---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^(hw|third-party)
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
            args: [--allow-multiple-documents]
          - id: check-added-large-files
    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: v17.0.6
      hooks:
          - id: clang-format
            types_or: [c++, c]
    - repo: https://github.com/cheshirekow/cmake-format-precommit
      rev: v0.6.10
      hooks:
          - id: cmake-format
    - repo: https://github.com/google/yapf
      rev: v0.43.0
      hooks:
          - id: yapf
            name: yapf
            args: [--style, google]
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
