servio: src/brd/proto4/board.cpp File Reference
board.cpp File Reference
#include "../../cfg/default.hpp"
#include "../../cnv/setup.hpp"
#include "../../core/drivers.hpp"
#include "../../core/globals.hpp"
#include "../../drv/adc_pooler_def.hpp"
#include "../../drv/char_uart.hpp"
#include "../../drv/clock.hpp"
#include "../../drv/cobs_uart.hpp"
#include "../../drv/drv8251.hpp"
#include "../../drv/dts_temp.hpp"
#include "../../drv/flash_cfg.hpp"
#include "../../drv/hbridge.hpp"
#include "../../drv/leds.hpp"
#include "../../drv/paged_i2c_eeprom.hpp"
#include "../../drv/quad_encoder.hpp"
#include "../../fw/util.hpp"
#include "../../plt/platform.hpp"
#include "../../sntr/central_sentry.hpp"
#include "../brd.hpp"
#include "flash_cfg.hpp"
#include "setup.hpp"
#include <emlabcpp/defer.h>
#include <emlabcpp/result.h>
Classes
struct servio::brd::adc_set
Namespaces
namespace servio
namespace servio::brd
Typedefs
using servio::brd::adc_pooler_type = drv::adc_pooler< adc_set >
Functions
cfg::map servio::brd::get_default_config ()
void servio::brd::flash_start_cb ()
void servio::brd::flash_stop_cb ()
void ADC1_IRQHandler ()
void TIM1_UP_IRQHandler ()
void TIM2_IRQHandler ()
void USART2_IRQHandler ()
void USART1_IRQHandler ()
void GPDMA1_Channel0_IRQHandler ()
void GPDMA1_Channel1_IRQHandler ()
void GPDMA1_Channel2_IRQHandler ()
void I2C2_ER_IRQHandler ()
void I2C2_EV_IRQHandler ()
void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef *h)
void HAL_UART_TxCpltCallback (UART_HandleTypeDef *h)
void HAL_UART_RxCpltCallback (UART_HandleTypeDef *h)
void HAL_UART_ErrorCallback (UART_HandleTypeDef *h)
void HAL_ADC_ConvCpltCallback (ADC_HandleTypeDef *h)
void HAL_ADC_ErrorCallback (ADC_HandleTypeDef *h)
adc_pooler_type * servio::brd::adc_pooler_setup (bool enable_pos)
drv::hbridge * servio::brd::hbridge_setup ()
drv::com_iface * servio::brd::comms_setup ()
drv::com_iface * servio::brd::setup_debug_comms ()
Initialize debug interface.
drv::leds * servio::brd::leds_setup ()
drv::pos_iface * servio::brd::quad_encoder_setup (uint32_t period)
void servio::brd::try_i2c_gpio_toggle ()
drv::storage_iface * servio::brd::eeprom_setup ()
status servio::brd::start_callback (core::drivers &cdrv)
void servio::brd::install_stop_callback (drv::pwm_motor_iface &motor, drv::leds_iface *leds_ptr)
status servio::brd::setup_board ()
An API that has to be implemented by each board variation.
core::drivers servio::brd::setup_core_drivers ()
Initialize all core drivers for the servo.
Variables
drv::pin_cfg servio::brd::HBRDIGE_VREF_PIN
cfg::context servio::brd::CFG { .map = get_default_config() }
TIM_HandleTypeDef servio::brd::TIM2_HANDLE = {}
drv::clock servio::brd::CLOCK { TIM2_HANDLE }
drv::leds servio::brd::LEDS {}
sntr::record servio::brd::INOPERABLE_RECORDS [16]
sntr::record servio::brd::DEGRADED_RECORDS [128]
sntr::central_sentry servio::brd::CENTRAL_SENTRY
ADC_HandleTypeDef servio::brd::ADC_HANDLE
DMA_HandleTypeDef servio::brd::GPDMA1_Ch0_HANDLE
TIM_HandleTypeDef servio::brd::TIM6_HANDLE
adc_pooler_type servio::brd::ADC_POOLER { ADC_HANDLE, GPDMA1_Ch0_HANDLE, TIM6_HANDLE }
drv::adc_pooler_period_cb< ADC_POOLER > servio::brd::ADC_PERIOD_CB
drv::adc_pooler_vcc< ADC_POOLER > servio::brd::ADC_VCC
drv::adc_pooler_position< ADC_POOLER > servio::brd::ADC_POSITION
drv::adc_pooler_current< ADC_POOLER > servio::brd::ADC_CURRENT
UART_HandleTypeDef servio::brd::UART2_HANDLE {}
DMA_HandleTypeDef servio::brd::GPDMA1_Ch2_HANDLE {}
drv::cobs_uart servio::brd::DEBUG_COMMS { "dcomms", CENTRAL_SENTRY, CLOCK, &UART2_HANDLE, &GPDMA1_Ch2_HANDLE }
UART_HandleTypeDef servio::brd::UART1_HANDLE {}
DMA_HandleTypeDef servio::brd::GPDMA1_Ch1_HANDLE {}
drv::char_uart servio::brd::COMMS { "comms", CENTRAL_SENTRY, CLOCK, &UART1_HANDLE, &GPDMA1_Ch1_HANDLE }
TIM_HandleTypeDef servio::brd::TIM1_HANDLE {}
drv::hbridge servio::brd::HBRIDGE { &TIM1_HANDLE }
DTS_HandleTypeDef servio::brd::DTS_HANDLE {}
drv::dts_temp servio::brd::DTS_DRV { DTS_HANDLE }
TIM_HandleTypeDef servio::brd::TIM3_HANDLE {}
drv::quad_encoder servio::brd::QUAD { TIM3_HANDLE }
TIM_HandleTypeDef * servio::brd::QUAD_TRIGGER_TIMER = nullptr
I2C_HandleTypeDef servio::brd::I2C2_HANDLE {}
drv::i2c_eeprom servio::brd::EEPROM { 0b1010'0000, 65'535u, 2'000u, I2C2_HANDLE }
std::array< em::view< std::byte * >, 2 > servio::brd::PERSISTENT_BLOCKS { page_at(0), page_at(1) }
drv::flash_storage servio::brd::FLASH_STORAGE { PERSISTENT_BLOCKS, flash_start_cb, flash_stop_cb }
Class Documentation
servio::brd::adc_set
struct servio::brd::adc_set
Class Members
typedef chan_ids id_type
Class Members
detailed_adc_channel< CURRENT_CHANNEL, 128 > current
adc_channel_with_callback< POSITION_CHANNEL > position
adc_channel< VCC_CHANNEL > vcc { { "vcc", CENTRAL_SENTRY } }
Function Documentation
ADC1_IRQHandler()
void ADC1_IRQHandler ()
References servio::brd::ADC_HANDLE.
GPDMA1_Channel0_IRQHandler()
void GPDMA1_Channel0_IRQHandler ()
References servio::brd::GPDMA1_Ch0_HANDLE.
GPDMA1_Channel1_IRQHandler()
void GPDMA1_Channel1_IRQHandler ()
References servio::brd::GPDMA1_Ch1_HANDLE.
GPDMA1_Channel2_IRQHandler()
void GPDMA1_Channel2_IRQHandler ()
References servio::brd::GPDMA1_Ch2_HANDLE.
HAL_ADC_ConvCpltCallback()
void HAL_ADC_ConvCpltCallback (ADC_HandleTypeDef * h)
References servio::drv::adc_pooler< Set >::adc_conv_cplt_irq(), and servio::brd::ADC_POOLER.
HAL_ADC_ErrorCallback()
void HAL_ADC_ErrorCallback (ADC_HandleTypeDef * h)
References servio::drv::adc_pooler< Set >::adc_error_irq(), and servio::brd::ADC_POOLER.
HAL_TIM_PeriodElapsedCallback()
void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef * h)
References servio::brd::CLOCK, servio::brd::HBRIDGE, servio::drv::quad_encoder::on_tick_irq(), servio::brd::QUAD, servio::brd::QUAD_TRIGGER_TIMER, servio::drv::clock::timer_period_irq(), and servio::drv::hbridge::timer_period_irq().
HAL_UART_ErrorCallback()
void HAL_UART_ErrorCallback (UART_HandleTypeDef * h)
References servio::brd::COMMS, servio::brd::DEBUG_COMMS, servio::drv::char_uart::err_irq(), and servio::drv::cobs_uart::err_irq().
HAL_UART_RxCpltCallback()
void HAL_UART_RxCpltCallback (UART_HandleTypeDef * h)
References servio::brd::COMMS, servio::brd::DEBUG_COMMS, servio::drv::char_uart::rx_cplt_irq(), and servio::drv::cobs_uart::rx_cplt_irq().
HAL_UART_TxCpltCallback()
void HAL_UART_TxCpltCallback (UART_HandleTypeDef * h)
References servio::brd::COMMS, servio::brd::DEBUG_COMMS, servio::drv::char_uart::tx_cplt_irq(), and servio::drv::cobs_uart::tx_cplt_irq().
I2C2_ER_IRQHandler()
void I2C2_ER_IRQHandler ()
References servio::brd::I2C2_HANDLE.
I2C2_EV_IRQHandler()
void I2C2_EV_IRQHandler ()
References servio::brd::I2C2_HANDLE.
TIM1_UP_IRQHandler()
void TIM1_UP_IRQHandler ()
References servio::brd::TIM1_HANDLE.
TIM2_IRQHandler()
void TIM2_IRQHandler ()
References servio::brd::TIM2_HANDLE.
USART1_IRQHandler()
void USART1_IRQHandler ()
References servio::brd::UART1_HANDLE.
USART2_IRQHandler()
void USART2_IRQHandler ()
References servio::brd::UART2_HANDLE.