servio: converter Class Reference
converter Class Reference
#include <converter.hpp>
Public Member Functions
void set_position_cfg (uint16_t low_value, float low_angle, uint16_t high_value, float high_angle)
float convert_position (uint32_t val) const
void set_current_cfg (float scale, float offset)
float convert_current (uint32_t val, int8_t direction) const
void set_temp_cfg (float scale, float offset)
float convert_temp (uint32_t val) const
void set_vcc_cfg (float scale)
float convert_vcc (uint32_t val) const
Member Function Documentation
convert_current()
float converter::convert_current (uint32_t val, int8_t direction) const inline
References current_converter::convert().
convert_position()
float converter::convert_position (uint32_t val) const inline
References position_converter::convert().
convert_temp()
float converter::convert_temp (uint32_t val) const inline
References temperature_converter::convert().
convert_vcc()
float converter::convert_vcc (uint32_t val) const inline
References voltage_converter::convert().
set_current_cfg()
void converter::set_current_cfg (float scale, float offset) inline
set_position_cfg()
void converter::set_position_cfg (uint16_t low_value, float low_angle, uint16_t high_value, float high_angle) inline
set_temp_cfg()
void converter::set_temp_cfg (float scale, float offset) inline
set_vcc_cfg()
void converter::set_vcc_cfg (float scale) inline
The documentation for this class was generated from the following file:
src/converter.hpp