servio: servio::monitor Class Reference
servio::monitor Class Reference
#include <monitor.hpp>
Public Member Functions
monitor (microseconds now, const ctl::control &ctl, const vcc_interface &vcc_drv, const temperature_interface &temp_drv, indication &indi, const cnv::converter &conv)
void set_minimum_voltage (float vcc)
void set_maximum_temperature (float temp)
void tick (microseconds now)
Constructor & Destructor Documentation
monitor()
servio::monitor::monitor (microseconds now, const ctl::control & ctl, const vcc_interface & vcc_drv, const temperature_interface & temp_drv, indication & indi, const cnv::converter & conv) inline
References servio::BOOTING, and servio::indication::on_event().
Member Function Documentation
set_maximum_temperature()
void servio::monitor::set_maximum_temperature (float temp) inline
set_minimum_voltage()
void servio::monitor::set_minimum_voltage (float vcc) inline
tick()
void servio::monitor::tick (microseconds now) inline
References servio::cnv::temperature_converter::convert(), servio::cnv::voltage_converter::convert(), servio::DISENGAGED, servio::ENGAGED, servio::ctl::control::get_mode(), servio::temperature_interface::get_temperature(), servio::vcc_interface::get_vcc(), servio::HEARTBEAT, servio::indication::on_event(), servio::cnv::converter::temp, servio::TEMPERATURE_HIGH, servio::cnv::converter::vcc, and servio::VOLTAGE_LOW.
The documentation for this class was generated from the following file:
src/monitor.hpp