servio: fw::drv::acquisition Class Reference
fw::drv::acquisition Class Reference
#include <acquisition.hpp>
Classes
struct detailed_sequence
struct handles
Public Member Functions
acquisition ()
bool setup (em::function_view< bool(handles &) >)
void adc_irq ()
void adc_conv_cplt_irq (ADC_HandleTypeDef *h)
void adc_error_irq (ADC_HandleTypeDef *h)
void dma_irq ()
void on_period_irq ()
void start ()
void set_current_callback (current_cb_interface &) override
current_cb_interface & get_current_callback () const override
void set_position_callback (position_cb_interface &) override
position_cb_interface & get_position_callback () const override
uint32_t get_current () const override
uint32_t get_position () const override
uint32_t get_vcc () const override
uint32_t get_temperature () const override
const acquisition_status & get_status () const
void clear_status ()
Public Member Functions inherited from fw::drv::position_interface
virtual ~position_interface ()=default
Public Member Functions inherited from fw::drv::current_interface
virtual ~current_interface ()=default
Public Member Functions inherited from fw::drv::vcc_interface
virtual ~vcc_interface ()=default
Public Member Functions inherited from fw::drv::temperature_interface
virtual ~temperature_interface ()=default
Public Member Functions inherited from fw::drv::period_cb_interface
virtual ~period_cb_interface ()=default
Static Public Attributes
static constexpr std::size_t chan_n = 4
static constexpr std::size_t detailed_chid = 0
Class Documentation
fw::drv::acquisition::handles
struct fw::drv::acquisition::handles
Class Members
ADC_HandleTypeDef adc
static_vector< ADC_ChannelConfTypeDef, chan_n > chconfs
DMA_HandleTypeDef dma
TIM_HandleTypeDef tim
uint32_t tim_channel
Constructor & Destructor Documentation
acquisition()
fw::drv::acquisition::acquisition ()
Member Function Documentation
adc_conv_cplt_irq()
void fw::drv::acquisition::adc_conv_cplt_irq (ADC_HandleTypeDef * h)
References fw::drv::acquisition::handles::adc, detailed_chid, and fw::drv::position_cb_interface::on_position_irq().
adc_error_irq()
void fw::drv::acquisition::adc_error_irq (ADC_HandleTypeDef * h)
adc_irq()
void fw::drv::acquisition::adc_irq ()
References fw::drv::acquisition::handles::adc.
clear_status()
void fw::drv::acquisition::clear_status () inline
dma_irq()
void fw::drv::acquisition::dma_irq ()
References fw::drv::acquisition::handles::dma.
get_current()
uint32_t fw::drv::acquisition::get_current () const inline override virtual
Implements fw::drv::current_interface.
get_current_callback()
current_cb_interface & fw::drv::acquisition::get_current_callback () const override virtual
Implements fw::drv::current_interface.
get_position()
uint32_t fw::drv::acquisition::get_position () const inline override virtual
Implements fw::drv::position_interface.
get_position_callback()
position_cb_interface & fw::drv::acquisition::get_position_callback () const override virtual
Implements fw::drv::position_interface.
get_status()
const acquisition_status& fw::drv::acquisition::get_status () const inline
get_temperature()
uint32_t fw::drv::acquisition::get_temperature () const inline override virtual
Implements fw::drv::temperature_interface.
get_vcc()
uint32_t fw::drv::acquisition::get_vcc () const inline override virtual
Implements fw::drv::vcc_interface.
on_period_irq()
void fw::drv::acquisition::on_period_irq () virtual
Implements fw::drv::period_cb_interface.
References fw::drv::acquisition::handles::adc, fw::drv::acquisition::detailed_sequence::buffer, fw::drv::acquisition::detailed_sequence::buffer_size, fw::drv::acquisition_status::buffer_was_full, fw::drv::acquisition::handles::chconfs, detailed_chid, fw::drv::acquisition::handles::dma, fw::drv::current_cb_interface::on_current_irq(), fw::drv::acquisition_status::start_failed, fw::stop_exec(), and fw::drv::acquisition::detailed_sequence::used.
set_current_callback()
void fw::drv::acquisition::set_current_callback (current_cb_interface & cb) override virtual
Implements fw::drv::current_interface.
set_position_callback()
void fw::drv::acquisition::set_position_callback (position_cb_interface & cb) override virtual
Implements fw::drv::position_interface.
setup()
bool fw::drv::acquisition::setup (em::function_view< bool(handles &) > setup_f)
start()
void fw::drv::acquisition::start ()
References fw::drv::acquisition::handles::tim, and fw::drv::acquisition::handles::tim_channel.
Member Data Documentation
chan_n
constexpr std::size_t fw::drv::acquisition::chan_n = 4 static constexpr
detailed_chid
constexpr std::size_t fw::drv::acquisition::detailed_chid = 0 static constexpr
The documentation for this class was generated from the following files:
src/fw/drv/acquisition.hpp
src/fw/drv/acquisition.cpp