servio: servio::core::current_callback Class Reference
servio::core::current_callback Class Reference
#include <callbacks.hpp>
Public Member Functions
current_callback (drv::pwm_motor_iface &motor, ctl::control &ctl, drv::clk_iface &clk, const cnv::converter &conv)
void on_value_irq (uint32_t curr, std::span< uint16_t >) override
Public Member Functions inherited from servio::drv::detailed_cb_iface
virtual ~detailed_cb_iface ()=default
Constructor & Destructor Documentation
current_callback()
servio::core::current_callback::current_callback (drv::pwm_motor_iface & motor, ctl::control & ctl, drv::clk_iface & clk, const cnv::converter & conv) inline
Member Function Documentation
on_value_irq()
void servio::core::current_callback::on_value_irq (uint32_t curr, std::span< uint16_t >) inline override virtual
Implements servio::drv::detailed_cb_iface.
References servio::core::avg_filter::add(), servio::cnv::current(), servio::ctl::control::current_irq(), servio::core::avg_filter::get(), servio::ctl::control::get_power(), servio::drv::clk_iface::get_us(), and servio::drv::pwm_motor_iface::set_power().
The documentation for this class was generated from the following file:
src/core/callbacks.hpp