servio: monitor Class Reference
monitor Class Reference
#include <monitor.hpp>
Public Member Functions
monitor (microseconds now, const control &ctl, const vcc_interface &vcc_drv, const temperature_interface &temp_drv, indication &indi, const converter &conv)
void set_minimum_voltage (float vcc)
void set_maximum_temperature (float temp)
void tick (microseconds now)
Constructor & Destructor Documentation
monitor()
monitor::monitor (microseconds now, const control & ctl, const vcc_interface & vcc_drv, const temperature_interface & temp_drv, indication & indi, const converter & conv) inline
References BOOTING, and indication::on_event().
Member Function Documentation
set_maximum_temperature()
void monitor::set_maximum_temperature (float temp) inline
set_minimum_voltage()
void monitor::set_minimum_voltage (float vcc) inline
tick()
void monitor::tick (microseconds now) inline
References cnv::temperature_converter::convert(), cnv::voltage_converter::convert(), DISENGAGED, ENGAGED, control::get_mode(), temperature_interface::get_temperature(), vcc_interface::get_vcc(), HEARTBEAT, indication::on_event(), converter::temp, TEMPERATURE_HIGH, converter::vcc, and VOLTAGE_LOW.
The documentation for this class was generated from the following file:
src/monitor.hpp