servio: fw::monitor Class Reference
fw::monitor Class Reference
#include <monitor.hpp>
Public Member Functions
monitor (microseconds now, const control &ctl, const drv::vcc_interface &vcc_drv, const drv::temperature_interface &temp_drv, indication &indi, const converter &conv)
void set_minimum_voltage (float vcc)
void set_maximum_temperature (float temp)
void tick (microseconds now)
Constructor & Destructor Documentation
monitor()
fw::monitor::monitor (microseconds now, const control & ctl, const drv::vcc_interface & vcc_drv, const drv::temperature_interface & temp_drv, indication & indi, const converter & conv) inline
References BOOTING, and indication::on_event().
Member Function Documentation
set_maximum_temperature()
void fw::monitor::set_maximum_temperature (float temp) inline
set_minimum_voltage()
void fw::monitor::set_minimum_voltage (float vcc) inline
tick()
void fw::monitor::tick (microseconds now) inline
References temperature_converter::convert(), voltage_converter::convert(), DISENGAGED, ENGAGED, control::get_mode(), fw::drv::temperature_interface::get_temperature(), fw::drv::vcc_interface::get_vcc(), HEARTBEAT, indication::on_event(), converter::temp, TEMPERATURE_HIGH, converter::vcc, and VOLTAGE_LOW.
The documentation for this class was generated from the following file:
src/fw/monitor.hpp