servio: servio::sntr::sentry Class Reference
servio::sntr::sentry Class Reference
#include <sentry.hpp>
Public Member Functions
sentry (const char *source_id, central_sentry_iface &central)
sentry (const sentry &)=delete
sentry (sentry &&)=delete
sentry & operator= (const sentry &)=delete
sentry & operator= (sentry &&)=delete
void set_inoperable (std::size_t eid, const char *emsg, const data_type &data=std::monostate{})
void set_inoperable_set (ecode_set set, const char *emsg, const data_type &data=std::monostate{})
void set_degraded (std::size_t eid, const char *emsg, const data_type &data=std::monostate{})
void set_degraded_set (ecode_set set, const char *emsg, const data_type &data=std::monostate{})
void unset_degraded (std::size_t eid)
~sentry ()
Constructor & Destructor Documentation
sentry() [1/3]
servio::sntr::sentry::sentry (const char * source_id, central_sentry_iface & central)
sentry() [2/3]
servio::sntr::sentry::sentry (const sentry &) delete
sentry() [3/3]
servio::sntr::sentry::sentry (sentry &&) delete
~sentry()
servio::sntr::sentry::~sentry ()
References set_inoperable(), and servio::sntr::terminated_eid.
Member Function Documentation
operator=() [1/2]
sentry& servio::sntr::sentry::operator= (const sentry &) delete
operator=() [2/2]
sentry& servio::sntr::sentry::operator= (sentry &&) delete
set_degraded()
void servio::sntr::sentry::set_degraded (std::size_t eid, const char * emsg, const data_type & data = std::monostate{})
References servio::sntr::forbidden_eid, servio::sntr::max_eid, and servio::sntr::central_sentry_iface::report_degraded().
set_degraded_set()
void servio::sntr::sentry::set_degraded_set (ecode_set set, const char * emsg, const data_type & data = std::monostate{})
References servio::sntr::central_sentry_iface::report_degraded().
set_inoperable()
void servio::sntr::sentry::set_inoperable (std::size_t eid, const char * emsg, const data_type & data = std::monostate{})
References servio::sntr::forbidden_eid, and servio::sntr::max_eid.
set_inoperable_set()
void servio::sntr::sentry::set_inoperable_set (ecode_set set, const char * emsg, const data_type & data = std::monostate{})
References servio::sntr::central_sentry_iface::report_inoperable().
unset_degraded()
void servio::sntr::sentry::unset_degraded (std::size_t eid)
References servio::sntr::central_sentry_iface::report_degraded().
The documentation for this class was generated from the following files:
src/sntr/sentry.hpp
src/sntr/sentry.cpp