servio: servio::metrics Class Reference
servio::metrics Class Reference
#include <metrics.hpp>
Public Member Functions
metrics (microseconds time, float position, limits< float > position_range)
void set_position_range (limits< float > position_range)
void set_moving_step (float step)
void position_irq (microseconds now, float position)
bool is_moving () const
float get_position () const
float get_velocity () const
Constructor & Destructor Documentation
metrics()
servio::metrics::metrics (microseconds time, float position, limits< float > position_range)
References set_position_range().
Member Function Documentation
get_position()
float servio::metrics::get_position () const inline
References servio::mtr::posvel_kalman::get_position().
get_velocity()
float servio::metrics::get_velocity () const inline
References servio::mtr::posvel_kalman::get_velocity().
is_moving()
bool servio::metrics::is_moving () const inline
References servio::static_detector::is_static.
position_irq()
void servio::metrics::position_irq (microseconds now, float position)
References servio::cnv::position(), servio::static_detector::update(), and servio::mtr::posvel_kalman::update().
set_moving_step()
void servio::metrics::set_moving_step (float step)
References servio::static_detector::set_step().
set_position_range()
void servio::metrics::set_position_range (limits< float > position_range)
References servio::mtr::posvel_kalman::set_position_range().
The documentation for this class was generated from the following files:
src/metrics.hpp
src/metrics.cpp