servio: control Class Reference
control Class Reference
#include <control.hpp>
Public Member Functions
control (std::chrono::milliseconds, ctl::config cfg)
void set_pid (control_loop, ctl::pid_coefficients coeffs)
void set_limits (control_loop, limits< float > lim)
bool is_engaged ()
control_mode get_mode ()
void disengage ()
void switch_to_power_control (int16_t power)
void switch_to_current_control (std::chrono::milliseconds now, float current)
void switch_to_velocity_control (std::chrono::milliseconds now, float velocity)
void switch_to_position_control (std::chrono::milliseconds now, float position)
void position_irq (std::chrono::milliseconds now, float position)
void velocity_irq (std::chrono::milliseconds now, float velocity)
void current_irq (std::chrono::milliseconds now, float current)
int16_t get_power () const
float get_desired_current () const
float get_desired_velocity () const
float get_desired_position () const
Constructor & Destructor Documentation
control()
control::control (std::chrono::milliseconds now, ctl::config cfg)
Member Function Documentation
current_irq()
void control::current_irq (std::chrono::milliseconds now, float current)
References ctl::pid_module::get_output(), POWER, and ctl::pid_module::update().
disengage()
void control::disengage ()
References switch_to_power_control().
get_desired_current()
float control::get_desired_current () const
References ctl::pid_module::get_desired().
get_desired_position()
float control::get_desired_position () const
References ctl::pid_module::get_desired().
get_desired_velocity()
float control::get_desired_velocity () const
References ctl::pid_module::get_desired().
get_mode()
control_mode control::get_mode ()
get_power()
int16_t control::get_power () const
is_engaged()
bool control::is_engaged ()
position_irq()
void control::position_irq (std::chrono::milliseconds now, float position)
References POSITION, ctl::pid_module::set_momentary_limit(), and ctl::pid_module::update().
set_limits()
void control::set_limits (control_loop cl, limits< float > lim)
References CURRENT, ctl::pid_module::set_config_limit(), and VELOCITY.
set_pid()
void control::set_pid (control_loop cl, ctl::pid_coefficients coeffs)
References ctl::pid_module::set_pid().
switch_to_current_control()
void control::switch_to_current_control (std::chrono::milliseconds now, float current)
References CURRENT, infty, ctl::pid_module::set_momentary_limit(), and ctl::pid_module::set_output().
switch_to_position_control()
void control::switch_to_position_control (std::chrono::milliseconds now, float position)
References POSITION, and ctl::pid_module::reset_momentary_limit().
switch_to_power_control()
void control::switch_to_power_control (int16_t power)
References POWER.
switch_to_velocity_control()
void control::switch_to_velocity_control (std::chrono::milliseconds now, float velocity)
References ctl::pid_module::reset_momentary_limit(), ctl::pid_module::set_output(), VELOCITY, and kalman::velocity().
velocity_irq()
void control::velocity_irq (std::chrono::milliseconds now, float velocity)
References ctl::pid_module::get_output(), POWER, ctl::pid_module::update(), and kalman::velocity().
The documentation for this class was generated from the following files:
src/control.hpp
src/control.cpp