servio: servio::mtr::metrics Class Reference
servio::mtr::metrics Class Reference
#include <metrics.hpp>
Public Member Functions
metrics (base::microseconds time, float position, base::limits< float > position_range)
void set_position_range (base::limits< float > position_range)
void set_moving_step (float step)
void position_irq (base::microseconds now, float position)
bool is_moving () const
float get_position () const
float get_velocity () const
Constructor & Destructor Documentation
metrics()
servio::mtr::metrics::metrics (base::microseconds time, float position, base::limits< float > position_range)
References set_position_range().
Member Function Documentation
get_position()
float servio::mtr::metrics::get_position () const inline
References servio::mtr::posvel_kalman::get_position().
get_velocity()
float servio::mtr::metrics::get_velocity () const inline
References servio::mtr::posvel_kalman::get_velocity().
is_moving()
bool servio::mtr::metrics::is_moving () const inline
References servio::mtr::static_detector::is_static.
position_irq()
void servio::mtr::metrics::position_irq (base::microseconds now, float position)
References servio::cnv::position(), servio::mtr::posvel_kalman::update(), and servio::mtr::static_detector::update().
set_moving_step()
void servio::mtr::metrics::set_moving_step (float step)
References servio::mtr::static_detector::set_step().
set_position_range()
void servio::mtr::metrics::set_position_range (base::limits< float > position_range)
References servio::mtr::posvel_kalman::set_position_range().
The documentation for this class was generated from the following files:
src/mtr/metrics.hpp
src/mtr/metrics.cpp