servio: servio::ftester::gtest Class Reference
servio::ftester::gtest Class Reference
Public Member Functions
gtest (test_system &sys, std::string name, em::testing::test_id tid, std::optional< std::filesystem::path > output_dir)
void SetUp () final
void TestBody () final
void TearDown () final
Constructor & Destructor Documentation
gtest()
servio::ftester::gtest::gtest (test_system & sys, std::string name, em::testing::test_id tid, std::optional< std::filesystem::path > output_dir) inline
Member Function Documentation
SetUp()
void servio::ftester::gtest::SetUp () inline final
References servio::ftester::test_system::clear().
TearDown()
void servio::ftester::gtest::TearDown () inline final
References servio::ftester::test_system::get_collected().
TestBody()
void servio::ftester::gtest::TestBody () inline final
References servio::ftester::test_system::run_test().
The documentation for this class was generated from the following file:
src/ftester/main.cpp