servio: servio::mon::monitor Class Reference
servio::mon::monitor Class Reference
#include <monitor.hpp>
Public Member Functions
monitor (base::microseconds now, const ctl::control &ctl, const base::vcc_interface &vcc_drv, const base::temperature_interface &temp_drv, indication &indi, const cnv::converter &conv)
void set_minimum_voltage (float vcc)
void set_maximum_temperature (float temp)
void tick (base::microseconds now)
Constructor & Destructor Documentation
monitor()
servio::mon::monitor::monitor (base::microseconds now, const ctl::control & ctl, const base::vcc_interface & vcc_drv, const base::temperature_interface & temp_drv, indication & indi, const cnv::converter & conv) inline
References servio::mon::BOOTING, and servio::mon::indication::on_event().
Member Function Documentation
set_maximum_temperature()
void servio::mon::monitor::set_maximum_temperature (float temp) inline
set_minimum_voltage()
void servio::mon::monitor::set_minimum_voltage (float vcc) inline
tick()
void servio::mon::monitor::tick (base::microseconds now) inline
References servio::cnv::temperature_converter::convert(), servio::cnv::voltage_converter::convert(), servio::base::DISENGAGED, servio::mon::DISENGAGED, servio::mon::ENGAGED, servio::ctl::control::get_mode(), servio::base::temperature_interface::get_temperature(), servio::base::vcc_interface::get_vcc(), servio::mon::HEARTBEAT, servio::mon::indication::on_event(), servio::cnv::converter::temp, servio::mon::TEMPERATURE_HIGH, servio::cnv::converter::vcc, and servio::mon::VOLTAGE_LOW.
The documentation for this class was generated from the following file:
src/mon/monitor.hpp