servio: fw::acquisition Class Reference
fw::acquisition Class Reference
#include <acquisition.hpp>
Classes
struct current_sequence
struct handles
Public Types
using current_callback = em::static_function< void(float), 16 >
using position_callback = em::static_function< void(float), 16 >
Public Member Functions
acquisition ()=default
bool setup (em::function_view< bool(handles &) >)
void adc_irq ()
void adc_conv_cplt_irq (ADC_HandleTypeDef *h)
void adc_error_irq (ADC_HandleTypeDef *h)
void dma_irq ()
void period_elapsed_irq (int8_t power_direction)
void start ()
void set_position_cfg (uint16_t low_value, float low_angle, uint16_t high_value, float high_angle)
void set_current_cfg (float scale, float offset)
void set_temp_cfg (float scale, float offset)
void set_vcc_cfg (float scale)
void set_current_callback (current_callback)
const current_callback & get_current_callback ()
em::view< const uint16_t * > get_current_reading () const
void set_position_callback (position_callback)
const position_callback & get_position_callback ()
float get_current () const
float get_position () const
float get_vcc () const
float get_temp () const
const acquisition_status & get_status () const
void clear_status ()
Class Documentation
fw::acquisition::handles
struct fw::acquisition::handles
Class Members
ADC_HandleTypeDef adc
ADC_ChannelConfTypeDef current_chconf
DMA_HandleTypeDef dma
ADC_ChannelConfTypeDef position_chconf
ADC_ChannelConfTypeDef temp_chconf
TIM_HandleTypeDef tim
uint32_t tim_channel
ADC_ChannelConfTypeDef vcc_chconf
Member Typedef Documentation
current_callback
using fw::acquisition::current_callback = em::static_function< void(float), 16 >
position_callback
using fw::acquisition::position_callback = em::static_function< void(float), 16 >
Constructor & Destructor Documentation
acquisition()
fw::acquisition::acquisition () default
Member Function Documentation
adc_conv_cplt_irq()
void fw::acquisition::adc_conv_cplt_irq (ADC_HandleTypeDef * h)
References fw::acquisition::handles::adc, position_converter::convert(), temperature_converter::convert(), and voltage_converter::convert().
adc_error_irq()
void fw::acquisition::adc_error_irq (ADC_HandleTypeDef * h)
References fw::stop_exec().
adc_irq()
void fw::acquisition::adc_irq ()
References fw::acquisition::handles::adc.
clear_status()
void fw::acquisition::clear_status () inline
dma_irq()
void fw::acquisition::dma_irq ()
References fw::acquisition::handles::dma.
get_current()
float fw::acquisition::get_current () const inline
get_current_callback()
const acquisition::current_callback & fw::acquisition::get_current_callback ()
get_current_reading()
em::view< const uint16_t * > fw::acquisition::get_current_reading () const
References fw::acquisition::current_sequence::buffer, and fw::acquisition::current_sequence::used.
get_position()
float fw::acquisition::get_position () const inline
get_position_callback()
const acquisition::position_callback & fw::acquisition::get_position_callback ()
get_status()
const acquisition_status& fw::acquisition::get_status () const inline
get_temp()
float fw::acquisition::get_temp () const inline
get_vcc()
float fw::acquisition::get_vcc () const inline
period_elapsed_irq()
void fw::acquisition::period_elapsed_irq (int8_t power_direction)
References fw::acquisition::handles::adc, fw::acquisition::current_sequence::buffer, fw::acquisition::current_sequence::buffer_size, fw::acquisition_status::buffer_was_full, current_converter::convert(), fw::acquisition::handles::dma, fw::stop_exec(), and fw::acquisition::current_sequence::used.
set_current_callback()
void fw::acquisition::set_current_callback (current_callback f)
set_current_cfg()
void fw::acquisition::set_current_cfg (float scale, float offset)
set_position_callback()
void fw::acquisition::set_position_callback (position_callback cb)
set_position_cfg()
void fw::acquisition::set_position_cfg (uint16_t low_value, float low_angle, uint16_t high_value, float high_angle)
set_temp_cfg()
void fw::acquisition::set_temp_cfg (float scale, float offset)
set_vcc_cfg()
void fw::acquisition::set_vcc_cfg (float scale)
setup()
bool fw::acquisition::setup (em::function_view< bool(handles &) > setup_f)
start()
void fw::acquisition::start ()
References fw::acquisition::handles::tim, and fw::acquisition::handles::tim_channel.
The documentation for this class was generated from the following files:
src/fw/drivers/acquisition.hpp
src/fw/drivers/acquisition.cpp