servio: servio::control Class Reference
servio::control Class Reference
#include <control.hpp>
Public Member Functions
control (microseconds, ctl::config cfg={})
void set_pid (control_loop, ctl::pid_coefficients coeffs)
void set_limits (control_loop, limits< float > lim)
void set_static_friction (float scale, float decay)
void set_pos_to_vel_lim_scale (float scale)
void set_vel_to_curr_lim_scale (float scale)
void disengage ()
void switch_to_power_control (int16_t power)
void switch_to_current_control (microseconds now, float current)
void switch_to_velocity_control (microseconds now, float velocity)
void switch_to_position_control (microseconds now, float position)
void moving_irq (microseconds now, bool is_moving)
void position_irq (microseconds now, float position)
void velocity_irq (microseconds now, float velocity)
void current_irq (microseconds now, float current)
int16_t get_power () const
float get_desired_current () const
float get_desired_velocity () const
float get_desired_position () const
control_mode get_mode () const
Constructor & Destructor Documentation
control()
servio::control::control (microseconds now, ctl::config cfg = {})
References servio::ctl::config::current_limits, and servio::ctl::config::position_pid.
Member Function Documentation
current_irq()
void servio::control::current_irq (microseconds now, float current)
References servio::cnv::current(), and servio::kalman::update().
disengage()
void servio::control::disengage ()
get_desired_current()
float servio::control::get_desired_current () const
get_desired_position()
float servio::control::get_desired_position () const
get_desired_velocity()
float servio::control::get_desired_velocity () const
get_mode()
control_mode servio::control::get_mode () const inline
get_power()
int16_t servio::control::get_power () const
moving_irq()
void servio::control::moving_irq (microseconds now, bool is_moving)
position_irq()
void servio::control::position_irq (microseconds now, float position)
References servio::cnv::position(), and servio::kalman::update().
set_limits()
void servio::control::set_limits (control_loop cl, limits< float > lim)
set_pid()
void servio::control::set_pid (control_loop cl, ctl::pid_coefficients coeffs)
set_pos_to_vel_lim_scale()
void servio::control::set_pos_to_vel_lim_scale (float scale)
set_static_friction()
void servio::control::set_static_friction (float scale, float decay)
set_vel_to_curr_lim_scale()
void servio::control::set_vel_to_curr_lim_scale (float scale)
switch_to_current_control()
void servio::control::switch_to_current_control (microseconds now, float current)
References servio::cnv::current().
switch_to_position_control()
void servio::control::switch_to_position_control (microseconds now, float position)
References servio::cnv::position().
switch_to_power_control()
void servio::control::switch_to_power_control (int16_t power)
switch_to_velocity_control()
void servio::control::switch_to_velocity_control (microseconds now, float velocity)
References servio::kalman::velocity().
velocity_irq()
void servio::control::velocity_irq (microseconds now, float velocity)
References servio::kalman::update(), and servio::kalman::velocity().
The documentation for this class was generated from the following files:
src/control.hpp
src/control.cpp