servio: servio::drv::cobs_uart Class Reference
servio::drv::cobs_uart Class Reference
#include <cobs_uart.hpp>
Public Member Functions
cobs_uart (const char *id, sntr::central_sentry_iface &central, clk_iface &clk, UART_HandleTypeDef *uart, DMA_HandleTypeDef *tx_dma)
cobs_uart (const cobs_uart &)=delete
cobs_uart (cobs_uart &&)=delete
cobs_uart & operator= (const cobs_uart &)=delete
cobs_uart & operator= (cobs_uart &&)=delete
void rx_cplt_irq (UART_HandleTypeDef *huart)
void tx_cplt_irq (UART_HandleTypeDef *huart)
void err_irq (UART_HandleTypeDef *huart)
com_res recv (std::span< std::byte > data) override
em::result start () override
em::result send (std::span< const std::span< const std::byte > > data, microseconds timeout) override
Public Member Functions inherited from servio::drv::com_iface
virtual ~com_iface ()=default
Static Public Attributes
static constexpr uint32_t tolerable_hal_errors
Constructor & Destructor Documentation
cobs_uart() [1/3]
servio::drv::cobs_uart::cobs_uart (const char * id, sntr::central_sentry_iface & central, clk_iface & clk, UART_HandleTypeDef * uart, DMA_HandleTypeDef * tx_dma) inline
cobs_uart() [2/3]
servio::drv::cobs_uart::cobs_uart (const cobs_uart &) delete
cobs_uart() [3/3]
servio::drv::cobs_uart::cobs_uart (cobs_uart &&) delete
Member Function Documentation
err_irq()
void servio::drv::cobs_uart::err_irq (UART_HandleTypeDef * huart) inline
References servio::sntr::sentry::set_degraded_set(), servio::sntr::sentry::set_inoperable_set(), and tolerable_hal_errors.
operator=() [1/2]
cobs_uart& servio::drv::cobs_uart::operator= (cobs_uart &&) delete
operator=() [2/2]
cobs_uart& servio::drv::cobs_uart::operator= (const cobs_uart &) delete
recv()
com_res servio::drv::cobs_uart::recv (std::span< std::byte > data) override virtual
Implements servio::drv::com_iface.
References servio::drv::bits::load_message().
rx_cplt_irq()
void servio::drv::cobs_uart::rx_cplt_irq (UART_HandleTypeDef * huart) inline
References servio::drv::COBS_HAL_RX_START_ERR, servio::drv::bits::on_rx_cplt_irq(), servio::sntr::sentry::set_inoperable(), and start().
send()
em::result servio::drv::cobs_uart::send (std::span< const std::span< const std::byte > > data, microseconds timeout) override virtual
Implements servio::drv::com_iface.
References servio::drv::clk_iface::get_us().
start()
em::result servio::drv::cobs_uart::start () inline override virtual
Implements servio::drv::com_iface.
tx_cplt_irq()
void servio::drv::cobs_uart::tx_cplt_irq (UART_HandleTypeDef * huart) inline
Member Data Documentation
tolerable_hal_errors
constexpr uint32_t servio::drv::cobs_uart::tolerable_hal_errors static constexpr
Initial value:
=
            HAL_UART_ERROR_ORE | HAL_UART_ERROR_DMA | HAL_UART_ERROR_FE | HAL_UART_ERROR_NE
The documentation for this class was generated from the following files:
src/drv/cobs_uart.hpp
src/drv/cobs_uart.cpp