servio: servio::ctl::control Class Reference
servio::ctl::control Class Reference
#include <control.hpp>
Public Member Functions
control (base::microseconds, ctl::config cfg={})
void set_pid (base::control_loop, ctl::pid_coefficients coeffs)
void set_limits (base::control_loop, base::limits< float > lim)
void set_static_friction (float scale, float decay)
void set_pos_to_vel_lim_scale (float scale)
void set_vel_to_curr_lim_scale (float scale)
void disengage ()
void switch_to_power_control (int16_t power)
void switch_to_current_control (base::microseconds now, float current)
void switch_to_velocity_control (base::microseconds now, float velocity)
void switch_to_position_control (base::microseconds now, float position)
void moving_irq (base::microseconds now, bool is_moving)
void position_irq (base::microseconds now, float position)
void velocity_irq (base::microseconds now, float velocity)
void current_irq (base::microseconds now, float current)
int16_t get_power () const
float get_desired_current () const
float get_desired_velocity () const
float get_desired_position () const
base::control_mode get_mode () const
Constructor & Destructor Documentation
control()
servio::ctl::control::control (base::microseconds now, ctl::config cfg = {})
References servio::ctl::config::current_limits, and servio::ctl::config::position_pid.
Member Function Documentation
current_irq()
void servio::ctl::control::current_irq (base::microseconds now, float current)
References servio::cnv::current(), servio::base::DISENGAGED, servio::base::POWER, and servio::klmn::update().
disengage()
void servio::ctl::control::disengage ()
References servio::base::DISENGAGED.
get_desired_current()
float servio::ctl::control::get_desired_current () const
References servio::base::CURRENT, servio::base::DISENGAGED, servio::base::POSITION, servio::base::POWER, and servio::base::VELOCITY.
get_desired_position()
float servio::ctl::control::get_desired_position () const
get_desired_velocity()
float servio::ctl::control::get_desired_velocity () const
get_mode()
base::control_mode servio::ctl::control::get_mode () const inline
get_power()
int16_t servio::ctl::control::get_power () const
moving_irq()
void servio::ctl::control::moving_irq (base::microseconds now, bool is_moving)
position_irq()
void servio::ctl::control::position_irq (base::microseconds now, float position)
References servio::base::POSITION, servio::cnv::position(), and servio::klmn::update().
set_limits()
void servio::ctl::control::set_limits (base::control_loop cl, base::limits< float > lim)
References servio::base::CURRENT, servio::base::POSITION, and servio::base::VELOCITY.
set_pid()
void servio::ctl::control::set_pid (base::control_loop cl, ctl::pid_coefficients coeffs)
set_pos_to_vel_lim_scale()
void servio::ctl::control::set_pos_to_vel_lim_scale (float scale)
set_static_friction()
void servio::ctl::control::set_static_friction (float scale, float decay)
set_vel_to_curr_lim_scale()
void servio::ctl::control::set_vel_to_curr_lim_scale (float scale)
switch_to_current_control()
void servio::ctl::control::switch_to_current_control (base::microseconds now, float current)
References servio::base::CURRENT, and servio::cnv::current().
switch_to_position_control()
void servio::ctl::control::switch_to_position_control (base::microseconds now, float position)
References servio::base::POSITION, and servio::cnv::position().
switch_to_power_control()
void servio::ctl::control::switch_to_power_control (int16_t power)
References servio::base::POWER.
switch_to_velocity_control()
void servio::ctl::control::switch_to_velocity_control (base::microseconds now, float velocity)
References servio::base::VELOCITY, and servio::klmn::velocity().
velocity_irq()
void servio::ctl::control::velocity_irq (base::microseconds now, float velocity)
References servio::klmn::update(), servio::base::VELOCITY, and servio::klmn::velocity().
The documentation for this class was generated from the following files:
src/ctl/control.hpp
src/ctl/control.cpp