servio: fw::position_callback Class Reference
fw::position_callback Class Reference
#include <callbacks.hpp>
Public Member Functions
position_callback (control &ctl, metrics &met, clock &clk, const converter &conv)
virtual void on_position (uint32_t position)
Public Member Functions inherited from position_cb_interface
virtual ~position_cb_interface ()=default
Constructor & Destructor Documentation
position_callback()
fw::position_callback::position_callback (control & ctl, metrics & met, clock & clk, const converter & conv) inline
Member Function Documentation
on_position()
virtual void fw::position_callback::on_position (uint32_t position) inline virtual
Implements position_cb_interface.
References position_converter::convert(), metrics::get_position(), fw::clock::get_us(), metrics::get_velocity(), metrics::is_moving(), control::moving_irq(), converter::position, fw::position(), control::position_irq(), metrics::position_irq(), and control::velocity_irq().
The documentation for this class was generated from the following file:
src/fw/callbacks.hpp