servio: metrics Class Reference
metrics Class Reference
#include <metrics.hpp>
Public Member Functions
metrics (microseconds time, float position, limits< float > position_range)
void set_position_range (limits< float > position_range)
void set_moving_step (float step)
void position_irq (microseconds now, float position)
bool is_moving () const
float get_position () const
float get_velocity () const
Constructor & Destructor Documentation
metrics()
metrics::metrics (microseconds time, float position, limits< float > position_range)
References set_position_range().
Member Function Documentation
get_position()
float metrics::get_position () const
References mtr::posvel_kalman::get_position().
get_velocity()
float metrics::get_velocity () const
References mtr::posvel_kalman::get_velocity().
is_moving()
bool metrics::is_moving () const
References static_detector::is_static.
position_irq()
void metrics::position_irq (microseconds now, float position)
References fw::position(), static_detector::update(), and mtr::posvel_kalman::update().
set_moving_step()
void metrics::set_moving_step (float step)
References static_detector::set_step().
set_position_range()
void metrics::set_position_range (limits< float > position_range)
References mtr::posvel_kalman::set_position_range().
The documentation for this class was generated from the following files:
src/metrics.hpp
src/metrics.cpp