servio: src/fw/extra.cpp File Reference
extra.cpp File Reference
#include "util.hpp"
#include <cstdlib>
#include <exception>
#include <new>
Functions
void * operator new (std::size_t)
void operator delete (void *) noexcept
void operator delete (void *, std::size_t) noexcept
void * operator new (std::size_t, std::align_val_t)
void operator delete (void *, std::align_val_t) noexcept
int _getpid (void)
void _kill (int)
void _exit (int)
int _write (int, char *, int)
int _read ()
int _close ()
int _lseek ()
Function Documentation
_close()
int _close ()
_exit()
void _exit (int)
_getpid()
int _getpid (void)
_kill()
void _kill (int)
_lseek()
int _lseek ()
_read()
int _read ()
_write()
int _write (int , char * , int)
operator delete() [1/3]
void operator delete (void *) noexcept
References servio::fw::stop_exec().
operator delete() [2/3]
void operator delete (void * , std::align_val_t) noexcept
References servio::fw::stop_exec().
operator delete() [3/3]
void operator delete (void * , std::size_t) noexcept
References servio::fw::stop_exec().
operator new() [1/2]
void* operator new (std::size_t)
References servio::fw::stop_exec().
operator new() [2/2]
void* operator new (std::size_t , std::align_val_t)
References servio::fw::stop_exec().