servio: src/ftest/main.cpp File Reference
main.cpp File Reference
#include "ftest/setup_tests.hpp"
#include "ftest/testing_system.hpp"
#include "fw/context.hpp"
Functions
int main ()
Variables
em::pmr::stack_resource< 1024 > TEST_STACK
Function Documentation
main()
int main ()
References servio::fw::context::cdrv, servio::fw::context::core, servio::brd::setup_board(), servio::fw::setup_context(), servio::brd::setup_debug_comms(), servio::ftest::setup_tests(), servio::drv::com_interface::start(), servio::fw::stop_exec(), TEST_STACK, and servio::fw::context::tick().
Variable Documentation
TEST_STACK
em::pmr::stack_resource< 1024 > TEST_STACK