servio: src/fw/main.cpp File Reference
main.cpp File Reference
#include "brd.hpp"
#include "cfg/dispatcher.hpp"
#include "core/core.hpp"
#include "core/drivers.hpp"
#include "emlabcpp/result.h"
#include "fw/dispatcher.hpp"
#include "fw/servio_pb.hpp"
#include "fw/store_persistent_config.hpp"
#include "fw/util.hpp"
#include "load_persistent_config.hpp"
Functions
int main ()
Variables
std::byte INPUT_BUFFER [HostToServioPacket_size]
std::byte OUTPUT_BUFFER [ServioToHostPacket_size]
Function Documentation
main()
int main ()
References servio::core::drivers::any_uninitialized(), servio::core::drivers::clock, servio::core::drivers::comms, servio::core::drivers::current, servio::cfg::dispatcher::full_apply(), servio::brd::get_default_config(), servio::brd::get_persistent_pages(), servio::base::clk_interface::get_us(), servio::fw::handle_message_packet(), servio::mon::INCOMING_MESSAGE, servio::mon::INITIALIZED, INPUT_BUFFER, servio::core::drivers::leds, servio::base::com_interface::load_message(), servio::fw::load_persistent_config(), servio::core::drivers::motor, servio::fw::dispatcher::motor, OUTPUT_BUFFER, servio::core::drivers::period, servio::core::drivers::period_cb, servio::core::drivers::position, servio::base::com_interface::send(), servio::core::standard_callbacks::set_callbacks(), servio::brd::setup_board(), servio::brd::setup_core_drivers(), servio::core::drivers::start_cb, servio::fw::stop_exec(), servio::core::drivers::temperature, servio::base::leds_interface::update(), and servio::core::drivers::vcc.
Variable Documentation
INPUT_BUFFER
std::byte INPUT_BUFFER[HostToServioPacket_size]
OUTPUT_BUFFER
std::byte OUTPUT_BUFFER[ServioToHostPacket_size]