servio: src/host/main.cpp File Reference
main.cpp File Reference
#include "host/cli.hpp"
#include "host/config_cmds.hpp"
#include "host/serial.hpp"
#include "io.pb.h"
#include <emlabcpp/algorithm.h>
#include <filesystem>
Classes
struct cfg_opts
struct mode_opts
Functions
void json_flag (CLI::App *app, bool &flag)
void field_option (CLI::App *app, std::string &field)
void cfg_def (CLI::App &app, boost::asio::io_context &context, std::unique_ptr< boost::asio::serial_port > &port_ptr)
boost::asio::awaitable< void > pool_cmd (boost::asio::io_context &, boost::asio::serial_port &port, std::vector< const google::protobuf::FieldDescriptor * > fields)
boost::asio::awaitable< void > pool_cmd (boost::asio::io_context &context, boost::asio::serial_port &port, std::vector< std::string > properties)
void pool_def (CLI::App &app, boost::asio::io_context &context, std::unique_ptr< boost::asio::serial_port > &port_ptr)
void mode_def (CLI::App &app, boost::asio::io_context &context, std::unique_ptr< boost::asio::serial_port > &port_ptr)
int main (int argc, char *argv[])
Class Documentation
cfg_opts
struct cfg_opts
Class Members
string field
bool json
string value
mode_opts
struct mode_opts
Class Members
float angle
float current
float velocity
Function Documentation
cfg_def()
void cfg_def (CLI::App & app, boost::asio::io_context & context, std::unique_ptr< boost::asio::serial_port > & port_ptr)
References host::cfg_clear_cmd(), host::cfg_commit_cmd(), host::cfg_get_cmd(), host::cfg_query_cmd(), host::cfg_set_cmd(), field_option(), and json_flag().
field_option()
void field_option (CLI::App * app, std::string & field)
json_flag()
void json_flag (CLI::App * app, bool & flag)
main()
int main (int argc, char * argv[])
References cfg_def(), host::common_cli::context, mode_def(), pool_def(), host::common_cli::port_ptr, and host::common_cli::setup().
mode_def()
void mode_def (CLI::App & app, boost::asio::io_context & context, std::unique_ptr< boost::asio::serial_port > & port_ptr)
References fw::current(), fw::position(), host::set_mode_current(), host::set_mode_disengaged(), host::set_mode_position(), host::set_mode_velocity(), and kalman::velocity().
pool_cmd() [1/2]
boost::asio::awaitable< void > pool_cmd (boost::asio::io_context & , boost::asio::serial_port & port, std::vector< const google::protobuf::FieldDescriptor * > fields)
References host::get_property().
pool_cmd() [2/2]
boost::asio::awaitable< void > pool_cmd (boost::asio::io_context & context, boost::asio::serial_port & port, std::vector< std::string > properties)
References pool_cmd().
pool_def()
void pool_def (CLI::App & app, boost::asio::io_context & context, std::unique_ptr< boost::asio::serial_port > & port_ptr)
References pool_cmd().