servio: src/fw/main.cpp File Reference
main.cpp File Reference
#include "control.hpp"
#include "fw/board.hpp"
#include "fw/callbacks.hpp"
#include "fw/cfg_dispatcher.hpp"
#include "fw/dispatcher.hpp"
#include "fw/globals.hpp"
#include "fw/monitor.hpp"
#include "indication.hpp"
#include "metrics.hpp"
#include "protocol.hpp"
#include <emlabcpp/algorithm.h>
#include <emlabcpp/iterators/numeric.h>
#include <emlabcpp/match.h>
#include <emlabcpp/pid.h>
#include <string>
Functions
int main ()
Variables
cfg_map CONFIG
Function Documentation
main()
int main ()
References brd::apply_config(), CONFIG, fw::leds::force_red_led(), fw::comms::get_message(), fw::acquisition::get_position(), INCOMING_MESSAGE, INITIALIZED, fw::acquisition::set_current_callback(), fw::hbridge::set_period_callback(), fw::acquisition::set_position_callback(), brd::setup_acquisition(), brd::setup_board(), brd::setup_comms(), brd::setup_debug_comms(), brd::setup_hbridge(), brd::setup_leds(), fw::acquisition::start(), fw::hbridge::start(), fw::comms::start_receiving(), fw::debug_comms::start_receiving(), fw::STOP_CALLBACK, fw::stop_exec(), fw::ticks_ms(), and fw::leds::update().
Variable Documentation
CONFIG
cfg_map CONFIG