servio: src/bb/modes_test.cpp File Reference
modes_test.cpp File Reference
#include "bb_test_case.hpp"
#include "scmdio/cli.hpp"
#include "scmdio/exceptions.hpp"
#include "scmdio/serial.hpp"
#include <emlabcpp/experimental/logging.h>
#include <filesystem>
#include <gtest/gtest.h>
Namespaces
servio
servio::bb
Functions
boost::asio::awaitable< void > servio::bb::check_mode (scmdio::cobs_port &port, servio::Mode m)
boost::asio::awaitable< void > servio::bb::disengage (boost::asio::io_context &, scmdio::cobs_port &port)
boost::asio::awaitable< void > servio::bb::test_disengaged (boost::asio::io_context &, scmdio::cobs_port &port)
boost::asio::awaitable< void > servio::bb::test_power (boost::asio::io_context &io, scmdio::cobs_port &port)
boost::asio::awaitable< void > servio::bb::test_current (boost::asio::io_context &io, scmdio::cobs_port &port)
boost::asio::awaitable< void > servio::bb::test_velocity (boost::asio::io_context &io, scmdio::cobs_port &port)
boost::asio::awaitable< void > servio::bb::test_position (boost::asio::io_context &io, scmdio::cobs_port &port)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References servio::scmdio::powerless_flag(), servio::bb::register_test(), servio::scmdio::common_cli::setup(), servio::bb::test_current(), servio::bb::test_disengaged(), servio::bb::test_position(), servio::bb::test_power(), servio::bb::test_velocity(), and servio::scmdio::verbose_opt().