servio: scmdio Namespace Reference
scmdio Namespace Reference
Classes
struct cobs_port
struct common_cli
struct servio_exception
struct reply_error
struct error_exception
struct serialize_error
struct parse_error
struct cfg_opts
struct mode_opts
Functions
CLI::Option * verbose_opt (CLI::App &app, bool &val)
CLI::Option * device_opt (CLI::App &app, std::filesystem::path &device)
CLI::Option * baudrate_opt (CLI::App &app, unsigned &baudrate)
CLI::Option * powerless_flag (CLI::App &app, bool &is_powerless)
boost::asio::awaitable< void > cfg_query_cmd (cobs_port &port, bool json)
boost::asio::awaitable< void > cfg_commit_cmd (cobs_port &port)
boost::asio::awaitable< void > cfg_clear_cmd (cobs_port &port)
boost::asio::awaitable< void > cfg_get_cmd (cobs_port &port, const std::string &name, bool json)
boost::asio::awaitable< void > cfg_set_cmd (cobs_port &port, const std::string &name, std::string value)
void json_flag (CLI::App *app, bool &flag)
void field_option (CLI::App *app, std::string &field)
void cfg_def (CLI::App &app, boost::asio::io_context &context, std::unique_ptr< cobs_port > &port_ptr)
boost::asio::awaitable< void > pool_cmd (boost::asio::io_context &, cobs_port &port, std::vector< const google::protobuf::FieldDescriptor * > fields)
boost::asio::awaitable< void > pool_cmd (boost::asio::io_context &context, cobs_port &port, std::vector< std::string > properties)
void pool_def (CLI::App &app, boost::asio::io_context &context, std::unique_ptr< cobs_port > &port_ptr)
void mode_def (CLI::App &app, boost::asio::io_context &context, std::unique_ptr< cobs_port > &port_ptr)
boost::asio::awaitable< void > write (cobs_port &port, const servio::HostToServio &payload)
Writes a reply to servo port.
boost::asio::awaitable< servio::ServioToHost > read (cobs_port &port)
Reads a reply from servo over port.
boost::asio::awaitable< servio::ServioToHost > exchange (cobs_port &port, const servio::HostToServio &msg)
Exchanges messages with the servo over port.
boost::asio::awaitable< servio::Config > get_config_field (cobs_port &port, const google::protobuf::FieldDescriptor *field)
Loads a config field specified by field from servo over port.
boost::asio::awaitable< void > set_config_field (cobs_port &port, const servio::Config &cfg)
Sets config field defined by cfg to serv over port.
boost::asio::awaitable< std::vector< servio::Config > > get_full_config (cobs_port &port)
Loads full config of servo over port.
boost::asio::awaitable< servio::Property > get_property (cobs_port &port, uint32_t field_id)
boost::asio::awaitable< servio::Property > get_property (cobs_port &port, servio::Property::PldCase field_id)
boost::asio::awaitable< servio::Property > get_property (cobs_port &port, const google::protobuf::FieldDescriptor *field)
boost::asio::awaitable< servio::Mode > get_property_mode (cobs_port &port)
TODO: error checking for the getters.
boost::asio::awaitable< float > get_property_current (cobs_port &port)
boost::asio::awaitable< float > get_property_position (cobs_port &port)
boost::asio::awaitable< float > get_property_velocity (cobs_port &port)
boost::asio::awaitable< void > set_mode (cobs_port &port, servio::Mode mode)
boost::asio::awaitable< void > set_mode_disengaged (cobs_port &port)
boost::asio::awaitable< void > set_mode_position (cobs_port &port, float angle)
boost::asio::awaitable< void > set_mode_velocity (cobs_port &port, float vel)
boost::asio::awaitable< void > set_mode_current (cobs_port &port, float curr)
Class Documentation
scmdio::cfg_opts
struct scmdio::cfg_opts
Class Members
string field
bool json
string value
scmdio::mode_opts
struct scmdio::mode_opts
Class Members
float angle
float current
float velocity
Function Documentation
baudrate_opt()
CLI::Option * scmdio::baudrate_opt (CLI::App & app, unsigned & baudrate)
cfg_clear_cmd()
boost::asio::awaitable< void > scmdio::cfg_clear_cmd (cobs_port & port)
References exchange().
cfg_commit_cmd()
boost::asio::awaitable< void > scmdio::cfg_commit_cmd (cobs_port & port)
References exchange().
cfg_def()
void scmdio::cfg_def (CLI::App & app, boost::asio::io_context & context, std::unique_ptr< cobs_port > & port_ptr)
References cfg_clear_cmd(), cfg_commit_cmd(), cfg_get_cmd(), cfg_query_cmd(), cfg_set_cmd(), field_option(), and json_flag().
cfg_get_cmd()
boost::asio::awaitable< void > scmdio::cfg_get_cmd (cobs_port & port, const std::string & name, bool json)
References get_config_field().
cfg_query_cmd()
boost::asio::awaitable< void > scmdio::cfg_query_cmd (cobs_port & port, bool json)
References get_full_config().
cfg_set_cmd()
boost::asio::awaitable< void > scmdio::cfg_set_cmd (cobs_port & port, const std::string & name, std::string value)
References exchange().
device_opt()
CLI::Option * scmdio::device_opt (CLI::App & app, std::filesystem::path & device)
exchange()
boost::asio::awaitable< servio::ServioToHost > scmdio::exchange (cobs_port & port, const servio::HostToServio & msg)
Exchanges messages with the servo over port.
References scmdio::error_exception::msg, read(), and write().
field_option()
void scmdio::field_option (CLI::App * app, std::string & field)
get_config_field()
boost::asio::awaitable< servio::Config > scmdio::get_config_field (cobs_port & port, const google::protobuf::FieldDescriptor * field)
Loads a config field specified by field from servo over port.
References exchange().
get_full_config()
boost::asio::awaitable< std::vector< servio::Config > > scmdio::get_full_config (cobs_port & port)
Loads full config of servo over port.
References get_config_field().
get_property() [1/3]
boost::asio::awaitable< servio::Property > scmdio::get_property (cobs_port & port, const google::protobuf::FieldDescriptor * field)
References get_property().
get_property() [2/3]
boost::asio::awaitable< servio::Property > scmdio::get_property (cobs_port & port, servio::Property::PldCase field_id)
References get_property().
get_property() [3/3]
boost::asio::awaitable< servio::Property > scmdio::get_property (cobs_port & port, uint32_t field_id)
References exchange().
get_property_current()
boost::asio::awaitable< float > scmdio::get_property_current (cobs_port & port)
References get_property().
get_property_mode()
boost::asio::awaitable< servio::Mode > scmdio::get_property_mode (cobs_port & port)
TODO: error checking for the getters.
References get_property().
get_property_position()
boost::asio::awaitable< float > scmdio::get_property_position (cobs_port & port)
References get_property().
get_property_velocity()
boost::asio::awaitable< float > scmdio::get_property_velocity (cobs_port & port)
References get_property().
json_flag()
void scmdio::json_flag (CLI::App * app, bool & flag)
mode_def()
void scmdio::mode_def (CLI::App & app, boost::asio::io_context & context, std::unique_ptr< cobs_port > & port_ptr)
References cnv::current(), cnv::position(), set_mode_current(), set_mode_disengaged(), set_mode_position(), set_mode_velocity(), and kalman::velocity().
pool_cmd() [1/2]
boost::asio::awaitable< void > scmdio::pool_cmd (boost::asio::io_context & , cobs_port & port, std::vector< const google::protobuf::FieldDescriptor * > fields)
References get_property().
pool_cmd() [2/2]
boost::asio::awaitable< void > scmdio::pool_cmd (boost::asio::io_context & context, cobs_port & port, std::vector< std::string > properties)
References pool_cmd().
pool_def()
void scmdio::pool_def (CLI::App & app, boost::asio::io_context & context, std::unique_ptr< cobs_port > & port_ptr)
References pool_cmd().
powerless_flag()
CLI::Option * scmdio::powerless_flag (CLI::App & app, bool & is_powerless)
read()
boost::asio::awaitable< servio::ServioToHost > scmdio::read (cobs_port & port)
Reads a reply from servo over port.
References scmdio::cobs_port::async_read().
set_config_field()
boost::asio::awaitable< void > scmdio::set_config_field (cobs_port & port, const servio::Config & cfg)
Sets config field defined by cfg to serv over port.
References exchange().
set_mode()
boost::asio::awaitable< void > scmdio::set_mode (cobs_port & port, servio::Mode mode)
References exchange().
set_mode_current()
boost::asio::awaitable< void > scmdio::set_mode_current (cobs_port & port, float curr)
References set_mode().
set_mode_disengaged()
boost::asio::awaitable< void > scmdio::set_mode_disengaged (cobs_port & port)
References set_mode().
set_mode_position()
boost::asio::awaitable< void > scmdio::set_mode_position (cobs_port & port, float angle)
References kalman::angle(), and set_mode().
set_mode_velocity()
boost::asio::awaitable< void > scmdio::set_mode_velocity (cobs_port & port, float vel)
References set_mode().
verbose_opt()
CLI::Option * scmdio::verbose_opt (CLI::App & app, bool & val)
write()
boost::asio::awaitable< void > scmdio::write (cobs_port & port, const servio::HostToServio & payload)
Writes a reply to servo port.
References scmdio::cobs_port::async_write().