servio: servio::plt Namespace Reference
servio::plt Namespace Reference
Classes
struct dma_cfg
struct adc_cfg
struct uart_cfg
struct hb_timer_cfg
struct leds_gpio_cfg
struct leds_timer_cfg
struct temp_calib_coeffs
Functions
void cfg_erase (uint32_t start_addr)
bool cfg_write (uint32_t addr, std::span< std::byte > val)
void setup_adc_channel (ADC_ChannelConfTypeDef &channel, drv::pinch_cfg cfg)
em::result setup_adc (ADC_HandleTypeDef &adc, DMA_HandleTypeDef &dma, adc_cfg cfg)
em::result setup_clk ()
cfg::off_scale calculate_temp_conversion ()
consteval cfg::map generate_config ()
cfg::map get_default_config ()
em::result setup_dac (DAC_HandleTypeDef &dac, const drv::pin_cfg &pcfg)
em::result setup_gpio (const drv::pin_cfg &cfg)
em::result setup_adc_timer (TIM_HandleTypeDef &tim, TIM_TypeDef *instance)
em::result setup_uart (UART_HandleTypeDef &uart, DMA_HandleTypeDef &tx_dma, uart_cfg cfg)
em::result setup_hbridge_timers (TIM_HandleTypeDef &tim, hb_timer_cfg cfg)
em::result setup_leds_channel (TIM_HandleTypeDef *tim, drv::pinch_cfg cfg)
em::result setup_clock_timer (TIM_HandleTypeDef &tim, TIM_TypeDef *instance, IRQn_Type irq)
Variables
temp_calib_coeffs TEMP_CALIB_COEFFS
Class Documentation
servio::plt::dma_cfg
struct servio::plt::dma_cfg
Class Members
DMA_Channel_TypeDef * instance
IRQn_Type irq
uint32_t irq_priority
uint32_t priority
uint32_t request
servio::plt::adc_cfg
struct servio::plt::adc_cfg
Class Members
ADC_TypeDef * adc_instance
uint32_t adc_irq_priority
uint32_t adc_trigger
dma_cfg dma
servio::plt::uart_cfg
struct servio::plt::uart_cfg
Class Members
uint32_t baudrate
IRQn_Type irq
uint32_t irq_priority
pin_cfg rx
pin_cfg tx
dma_cfg tx_dma
USART_TypeDef * uart_instance
servio::plt::hb_timer_cfg
struct servio::plt::hb_timer_cfg
Class Members
IRQn_Type irq
uint32_t irq_priority
pinch_cfg mc1
pinch_cfg mc2
uint16_t period
TIM_TypeDef * timer_instance
servio::plt::leds_gpio_cfg
struct servio::plt::leds_gpio_cfg
Class Members
pin_cfg blue
pin_cfg red
servio::plt::leds_timer_cfg
struct servio::plt::leds_timer_cfg
Class Members
pinch_cfg green
TIM_TypeDef * timer_instance
pinch_cfg yellow
servio::plt::temp_calib_coeffs
struct servio::plt::temp_calib_coeffs
Class Members
float cal1
float cal2
Function Documentation
calculate_temp_conversion()
cfg::off_scale servio::plt::calculate_temp_conversion ()
References servio::plt::temp_calib_coeffs::cal1, servio::plt::temp_calib_coeffs::cal2, and TEMP_CALIB_COEFFS.
cfg_erase()
void servio::plt::cfg_erase (uint32_t start_addr)
References servio::fw::stop_exec().
cfg_write()
bool servio::plt::cfg_write (uint32_t addr, std::span< std::byte > val)
References servio::fw::stop_exec().
generate_config()
consteval cfg::map servio::plt::generate_config ()
References servio::cfg::calculate_current_conversion(), servio::cfg::CURRENT_CONV_OFFSET, servio::cfg::CURRENT_CONV_SCALE, servio::cfg::get_default_config(), servio::cfg::off_scale::offset, and servio::cfg::off_scale::scale.
get_default_config()
cfg::map servio::plt::get_default_config ()
References calculate_temp_conversion(), generate_config(), servio::cfg::off_scale::offset, servio::cfg::off_scale::scale, servio::cfg::TEMP_CONV_OFFSET, and servio::cfg::TEMP_CONV_SCALE.
setup_adc()
em::result servio::plt::setup_adc (ADC_HandleTypeDef & adc, DMA_HandleTypeDef & dma, adc_cfg cfg)
References servio::plt::adc_cfg::adc_instance, servio::plt::adc_cfg::adc_irq_priority, servio::plt::adc_cfg::dma, servio::plt::dma_cfg::instance, servio::plt::dma_cfg::irq, servio::plt::dma_cfg::irq_priority, servio::plt::dma_cfg::priority, and servio::plt::dma_cfg::request.
setup_adc_channel()
void servio::plt::setup_adc_channel (ADC_ChannelConfTypeDef & channel, drv::pinch_cfg cfg)
References servio::drv::pinch_cfg::channel, servio::drv::pinch_cfg::pin, and servio::drv::pinch_cfg::port.
setup_adc_timer()
em::result servio::plt::setup_adc_timer (TIM_HandleTypeDef & tim, TIM_TypeDef * instance)
References servio::fw::stop_exec().
setup_clk()
em::result servio::plt::setup_clk ()
Initializes the peripherals clocks
References servio::plt::temp_calib_coeffs::cal1, servio::plt::temp_calib_coeffs::cal2, servio::fw::stop_exec(), and TEMP_CALIB_COEFFS.
setup_clock_timer()
em::result servio::plt::setup_clock_timer (TIM_HandleTypeDef & tim, TIM_TypeDef * instance, IRQn_Type irq)
setup_dac()
em::result servio::plt::setup_dac (DAC_HandleTypeDef & dac, const drv::pin_cfg & pcfg)
References servio::drv::pin_cfg::alternate, servio::drv::pin_cfg::pin, and servio::drv::pin_cfg::port.
setup_gpio()
em::result servio::plt::setup_gpio (const drv::pin_cfg & cfg)
References servio::drv::pin_cfg::alternate, servio::drv::pin_cfg::pin, and servio::drv::pin_cfg::port.
setup_hbridge_timers()
em::result servio::plt::setup_hbridge_timers (TIM_HandleTypeDef & tim, hb_timer_cfg cfg)
References servio::drv::pinch_cfg::channel, servio::plt::hb_timer_cfg::irq, servio::plt::hb_timer_cfg::irq_priority, servio::plt::hb_timer_cfg::mc1, servio::plt::hb_timer_cfg::mc2, servio::plt::hb_timer_cfg::period, servio::fw::stop_exec(), and servio::plt::hb_timer_cfg::timer_instance.
setup_leds_channel()
em::result servio::plt::setup_leds_channel (TIM_HandleTypeDef * tim, drv::pinch_cfg cfg)
References servio::drv::pinch_cfg::alternate, servio::drv::pinch_cfg::channel, servio::drv::pinch_cfg::pin, and servio::drv::pinch_cfg::port.
setup_uart()
em::result servio::plt::setup_uart (UART_HandleTypeDef & uart, DMA_HandleTypeDef & tx_dma, uart_cfg cfg)
References servio::drv::pin_cfg::alternate, servio::plt::uart_cfg::baudrate, servio::plt::dma_cfg::instance, servio::plt::dma_cfg::irq, servio::plt::uart_cfg::irq, servio::plt::dma_cfg::irq_priority, servio::plt::uart_cfg::irq_priority, servio::drv::pin_cfg::pin, servio::drv::pin_cfg::port, servio::plt::dma_cfg::priority, servio::plt::dma_cfg::request, servio::plt::uart_cfg::rx, servio::fw::stop_exec(), servio::plt::uart_cfg::tx, servio::plt::uart_cfg::tx_dma, and servio::plt::uart_cfg::uart_instance.
Variable Documentation
TEMP_CALIB_COEFFS
temp_calib_coeffs servio::plt::TEMP_CALIB_COEFFS