servio: kalman Namespace Reference
kalman Namespace Reference
Classes
struct state_range
Typedefs
using state = em::matrix< 2, 1 >
using state_transition_model = em::matrix< 2, 2 >
using state_covariance = em::matrix< 2, 2 >
using process_noise_covariance = em::matrix< 2, 2 >
using control_input_model = em::matrix< 2, 1 >
using control_input = em::matrix< 1, 1 >
using innovation_covariance = em::matrix< 1, 1 >
using kalman_gain = em::matrix< 2, 1 >
using observation = em::matrix< 1, 1 >
using observation_model = em::matrix< 1, 2 >
using observation_noise_covariance = em::matrix< 1, 1 >
Functions
constexpr state_transition_model get_transition_model (sec_time tdiff)
constexpr control_input_model get_control_input_model (sec_time tdiff)
constexpr process_noise_covariance get_process_noise_covariance (sec_time tdiff, float standard_deviation)
constexpr observation_model get_observation_model ()
constexpr observation_noise_covariance get_observation_noise_covariance (float observation_deviation)
constexpr std::tuple< state, state_covariance > predict (const state &x_prev, const state_covariance &p_prev, const control_input &u, const state_transition_model &f, const control_input_model &b, const process_noise_covariance &q)
constexpr std::tuple< state, state_covariance > update (const state &x_prev, const state_covariance &p_prev, const observation &z, const observation_model &h, const observation_noise_covariance &r)
template<typename T >
auto & angle (T &x)
template<typename T >
auto & velocity (T &x)
constexpr bool requires_offset (const float v, const state_range &r)
float angle_mod (float v, state_range r)
template<typename T >
void modify_angle (T &x, float val, state_range r)
std::vector< state > simulate (sec_time tdiff, float process_deviation, float observation_deviation, const std::vector< observation > &observations, state_range sr)
Class Documentation
kalman::state_range
struct kalman::state_range
Class Members
float offset
float size
Typedef Documentation
control_input
using kalman::control_input = typedef em::matrix< 1, 1 >
control_input_model
using kalman::control_input_model = typedef em::matrix< 2, 1 >
innovation_covariance
using kalman::innovation_covariance = typedef em::matrix< 1, 1 >
kalman_gain
using kalman::kalman_gain = typedef em::matrix< 2, 1 >
observation
using kalman::observation = typedef em::matrix< 1, 1 >
observation_model
using kalman::observation_model = typedef em::matrix< 1, 2 >
observation_noise_covariance
using kalman::observation_noise_covariance = typedef em::matrix< 1, 1 >
process_noise_covariance
using kalman::process_noise_covariance = typedef em::matrix< 2, 2 >
state
using kalman::state = typedef em::matrix< 2, 1 >
state_covariance
using kalman::state_covariance = typedef em::matrix< 2, 2 >
state_transition_model
using kalman::state_transition_model = typedef em::matrix< 2, 2 >
Function Documentation
angle()
template<typename T > auto& kalman::angle (T & x) inline
angle_mod()
float kalman::angle_mod (float v, state_range r) inline
References kalman::state_range::offset, and kalman::state_range::size.
get_control_input_model()
constexpr control_input_model kalman::get_control_input_model (sec_time tdiff) constexpr
get_observation_model()
constexpr observation_model kalman::get_observation_model () constexpr
get_observation_noise_covariance()
constexpr observation_noise_covariance kalman::get_observation_noise_covariance (float observation_deviation) constexpr
get_process_noise_covariance()
constexpr process_noise_covariance kalman::get_process_noise_covariance (sec_time tdiff, float standard_deviation) constexpr
References get_control_input_model().
get_transition_model()
constexpr state_transition_model kalman::get_transition_model (sec_time tdiff) constexpr
modify_angle()
template<typename T > void kalman::modify_angle (T & x, float val, state_range r) inline
References angle(), and angle_mod().
predict()
constexpr std::tuple< state, state_covariance > kalman::predict (const state & x_prev, const state_covariance & p_prev, const control_input & u, const state_transition_model & f, const control_input_model & b, const process_noise_covariance & q) constexpr
requires_offset()
constexpr bool kalman::requires_offset (const float v, const state_range & r) constexpr
References kalman::state_range::offset, and kalman::state_range::size.
simulate()
std::vector< state > kalman::simulate (sec_time tdiff, float process_deviation, float observation_deviation, const std::vector< observation > & observations, state_range sr) inline
References angle(), angle_mod(), get_control_input_model(), get_observation_model(), get_observation_noise_covariance(), get_process_noise_covariance(), get_transition_model(), modify_angle(), pi, predict(), requires_offset(), update(), and velocity().
update()
constexpr std::tuple< state, state_covariance > kalman::update (const state & x_prev, const state_covariance & p_prev, const observation & z, const observation_model & h, const observation_noise_covariance & r) constexpr
velocity()
template<typename T > auto& kalman::velocity (T & x) inline