servio: cnv Namespace Reference
cnv Namespace Reference
Classes
class current_converter
class position_converter
class temperature_converter
class voltage_converter
Functions
float current (const converter &conv, uint32_t raw_current, const pwm_motor_interface &motor)
float current (const converter &conv, const current_interface &curr_drv, const pwm_motor_interface &motor)
float position (const converter &conv, const position_interface &pos_drv)
Function Documentation
current() [1/2]
float cnv::current (const converter & conv, const current_interface & curr_drv, const pwm_motor_interface & motor) inline
References current(), and current_interface::get_current().
current() [2/2]
float cnv::current (const converter & conv, uint32_t raw_current, const pwm_motor_interface & motor) inline
References cnv::current_converter::convert(), converter::current, and pwm_motor_interface::get_direction().
position()
float cnv::position (const converter & conv, const position_interface & pos_drv) inline
References cnv::position_converter::convert(), position_interface::get_position(), and converter::position.