servio: cfg Namespace Reference
cfg Namespace Reference
Classes
struct dispatcher
struct keyval
struct off_scale
struct payload
Typedefs
template<auto Key, typename T >
using reg = em::protocol::register_pair< Key, T >
using model_name = em::string_buffer< 32 >
using map = em::protocol::register_map< std::endian::little, reg< MODEL, model_name >, reg< ID, uint32_t >, reg< GROUP_ID, uint32_t >, reg< POSITION_CONV_LOW_VALUE, uint32_t >, reg< POSITION_CONV_LOW_ANGLE, float >, reg< POSITION_CONV_HIGH_VALUE, uint32_t >, reg< POSITION_CONV_HIGH_ANGLE, float >, reg< CURRENT_CONV_SCALE, float >, reg< CURRENT_CONV_OFFSET, float >, reg< TEMP_CONV_SCALE, float >, reg< TEMP_CONV_OFFSET, float >, reg< VOLTAGE_CONV_SCALE, float >, reg< CURRENT_LOOP_P, float >, reg< CURRENT_LOOP_I, float >, reg< CURRENT_LOOP_D, float >, reg< CURRENT_LIM_MIN, float >, reg< CURRENT_LIM_MAX, float >, reg< VELOCITY_LOOP_P, float >, reg< VELOCITY_LOOP_I, float >, reg< VELOCITY_LOOP_D, float >, reg< VELOCITY_LIM_MIN, float >, reg< VELOCITY_LIM_MAX, float >, reg< VELOCITY_TO_CURR_LIM_SCALE, float >, reg< POSITION_LOOP_P, float >, reg< POSITION_LOOP_I, float >, reg< POSITION_LOOP_D, float >, reg< POSITION_LIM_MIN, float >, reg< POSITION_LIM_MAX, float >, reg< POSITION_TO_VEL_LIM_SCALE, float >, reg< STATIC_FRICTION_SCALE, float >, reg< STATIC_FRICTION_DECAY, float >, reg< MINIMUM_VOLTAGE, float >, reg< MAXIMUM_TEMPERATURE, float >, reg< MOVING_DETECTION_STEP, float > >
using value_message = typename map::message_type
using value_variant = std::variant< model_name, uint32_t, float >
using handler = em::cfg::handler< payload, keyval, std::endian::native >
using reghandler = em::protocol::register_handler< map >
using page = em::view< std::byte * >
Enumerations
enum key : uint32_t {
MODEL = 1 ,
ID = 2 ,
GROUP_ID = 3 ,
POSITION_CONV_LOW_VALUE = 10 ,
POSITION_CONV_LOW_ANGLE = 11 ,
POSITION_CONV_HIGH_VALUE = 12 ,
POSITION_CONV_HIGH_ANGLE = 13 ,
CURRENT_CONV_SCALE = 14 ,
CURRENT_CONV_OFFSET = 15 ,
TEMP_CONV_SCALE = 16 ,
TEMP_CONV_OFFSET = 17 ,
VOLTAGE_CONV_SCALE = 18 ,
CURRENT_LOOP_P = 30 ,
CURRENT_LOOP_I = 31 ,
CURRENT_LOOP_D = 32 ,
CURRENT_LIM_MIN = 33 ,
CURRENT_LIM_MAX = 34 ,
VELOCITY_LOOP_P = 40 ,
VELOCITY_LOOP_I = 41 ,
VELOCITY_LOOP_D = 42 ,
VELOCITY_LIM_MIN = 43 ,
VELOCITY_LIM_MAX = 44 ,
VELOCITY_TO_CURR_LIM_SCALE = 45 ,
POSITION_LOOP_P = 50 ,
POSITION_LOOP_I = 51 ,
POSITION_LOOP_D = 52 ,
POSITION_LIM_MIN = 53 ,
POSITION_LIM_MAX = 54 ,
POSITION_TO_VEL_LIM_SCALE = 55 ,
STATIC_FRICTION_SCALE = 60 ,
STATIC_FRICTION_DECAY = 61 ,
MINIMUM_VOLTAGE = 62 ,
MAXIMUM_TEMPERATURE = 65 ,
MOVING_DETECTION_STEP = 66
}
Functions
consteval map get_default_config ()
void apply (control &ctl, const map &m, const key &key)
template<key Key>
keyval make_keyval (auto val)
constexpr off_scale calculate_current_conversion (float v_max, float v_min, float steps, float r_shunt, float gain)
std::optional< page > find_unused_page (em::view< const page * > pages)
std::optional< page > find_oldest_page (em::view< const page * > pages)
std::optional< page > find_next_page (em::view< const page * > pages)
std::optional< page > find_latest_page (em::view< const page * > pages)
bool store (const payload &pl, const map *m, em::function_view< bool(std::size_t, uint64_t) > writer)
bool load (page p, em::function_view< bool(const payload &) > pl_cb, map &m)
Class Documentation
cfg::keyval
struct cfg::keyval
Class Members
key key
value_message msg
cfg::off_scale
struct cfg::off_scale
Class Members
float offset
float scale
Typedef Documentation
handler
using cfg::handler = typedef em::cfg::handler< payload, keyval, std::endian::native >
map
using cfg::map = typedef em::protocol::register_map< std::endian::little, reg< MODEL, model_name >, reg< ID, uint32_t >, reg< GROUP_ID, uint32_t >, reg< POSITION_CONV_LOW_VALUE, uint32_t >, reg< POSITION_CONV_LOW_ANGLE, float >, reg< POSITION_CONV_HIGH_VALUE, uint32_t >, reg< POSITION_CONV_HIGH_ANGLE, float >, reg< CURRENT_CONV_SCALE, float >, reg< CURRENT_CONV_OFFSET, float >, reg< TEMP_CONV_SCALE, float >, reg< TEMP_CONV_OFFSET, float >, reg< VOLTAGE_CONV_SCALE, float >, reg< CURRENT_LOOP_P, float >, reg< CURRENT_LOOP_I, float >, reg< CURRENT_LOOP_D, float >, reg< CURRENT_LIM_MIN, float >, reg< CURRENT_LIM_MAX, float >, reg< VELOCITY_LOOP_P, float >, reg< VELOCITY_LOOP_I, float >, reg< VELOCITY_LOOP_D, float >, reg< VELOCITY_LIM_MIN, float >, reg< VELOCITY_LIM_MAX, float >, reg< VELOCITY_TO_CURR_LIM_SCALE, float >, reg< POSITION_LOOP_P, float >, reg< POSITION_LOOP_I, float >, reg< POSITION_LOOP_D, float >, reg< POSITION_LIM_MIN, float >, reg< POSITION_LIM_MAX, float >, reg< POSITION_TO_VEL_LIM_SCALE, float >, reg< STATIC_FRICTION_SCALE, float >, reg< STATIC_FRICTION_DECAY, float >, reg< MINIMUM_VOLTAGE, float >, reg< MAXIMUM_TEMPERATURE, float >, reg< MOVING_DETECTION_STEP, float > >
model_name
using cfg::model_name = typedef em::string_buffer< 32 >
page
using cfg::page = typedef em::view< std::byte* >
reg
template<auto Key, typename T > using cfg::reg = typedef em::protocol::register_pair< Key, T >
reghandler
using cfg::reghandler = typedef em::protocol::register_handler< map >
value_message
using cfg::value_message = typedef typename map::message_type
value_variant
using cfg::value_variant = typedef std::variant< model_name, uint32_t, float >
Enumeration Type Documentation
key
enum cfg::key : uint32_t
Enumerator
MODEL
ID
GROUP_ID
POSITION_CONV_LOW_VALUE
POSITION_CONV_LOW_ANGLE
POSITION_CONV_HIGH_VALUE
POSITION_CONV_HIGH_ANGLE
CURRENT_CONV_SCALE
CURRENT_CONV_OFFSET
TEMP_CONV_SCALE
TEMP_CONV_OFFSET
VOLTAGE_CONV_SCALE
CURRENT_LOOP_P
CURRENT_LOOP_I
CURRENT_LOOP_D
CURRENT_LIM_MIN
CURRENT_LIM_MAX
VELOCITY_LOOP_P
VELOCITY_LOOP_I
VELOCITY_LOOP_D
VELOCITY_LIM_MIN
VELOCITY_LIM_MAX
VELOCITY_TO_CURR_LIM_SCALE
POSITION_LOOP_P
POSITION_LOOP_I
POSITION_LOOP_D
POSITION_LIM_MIN
POSITION_LIM_MAX
POSITION_TO_VEL_LIM_SCALE
STATIC_FRICTION_SCALE
STATIC_FRICTION_DECAY
MINIMUM_VOLTAGE
MAXIMUM_TEMPERATURE
MOVING_DETECTION_STEP
Function Documentation
apply()
void cfg::apply (control & ctl, const map & m, const key & key)
References CURRENT, CURRENT_LIM_MAX, CURRENT_LIM_MIN, CURRENT_LOOP_D, CURRENT_LOOP_I, CURRENT_LOOP_P, POSITION, POSITION_LIM_MAX, POSITION_LIM_MIN, POSITION_LOOP_D, POSITION_LOOP_I, POSITION_LOOP_P, POSITION_TO_VEL_LIM_SCALE, STATIC_FRICTION_DECAY, STATIC_FRICTION_SCALE, VELOCITY, VELOCITY_LIM_MAX, VELOCITY_LIM_MIN, VELOCITY_LOOP_D, VELOCITY_LOOP_I, VELOCITY_LOOP_P, and VELOCITY_TO_CURR_LIM_SCALE.
calculate_current_conversion()
constexpr off_scale cfg::calculate_current_conversion (float v_max, float v_min, float steps, float r_shunt, float gain) constexpr
References cfg::off_scale::offset.
find_latest_page()
std::optional< page > cfg::find_latest_page (em::view< const page * > pages)
find_next_page()
std::optional< page > cfg::find_next_page (em::view< const page * > pages)
References find_oldest_page(), and find_unused_page().
find_oldest_page()
std::optional< page > cfg::find_oldest_page (em::view< const page * > pages)
find_unused_page()
std::optional< page > cfg::find_unused_page (em::view< const page * > pages)
References load().
get_default_config()
consteval map cfg::get_default_config ()
References pi.
load()
bool cfg::load (page p, em::function_view< bool(const payload &) > pl_cb, map & m)
References cfg::keyval::key, and cfg::keyval::msg.
make_keyval()
template<key Key> keyval cfg::make_keyval (auto val)
References cfg::keyval::key.
store()
bool cfg::store (const payload & pl, const map * m, em::function_view< bool(std::size_t, uint64_t) > writer)
References cfg::keyval::key.