servio: servio Namespace Reference
servio Namespace Reference
Namespaces
brd
cfg
cnv
ctl
fw
klmn
literals
mtr
plt
scmdio
sim
Classes
struct leds_vals
class current_callback
class position_callback
struct converter
struct core
struct core_drivers
class adc_detailed_cb_interface
class value_cb_interface
class period_cb_interface
class driver_interface
struct com_res
class com_interface
class leds_interface
class clk_interface
class period_interface
class pwm_motor_interface
class position_interface
class vcc_interface
class temperature_interface
class current_interface
class indication
class metrics
class monitor
class scaled
struct standard_callbacks
struct static_detector
Typedefs
using microseconds = std::chrono::duration< uint32_t, std::micro >
using milliseconds = std::chrono::duration< uint32_t, std::milli >
using seconds = std::chrono::duration< uint32_t >
using sec_time = std::chrono::duration< float >
template<typename T >
using limits = em::min_max< T >
using current_cb_interface = adc_detailed_cb_interface
using position_cb_interface = value_cb_interface
using page = em::view< std::byte * >
Enumerations
enum class control_mode {
DISENGAGED ,
POWER ,
CURRENT ,
VELOCITY ,
POSITION
}
enum class control_loop {
CURRENT ,
VELOCITY ,
POSITION
}
enum class indication_event {
VOLTAGE_LOW ,
TEMPERATURE_HIGH ,
HEARTBEAT ,
ENGAGED ,
DISENGAGED ,
STUCK ,
BOOTING ,
INITIALIZED ,
INCOMING_MESSAGE
}
enum class status {
NOMINAL ,
DEGRADED ,
INOPERABLE
}
Functions
float sin_approx (float x)
cfg::payload load_persistent_config (em::view< const page * > pages, cfg::map &cfg)
Variables
static constexpr float infty = std::numeric_limits< float >::infinity()
static constexpr float pi = std::numbers::pi_v< float >
em::static_function< void(), 16 > STOP_CALLBACK
Class Documentation
servio::leds_vals
struct servio::leds_vals
Class Members
bool blue
uint8_t green
bool red
uint8_t yellow
servio::com_res
struct servio::com_res
Class Members
bool success
view< byte * > used_data
Typedef Documentation
current_cb_interface
using servio::current_cb_interface = typedef adc_detailed_cb_interface
limits
template<typename T > using servio::limits = typedef em::min_max< T >
microseconds
using servio::microseconds = typedef std::chrono::duration< uint32_t, std::micro >
milliseconds
using servio::milliseconds = typedef std::chrono::duration< uint32_t, std::milli >
page
using servio::page = typedef em::view< std::byte* >
position_cb_interface
using servio::position_cb_interface = typedef value_cb_interface
sec_time
using servio::sec_time = typedef std::chrono::duration< float >
seconds
using servio::seconds = typedef std::chrono::duration< uint32_t >
Enumeration Type Documentation
control_loop
enum servio::control_loop strong
Enumerator
CURRENT
VELOCITY
POSITION
control_mode
enum servio::control_mode strong
Enumerator
DISENGAGED
POWER
CURRENT
VELOCITY
POSITION
indication_event
enum servio::indication_event strong
Enumerator
VOLTAGE_LOW
TEMPERATURE_HIGH
HEARTBEAT
ENGAGED
DISENGAGED
STUCK
BOOTING
INITIALIZED
INCOMING_MESSAGE
status
enum servio::status strong
Enumerator
NOMINAL
DEGRADED
INOPERABLE
Function Documentation
load_persistent_config()
cfg::payload servio::load_persistent_config (em::view< const page * > pages, cfg::map & cfg) inline
References servio::cfg::find_latest_page(), servio::cfg::payload::git_ver, servio::cfg::load(), and servio::fw::stop_exec().
sin_approx()
float servio::sin_approx (float x)
Variable Documentation
infty
constexpr float servio::infty = std::numeric_limits< float >::infinity() static constexpr
pi
constexpr float servio::pi = std::numbers::pi_v< float > static constexpr
STOP_CALLBACK
em::static_function< void(), 16 > servio::STOP_CALLBACK