servio: servio::ftest Namespace Reference
servio::ftest Namespace Reference
Namespaces
namespace bench
namespace intg
Classes
struct testing_system
struct uctx
struct utest
struct utest_base
Functions
void setup_tests (em::pmr::memory_resource &mem, t::reactor &reac, uctx &ctx, t::parameters &, core::drivers &cdrv, core::core &cor, status &res)
auto is_powerless (em::testing::parameters &params)
void rewind (core::core &cor, drv::clk_iface &iclk, drv::pos_iface &ipos, microseconds timeout, em::min_max< float > area, float current)
void setup_tests (em::pmr::memory_resource &mem, em::testing::reactor &reac, uctx &ctx, em::testing::parameters &params, core::drivers &cdrv, core::core &core, status &res)
t::coroutine< void > store_metric (em::pmr::memory_resource &, uctx &ctx, std::string_view name, auto &&value, std::string_view unit="")
t::coroutine< void > store_data (em::pmr::memory_resource &, uctx &ctx, std::string_view key, auto &&data)
auto setup_poweroff (ctl::control &ctl)
template<typename T , typename... Args>
void setup_utest (em::pmr::memory_resource &mem, t::reactor &r, uctx &ctx, status &res, Args &&... args)
Function Documentation
is_powerless()
auto servio::ftest::is_powerless (em::testing::parameters & params) inline
rewind()
void servio::ftest::rewind (core::core & cor, drv::clk_iface & iclk, drv::pos_iface & ipos, microseconds timeout, em::min_max< float > area, float current)
References servio::core::core::conv, servio::cnv::linear_converter::convert(), servio::core::core::ctl, servio::drv::get_pos_iface::get_position(), servio::drv::clk_iface::get_us(), servio::cnv::converter::position, servio::ctl::control::switch_to_current_control(), and servio::ctl::control::switch_to_power_control().
setup_poweroff()
auto servio::ftest::setup_poweroff (ctl::control & ctl) inline
References servio::ctl::control::switch_to_power_control().
setup_tests() [1/2]
void servio::ftest::setup_tests (em::pmr::memory_resource & mem, em::testing::reactor & reac, uctx & ctx, em::testing::parameters & params, core::drivers & cdrv, core::core & core, status & res)
setup_tests() [2/2]
void servio::ftest::setup_tests (em::pmr::memory_resource & mem, t::reactor & reac, uctx & ctx, t::parameters & params, core::drivers & cdrv, core::core & cor, status & res)
References servio::core::drivers::clock, servio::core::drivers::current, servio::core::drivers::period, servio::core::drivers::position, and servio::ftest::bench::setup_bench_tests().
setup_utest()
template<typename T , typename... Args> void servio::ftest::setup_utest (em::pmr::memory_resource & mem, t::reactor & r, uctx & ctx, status & res, Args &&... args)
References servio::SUCCESS.
store_data()
t::coroutine< void > servio::ftest::store_data (em::pmr::memory_resource & , uctx & ctx, std::string_view key, auto && data)
References servio::ftest::uctx::coll.
store_metric()
t::coroutine< void > servio::ftest::store_metric (em::pmr::memory_resource & , uctx & ctx, std::string_view name, auto && value, std::string_view unit = "")
References servio::ftest::uctx::coll, and servio::ftest::uctx::met_id.