servio: servio::bb Namespace Reference
servio::bb Namespace Reference
Classes
struct bb_test_case
Typedefs
using test_signature = boost::asio::awaitable< void >(boost::asio::io_context &, scmdio::port_iface &)
Functions
void register_test (std::string const &fixture_name, std::string const &name, boost::asio::io_context &io_ctx, std::shared_ptr< scmdio::port_iface > port, std::function< test_signature > test, std::chrono::milliseconds timeout)
void vary_value (vari::vref< iface::cfg_types > x)
::testing::AssertionResult cmp_cfg_state (opt< std::size_t > tested_i, std::vector< vari::vval< iface::cfg_vals > > const &initial, std::vector< vari::vval< iface::cfg_vals > > const &new_state)
boost::asio::awaitable< void > test_config (boost::asio::io_context &, scmdio::port_iface &port)
boost::asio::awaitable< void > check_mode (scmdio::port_iface &port, auto v)
boost::asio::awaitable< void > disengage (boost::asio::io_context &, scmdio::port_iface &port)
boost::asio::awaitable< void > test_disengaged (boost::asio::io_context &, scmdio::port_iface &port)
boost::asio::awaitable< void > test_power (boost::asio::io_context &io, scmdio::port_iface &port)
boost::asio::awaitable< void > test_current (boost::asio::io_context &io, scmdio::port_iface &port)
boost::asio::awaitable< void > test_velocity (boost::asio::io_context &io, scmdio::port_iface &port)
boost::asio::awaitable< void > test_position (boost::asio::io_context &io, scmdio::port_iface &port)
boost::asio::awaitable< void > test_properties_querying (boost::asio::io_context &, scmdio::port_iface &port)
Typedef Documentation
test_signature
using servio::bb::test_signature = typedef boost::asio::awaitable< void >(boost::asio::io_context&, scmdio::port_iface&)
Function Documentation
check_mode()
boost::asio::awaitable< void > servio::bb::check_mode (scmdio::port_iface & port, auto v)
References servio::scmdio::get_property_mode(), and servio::scmdio::set_mode().
cmp_cfg_state()
::testing::AssertionResult servio::bb::cmp_cfg_state (opt< std::size_t > tested_i, std::vector< vari::vval< iface::cfg_vals > > const & initial, std::vector< vari::vval< iface::cfg_vals > > const & new_state)
disengage()
boost::asio::awaitable< void > servio::bb::disengage (boost::asio::io_context & , scmdio::port_iface & port)
References servio::scmdio::set_mode().
register_test()
void servio::bb::register_test (std::string const & fixture_name, std::string const & name, boost::asio::io_context & io_ctx, std::shared_ptr< scmdio::port_iface > port, std::function< test_signature > test, std::chrono::milliseconds timeout) inline
test_config()
boost::asio::awaitable< void > servio::bb::test_config (boost::asio::io_context & , scmdio::port_iface & port)
References cmp_cfg_state(), servio::scmdio::get_full_config(), servio::scmdio::set_config_field(), and vary_value().
test_current()
boost::asio::awaitable< void > servio::bb::test_current (boost::asio::io_context & io, scmdio::port_iface & port)
References check_mode(), and disengage().
test_disengaged()
boost::asio::awaitable< void > servio::bb::test_disengaged (boost::asio::io_context & , scmdio::port_iface & port)
References check_mode().
test_position()
boost::asio::awaitable< void > servio::bb::test_position (boost::asio::io_context & io, scmdio::port_iface & port)
References check_mode(), and disengage().
test_power()
boost::asio::awaitable< void > servio::bb::test_power (boost::asio::io_context & io, scmdio::port_iface & port)
References check_mode(), and disengage().
test_properties_querying()
boost::asio::awaitable< void > servio::bb::test_properties_querying (boost::asio::io_context & , scmdio::port_iface & port)
References servio::scmdio::get_property().
test_velocity()
boost::asio::awaitable< void > servio::bb::test_velocity (boost::asio::io_context & io, scmdio::port_iface & port)
References check_mode(), and disengage().
vary_value()
void servio::bb::vary_value (vari::vref< iface::cfg_types > x)