servio: servio::klmn Namespace Reference
servio::klmn Namespace Reference
Namespaces
tests
Classes
struct state_range
Typedefs
using state = em::matrix< 2, 1 >
using state_transition_model = em::matrix< 2, 2 >
using state_covariance = em::matrix< 2, 2 >
using process_noise_covariance = em::matrix< 2, 2 >
using control_input_model = em::matrix< 2, 1 >
using control_input = em::matrix< 1, 1 >
using innovation_covariance = em::matrix< 1, 1 >
using kalman_gain = em::matrix< 2, 1 >
using observation = em::matrix< 1, 1 >
using observation_model = em::matrix< 1, 2 >
using observation_noise_covariance = em::matrix< 1, 1 >
Functions
constexpr state_transition_model get_transition_model (base::sec_time tdiff)
constexpr control_input_model get_control_input_model (base::sec_time tdiff)
constexpr process_noise_covariance get_process_noise_covariance (base::sec_time tdiff, float standard_deviation)
constexpr observation_model get_observation_model ()
constexpr observation_noise_covariance get_observation_noise_covariance (float observation_deviation)
constexpr std::tuple< state, state_covariance > predict (const state &x_prev, const state_covariance &p_prev, const control_input &u, const state_transition_model &f, const control_input_model &b, const process_noise_covariance &q)
constexpr std::tuple< state, state_covariance > update (const state &x_prev, const state_covariance &p_prev, const observation &z, const observation_model &h, const observation_noise_covariance &r)
template<typename T >
auto & angle (T &x)
template<typename T >
auto & velocity (T &x)
constexpr bool requires_offset (const float v, const state_range &r)
float angle_mod (float v, state_range r)
template<typename T >
void modify_angle (T &x, float val, state_range r)
std::vector< state > simulate (base::sec_time tdiff, float process_deviation, float observation_deviation, const std::vector< observation > &observations, state_range sr)
Class Documentation
servio::klmn::state_range
struct servio::klmn::state_range
Class Members
float offset
float size
Typedef Documentation
control_input
using servio::klmn::control_input = typedef em::matrix< 1, 1 >
control_input_model
using servio::klmn::control_input_model = typedef em::matrix< 2, 1 >
innovation_covariance
using servio::klmn::innovation_covariance = typedef em::matrix< 1, 1 >
kalman_gain
using servio::klmn::kalman_gain = typedef em::matrix< 2, 1 >
observation
using servio::klmn::observation = typedef em::matrix< 1, 1 >
observation_model
using servio::klmn::observation_model = typedef em::matrix< 1, 2 >
observation_noise_covariance
using servio::klmn::observation_noise_covariance = typedef em::matrix< 1, 1 >
process_noise_covariance
using servio::klmn::process_noise_covariance = typedef em::matrix< 2, 2 >
state
using servio::klmn::state = typedef em::matrix< 2, 1 >
state_covariance
using servio::klmn::state_covariance = typedef em::matrix< 2, 2 >
state_transition_model
using servio::klmn::state_transition_model = typedef em::matrix< 2, 2 >
Function Documentation
angle()
template<typename T > auto& servio::klmn::angle (T & x) inline
angle_mod()
float servio::klmn::angle_mod (float v, state_range r) inline
References servio::klmn::state_range::offset, and servio::klmn::state_range::size.
get_control_input_model()
constexpr control_input_model servio::klmn::get_control_input_model (base::sec_time tdiff) constexpr
get_observation_model()
constexpr observation_model servio::klmn::get_observation_model () constexpr
get_observation_noise_covariance()
constexpr observation_noise_covariance servio::klmn::get_observation_noise_covariance (float observation_deviation) constexpr
get_process_noise_covariance()
constexpr process_noise_covariance servio::klmn::get_process_noise_covariance (base::sec_time tdiff, float standard_deviation) constexpr
References get_control_input_model().
get_transition_model()
constexpr state_transition_model servio::klmn::get_transition_model (base::sec_time tdiff) constexpr
modify_angle()
template<typename T > void servio::klmn::modify_angle (T & x, float val, state_range r) inline
References angle(), and angle_mod().
predict()
constexpr std::tuple< state, state_covariance > servio::klmn::predict (const state & x_prev, const state_covariance & p_prev, const control_input & u, const state_transition_model & f, const control_input_model & b, const process_noise_covariance & q) constexpr
requires_offset()
constexpr bool servio::klmn::requires_offset (const float v, const state_range & r) constexpr
References servio::klmn::state_range::offset, and servio::klmn::state_range::size.
simulate()
std::vector< state > servio::klmn::simulate (base::sec_time tdiff, float process_deviation, float observation_deviation, const std::vector< observation > & observations, state_range sr)
References angle(), angle_mod(), get_control_input_model(), get_observation_model(), get_observation_noise_covariance(), get_process_noise_covariance(), get_transition_model(), modify_angle(), servio::base::pi, predict(), requires_offset(), update(), and velocity().
update()
constexpr std::tuple< state, state_covariance > servio::klmn::update (const state & x_prev, const state_covariance & p_prev, const observation & z, const observation_model & h, const observation_noise_covariance & r) constexpr
velocity()
template<typename T > auto& servio::klmn::velocity (T & x) inline