servio: host Namespace Reference
host Namespace Reference
Classes
struct common_cli
struct servio_exception
struct reply_error
struct error_exception
struct serialize_error
struct parse_error
Functions
template<typename Port >
boost::asio::awaitable< void > async_cobs_write (Port &port, em::view< std::byte * > msg)
template<typename Port >
boost::asio::awaitable< em::view< std::byte * > > async_cobs_read (Port &port, em::view< std::byte * > buffer)
boost::asio::awaitable< void > cfg_query_cmd (boost::asio::serial_port &port, bool json)
boost::asio::awaitable< void > cfg_commit_cmd (boost::asio::serial_port &port)
boost::asio::awaitable< void > cfg_clear_cmd (boost::asio::serial_port &port)
boost::asio::awaitable< void > cfg_get_cmd (boost::asio::serial_port &port, const std::string &name, bool json)
boost::asio::awaitable< void > cfg_set_cmd (boost::asio::serial_port &port, const std::string &name, std::string value)
boost::asio::awaitable< void > write (boost::asio::serial_port &port, const servio::HostToServio &payget)
Writes a reply to servo port.
boost::asio::awaitable< servio::ServioToHost > read (boost::asio::serial_port &port)
Reads a reply from servo over port.
boost::asio::awaitable< servio::ServioToHost > exchange (boost::asio::serial_port &port, const servio::HostToServio &msg)
Exchanges messages with the servo over port.
boost::asio::awaitable< servio::Config > get_config_field (boost::asio::serial_port &port, const google::protobuf::FieldDescriptor *field)
Loads a config field specified by field from servo over port.
boost::asio::awaitable< void > set_config_field (boost::asio::serial_port &port, const servio::Config &cfg)
Sets config field defined by cfg to serv over port.
boost::asio::awaitable< std::vector< servio::Config > > get_full_config (boost::asio::serial_port &port)
Loads full config of servo over port.
boost::asio::awaitable< servio::Property > get_property (boost::asio::serial_port &port, uint32_t field_id)
boost::asio::awaitable< servio::Property > get_property (boost::asio::serial_port &port, servio::Property::PldCase field_id)
boost::asio::awaitable< servio::Property > get_property (boost::asio::serial_port &port, const google::protobuf::FieldDescriptor *field)
boost::asio::awaitable< float > get_property_current (boost::asio::serial_port &port)
TODO: error checking for the getters.
boost::asio::awaitable< float > get_property_position (boost::asio::serial_port &port)
boost::asio::awaitable< float > get_property_velocity (boost::asio::serial_port &port)
boost::asio::awaitable< void > set_mode (boost::asio::serial_port &port, servio::Mode mode)
boost::asio::awaitable< void > set_mode_disengaged (boost::asio::serial_port &port)
boost::asio::awaitable< void > set_mode_position (boost::asio::serial_port &port, float angle)
boost::asio::awaitable< void > set_mode_current (boost::asio::serial_port &port, float curr)
Function Documentation
async_cobs_read()
template<typename Port > boost::asio::awaitable< em::view< std::byte* > > host::async_cobs_read (Port & port, em::view< std::byte * > buffer)
async_cobs_write()
template<typename Port > boost::asio::awaitable< void > host::async_cobs_write (Port & port, em::view< std::byte * > msg)
cfg_clear_cmd()
boost::asio::awaitable< void > host::cfg_clear_cmd (boost::asio::serial_port & port)
References exchange().
cfg_commit_cmd()
boost::asio::awaitable< void > host::cfg_commit_cmd (boost::asio::serial_port & port)
References exchange().
cfg_get_cmd()
boost::asio::awaitable< void > host::cfg_get_cmd (boost::asio::serial_port & port, const std::string & name, bool json)
References get_config_field().
cfg_query_cmd()
boost::asio::awaitable< void > host::cfg_query_cmd (boost::asio::serial_port & port, bool json)
References get_full_config().
cfg_set_cmd()
boost::asio::awaitable< void > host::cfg_set_cmd (boost::asio::serial_port & port, const std::string & name, std::string value)
References exchange().
exchange()
boost::asio::awaitable< servio::ServioToHost > host::exchange (boost::asio::serial_port & port, const servio::HostToServio & msg)
Exchanges messages with the servo over port.
References host::error_exception::msg, read(), and write().
get_config_field()
boost::asio::awaitable< servio::Config > host::get_config_field (boost::asio::serial_port & port, const google::protobuf::FieldDescriptor * field)
Loads a config field specified by field from servo over port.
References exchange().
get_full_config()
boost::asio::awaitable< std::vector< servio::Config > > host::get_full_config (boost::asio::serial_port & port)
Loads full config of servo over port.
References get_config_field().
get_property() [1/3]
boost::asio::awaitable< servio::Property > host::get_property (boost::asio::serial_port & port, const google::protobuf::FieldDescriptor * field)
References get_property().
get_property() [2/3]
boost::asio::awaitable< servio::Property > host::get_property (boost::asio::serial_port & port, servio::Property::PldCase field_id)
References get_property().
get_property() [3/3]
boost::asio::awaitable< servio::Property > host::get_property (boost::asio::serial_port & port, uint32_t field_id)
References exchange().
get_property_current()
boost::asio::awaitable< float > host::get_property_current (boost::asio::serial_port & port)
TODO: error checking for the getters.
References get_property().
get_property_position()
boost::asio::awaitable< float > host::get_property_position (boost::asio::serial_port & port)
References get_property().
get_property_velocity()
boost::asio::awaitable< float > host::get_property_velocity (boost::asio::serial_port & port)
References get_property().
read()
boost::asio::awaitable< servio::ServioToHost > host::read (boost::asio::serial_port & port)
Reads a reply from servo over port.
References async_cobs_read().
set_config_field()
boost::asio::awaitable< void > host::set_config_field (boost::asio::serial_port & port, const servio::Config & cfg)
Sets config field defined by cfg to serv over port.
References exchange().
set_mode()
boost::asio::awaitable< void > host::set_mode (boost::asio::serial_port & port, servio::Mode mode)
References exchange().
set_mode_current()
boost::asio::awaitable< void > host::set_mode_current (boost::asio::serial_port & port, float curr)
References set_mode().
set_mode_disengaged()
boost::asio::awaitable< void > host::set_mode_disengaged (boost::asio::serial_port & port)
References set_mode().
set_mode_position()
boost::asio::awaitable< void > host::set_mode_position (boost::asio::serial_port & port, float angle)
References kalman::angle(), and set_mode().
write()
boost::asio::awaitable< void > host::write (boost::asio::serial_port & port, const servio::HostToServio & payload)
Writes a reply to servo port.
References async_cobs_write().