servio: servio::fw Namespace Reference
servio::fw Namespace Reference
Classes
struct cfg_context
struct context
struct dispatcher
struct persistent_config_writer
struct check_bool
Typedefs
using page = em::view< std::byte * >
Functions
cfg_context load_cfg_context ()
context setup_context ()
ServioToHost handle_set_mode (base::microseconds now, ctl::control &ctl, const Mode &msg)
Mode get_mode (const ctl::control &ctl)
ServioToHost handle_get_property (const ctl::control &ctl, const mtr::metrics &met, const cnv::converter &conv, const drv::position_interface &pos_drv, const drv::current_interface &curr_drv, const drv::vcc_interface &vcc_drv, const drv::temperature_interface &temp_drv, const drv::pwm_motor_interface &motor, const GetProperty &msg)
ServioToHost handle_set_config (cfg::dispatcher &cfg_disp, const Config &req)
ServioToHost handle_get_config (const cfg::dispatcher &cfg_disp, const GetConfig &req)
ServioToHost handle_commit_config (const cfg::dispatcher &cfg_disp, const auto &cfg_writer)
ServioToHost handle_clear_config (const auto &cfg_writer)
ServioToHost handle_message (dispatcher &dis, const HostToServio &msg)
template<typename InputType , typename OutputType , typename Handle >
std::tuple< em::outcome, em::view< std::byte * > > process_message (em::view< const std::byte * > input_data, em::view< std::byte * > output_buffer, Handle &&h)
std::tuple< em::outcome, em::view< std::byte * > > handle_message (dispatcher &dis, em::view< const std::byte * > input_data, em::view< std::byte * > output_buffer)
std::tuple< em::outcome, em::view< std::byte * > > handle_message_packet (dispatcher &dis, em::view< const std::byte * > input_data, em::view< std::byte * > output_buffer)
void install_stop_callback (auto &target, drv::pwm_motor_interface &motor, drv::leds_interface *leds_ptr)
cfg::payload load_persistent_config (em::view< const page * > pages, cfg::map &cfg)
template<typename Cfg , typename UnaryFunction >
bool map_cfg (uint32_t key, Cfg &cfg, UnaryFunction &&f)
ServioToHost error_msg (const char *msg)
bool decode (em::view< const std::byte * > data, HostToServio &msg)
decodes a bytes from data to HostToServio message, returns true on success
bool decode (em::view< const std::byte * > data, HostToServioPacket &msg)
std::tuple< em::result, em::view< std::byte * > > encode (em::view< std::byte * > data, const ServioToHost &msg)
encodes a ServioToHost message to bytes, returns succes bool and subset of data that contains the serialized message
std::tuple< em::result, em::view< std::byte * > > encode (em::view< std::byte * > data, const ServioToHostPacket &msg)
bool store_persistent_config (const cfg::page &page, const cfg::payload &pld, const cfg::map *cfg)
void stop_exec ()
template<typename... Components>
void multistart (Components &... comps)
void copy_string_to (const char *str, std::size_t size, auto &target)
void operator<< (const check_bool &, bool val)
Class Documentation
servio::fw::cfg_context
struct servio::fw::cfg_context
Class Members
payload last_payload
map map
view< const page * > pages
servio::fw::dispatcher
struct servio::fw::dispatcher
Class Members
dispatcher & cfg_disp
function_view< bool(const map *cfg) > cfg_writer
converter & conv
control & ctl
const current_interface & curr_drv
metrics & met
pwm_motor_interface & motor
microseconds now
const position_interface & pos_drv
const temperature_interface & temp_drv
const vcc_interface & vcc_drv
servio::fw::check_bool
struct servio::fw::check_bool
Typedef Documentation
page
using servio::fw::page = typedef em::view< std::byte* >
Function Documentation
copy_string_to()
void servio::fw::copy_string_to (const char * str, std::size_t size, auto & target)
decode() [1/2]
bool servio::fw::decode (em::view< const std::byte * > data, HostToServio & msg)
decodes a bytes from data to HostToServio message, returns true on success
decode() [2/2]
bool servio::fw::decode (em::view< const std::byte * > data, HostToServioPacket & msg)
encode() [1/2]
std::tuple< em::result, em::view< std::byte * > > servio::fw::encode (em::view< std::byte * > data, const ServioToHost & msg)
encodes a ServioToHost message to bytes, returns succes bool and subset of data that contains the serialized message
encode() [2/2]
std::tuple< em::result, em::view< std::byte * > > servio::fw::encode (em::view< std::byte * > data, const ServioToHostPacket & msg)
error_msg()
ServioToHost servio::fw::error_msg (const char * msg)
References copy_string_to().
get_mode()
Mode servio::fw::get_mode (const ctl::control & ctl)
References servio::base::CURRENT, servio::base::DISENGAGED, servio::ctl::control::get_desired_current(), servio::ctl::control::get_desired_position(), servio::ctl::control::get_desired_velocity(), servio::ctl::control::get_mode(), servio::ctl::control::get_power(), servio::base::POSITION, servio::base::POWER, and servio::base::VELOCITY.
handle_clear_config()
ServioToHost servio::fw::handle_clear_config (const auto & cfg_writer)
References error_msg().
handle_commit_config()
ServioToHost servio::fw::handle_commit_config (const cfg::dispatcher & cfg_disp, const auto & cfg_writer)
References error_msg(), and servio::cfg::dispatcher::m.
handle_get_config()
ServioToHost servio::fw::handle_get_config (const cfg::dispatcher & cfg_disp, const GetConfig & req)
References map_cfg().
handle_get_property()
ServioToHost servio::fw::handle_get_property (const ctl::control & ctl, const mtr::metrics & met, const cnv::converter & conv, const drv::position_interface & pos_drv, const drv::current_interface & curr_drv, const drv::vcc_interface & vcc_drv, const drv::temperature_interface & temp_drv, const drv::pwm_motor_interface & motor, const GetProperty & msg)
References servio::cnv::linear_converter::convert(), servio::cnv::current(), error_msg(), get_mode(), servio::drv::temperature_interface::get_temperature(), servio::drv::vcc_interface::get_vcc(), servio::mtr::metrics::get_velocity(), servio::cnv::position(), servio::cnv::converter::temp, and servio::cnv::converter::vcc.
handle_message() [1/2]
ServioToHost servio::fw::handle_message (dispatcher & dis, const HostToServio & msg)
References servio::fw::dispatcher::cfg_disp, servio::fw::dispatcher::cfg_writer, servio::fw::dispatcher::conv, servio::fw::dispatcher::ctl, servio::fw::dispatcher::curr_drv, error_msg(), handle_clear_config(), handle_commit_config(), handle_get_config(), handle_get_property(), handle_set_config(), handle_set_mode(), servio::fw::dispatcher::met, servio::fw::dispatcher::motor, servio::fw::dispatcher::now, servio::fw::dispatcher::pos_drv, servio::fw::dispatcher::temp_drv, and servio::fw::dispatcher::vcc_drv.
handle_message() [2/2]
std::tuple< em::outcome, em::view< std::byte * > > servio::fw::handle_message (dispatcher & dis, em::view< const std::byte * > input_data, em::view< std::byte * > output_buffer)
handle_message_packet()
std::tuple< em::outcome, em::view< std::byte * > > servio::fw::handle_message_packet (dispatcher & dis, em::view< const std::byte * > input_data, em::view< std::byte * > output_buffer)
References handle_message().
handle_set_config()
ServioToHost servio::fw::handle_set_config (cfg::dispatcher & cfg_disp, const Config & req)
References error_msg(), and map_cfg().
handle_set_mode()
ServioToHost servio::fw::handle_set_mode (base::microseconds now, ctl::control & ctl, const Mode & msg)
References servio::ctl::control::disengage(), error_msg(), servio::ctl::control::switch_to_current_control(), servio::ctl::control::switch_to_position_control(), servio::ctl::control::switch_to_power_control(), and servio::ctl::control::switch_to_velocity_control().
install_stop_callback()
void servio::fw::install_stop_callback (auto & target, drv::pwm_motor_interface & motor, drv::leds_interface * leds_ptr) inline
References servio::drv::leds_interface::force_red_led(), and servio::drv::pwm_motor_interface::force_stop().
load_cfg_context()
cfg_context servio::fw::load_cfg_context () inline
References servio::brd::get_default_config(), servio::brd::get_persistent_pages(), servio::fw::cfg_context::last_payload, load_persistent_config(), servio::fw::cfg_context::map, and servio::fw::cfg_context::pages.
load_persistent_config()
cfg::payload servio::fw::load_persistent_config (em::view< const page * > pages, cfg::map & cfg) inline
References servio::cfg::find_latest_page(), servio::cfg::payload::git_ver, servio::cfg::load(), and stop_exec().
map_cfg()
template<typename Cfg , typename UnaryFunction > bool servio::fw::map_cfg (uint32_t key, Cfg & cfg, UnaryFunction && f)
References servio::cfg::CURRENT_CONV_OFFSET, servio::cfg::CURRENT_CONV_SCALE, servio::cfg::CURRENT_LIM_MAX, servio::cfg::CURRENT_LIM_MIN, servio::cfg::CURRENT_LOOP_D, servio::cfg::CURRENT_LOOP_I, servio::cfg::CURRENT_LOOP_P, servio::cfg::GROUP_ID, servio::cfg::ID, servio::cfg::MAXIMUM_TEMPERATURE, servio::cfg::MINIMUM_VOLTAGE, servio::cfg::MODEL, servio::cfg::MOVING_DETECTION_STEP, servio::cfg::POSITION_CONV_HIGH_ANGLE, servio::cfg::POSITION_CONV_HIGH_VALUE, servio::cfg::POSITION_CONV_LOW_ANGLE, servio::cfg::POSITION_CONV_LOW_VALUE, servio::cfg::POSITION_LIM_MAX, servio::cfg::POSITION_LIM_MIN, servio::cfg::POSITION_LOOP_D, servio::cfg::POSITION_LOOP_I, servio::cfg::POSITION_LOOP_P, servio::cfg::POSITION_TO_VEL_LIM_SCALE, servio::cfg::STATIC_FRICTION_DECAY, servio::cfg::STATIC_FRICTION_SCALE, servio::cfg::TEMP_CONV_OFFSET, servio::cfg::TEMP_CONV_SCALE, servio::cfg::VELOCITY_LIM_MAX, servio::cfg::VELOCITY_LIM_MIN, servio::cfg::VELOCITY_LOOP_D, servio::cfg::VELOCITY_LOOP_I, servio::cfg::VELOCITY_LOOP_P, servio::cfg::VELOCITY_TO_CURR_LIM_SCALE, and servio::cfg::VOLTAGE_CONV_SCALE.
multistart()
template<typename... Components> void servio::fw::multistart (Components &... comps)
operator<<()
void servio::fw::operator<< (const check_bool & , bool val) inline
References stop_exec().
process_message()
template<typename InputType , typename OutputType , typename Handle > std::tuple< em::outcome, em::view< std::byte* > > servio::fw::process_message (em::view< const std::byte * > input_data, em::view< std::byte * > output_buffer, Handle && h)
References decode(), and encode().
setup_context()
context servio::fw::setup_context ()
References servio::core::drivers::any_uninitialized(), servio::fw::context::cfg, servio::core::drivers::clock, servio::core::drivers::current, servio::drv::clk_interface::get_us(), servio::mon::INITIALIZED, load_cfg_context(), servio::core::drivers::motor, servio::core::drivers::period, servio::core::drivers::period_cb, servio::core::drivers::position, servio::brd::setup_core_drivers(), servio::core::drivers::start_cb, stop_exec(), servio::core::drivers::temperature, and servio::core::drivers::vcc.
stop_exec()
void servio::fw::stop_exec ()
References servio::core::STOP_CALLBACK.
store_persistent_config()
bool servio::fw::store_persistent_config (const cfg::page & page, const cfg::payload & pld, const cfg::map * cfg)
References servio::plt::cfg_erase(), servio::plt::cfg_write(), stop_exec(), and servio::cfg::store().