servio: servio::cnv Namespace Reference
servio::cnv Namespace Reference
Namespaces
namespace tests
Classes
struct converter
struct linear_converter
struct off_scale
Functions
constexpr off_scale calc_current_conversion (float v_max, float v_min, float steps, float r_shunt, float gain)
float current (converter const &conv, uint32_t raw_current, drv::motor_info_iface const &motor)
float current (converter const &conv, drv::get_curr_iface const &curr_drv, drv::motor_info_iface const &motor)
float position (converter const &conv, drv::get_pos_iface const &pos_drv)
Class Documentation
servio::cnv::off_scale
struct servio::cnv::off_scale
Class Members
float offset
float scale
Function Documentation
calc_current_conversion()
constexpr off_scale servio::cnv::calc_current_conversion (float v_max, float v_min, float steps, float r_shunt, float gain) constexpr
References servio::cnv::off_scale::offset.
current() [1/2]
float servio::cnv::current (converter const & conv, drv::get_curr_iface const & curr_drv, drv::motor_info_iface const & motor) inline
References current(), and servio::drv::get_curr_iface::get_current().
current() [2/2]
float servio::cnv::current (converter const & conv, uint32_t raw_current, drv::motor_info_iface const & motor) inline
References servio::cnv::linear_converter::convert(), servio::cnv::converter::current, and servio::drv::motor_info_iface::get_direction().
position()
float servio::cnv::position (converter const & conv, drv::get_pos_iface const & pos_drv) inline
References servio::cnv::linear_converter::convert(), servio::drv::get_pos_iface::get_position(), and servio::cnv::converter::position.