servio: fw Namespace Reference
fw Namespace Reference
Namespaces
drv
Classes
class current_callback
class position_callback
struct cfg_dispatcher
struct core
struct standard_callbacks
struct dispatcher
class monitor
struct check_bool
struct hal_check
Typedefs
using handler = em::protocol::register_handler< cfg_map >
Functions
void install_stop_callback (drv::leds *leds_ptr)
float current (const converter &conv, uint32_t raw_current, const drv::hbridge &hb)
float current (const converter &conv, const drv::current_interface &curr_drv, const drv::hbridge &hb)
float position (const converter &conv, const drv::position_interface &pos_drv)
ServioToHost handle_set_mode (microseconds now, control &ctl, const Mode &msg)
Mode get_mode (const control &ctl)
ServioToHost handle_get_property (const control &ctl, const metrics &met, const converter &conv, const drv::position_interface &pos_drv, const drv::current_interface &curr_drv, const drv::vcc_interface &vcc_drv, const drv::temperature_interface &temp_drv, const drv::hbridge &hb, const GetProperty &msg)
ServioToHost handle_set_config (cfg_dispatcher &cfg_disp, const Config &req)
ServioToHost handle_get_config (const cfg_dispatcher &cfg_disp, const GetConfig &req)
ServioToHost handle_commit_config (const cfg_dispatcher &cfg_disp, const auto &cfg_writer)
ServioToHost handle_clear_config (const auto &cfg_writer)
ServioToHost handle_message (dispatcher &dis, const HostToServio &msg)
template<typename InputType , typename OutputType , typename Handle >
std::tuple< bool, em::view< std::byte * > > process_message (em::view< const std::byte * > input_data, em::view< std::byte * > output_buffer, Handle &&h)
std::tuple< bool, em::view< std::byte * > > handle_message (dispatcher &dis, em::view< const std::byte * > input_data, em::view< std::byte * > output_buffer)
std::tuple< bool, em::view< std::byte * > > handle_message_packet (dispatcher &dis, em::view< const std::byte * > input_data, em::view< std::byte * > output_buffer)
template<typename Cfg , typename UnaryFunction >
bool map_cfg (uint32_t key, Cfg &cfg, UnaryFunction &&f)
ServioToHost error_msg (const char *msg)
bool decode (em::view< const std::byte * > data, HostToServio &msg)
decodes a bytes from data to HostToServio message, returns true on success
bool decode (em::view< const std::byte * > data, HostToServioPacket &msg)
std::tuple< bool, em::view< std::byte * > > encode (em::view< std::byte * > data, const ServioToHost &msg)
encodes a ServioToHost message to bytes, returns succes bool and subset of data that contains the serialized message
std::tuple< bool, em::view< std::byte * > > encode (em::view< std::byte * > data, const ServioToHostPacket &msg)
void stop_exec ()
template<typename... Components>
void multistart (Components &... comps)
void copy_string_to (const char *str, std::size_t size, auto &target)
void operator<< (const check_bool &, bool val)
void operator<< (hal_check, HAL_StatusTypeDef s)
Variables
em::static_function< void(), 16 > STOP_CALLBACK
Class Documentation
fw::dispatcher
struct fw::dispatcher
Class Members
cfg_dispatcher & cfg_disp
function_view< bool(const cfg_map *cfg) > cfg_writer
converter & conv
control & ctl
const current_interface & curr_drv
hbridge & hb
metrics & met
microseconds now
const position_interface & pos_drv
const temperature_interface & temp_drv
const vcc_interface & vcc_drv
fw::check_bool
struct fw::check_bool
fw::hal_check
struct fw::hal_check
Typedef Documentation
handler
using fw::handler = typedef em::protocol::register_handler< cfg_map >
Function Documentation
copy_string_to()
void fw::copy_string_to (const char * str, std::size_t size, auto & target)
current() [1/2]
float fw::current (const converter & conv, const drv::current_interface & curr_drv, const drv::hbridge & hb) inline
References current(), and fw::drv::current_interface::get_current().
current() [2/2]
float fw::current (const converter & conv, uint32_t raw_current, const drv::hbridge & hb) inline
References current_converter::convert(), converter::current, and fw::drv::hbridge::get_direction().
decode() [1/2]
bool fw::decode (em::view< const std::byte * > data, HostToServio & msg)
decodes a bytes from data to HostToServio message, returns true on success
decode() [2/2]
bool fw::decode (em::view< const std::byte * > data, HostToServioPacket & msg)
encode() [1/2]
std::tuple< bool, em::view< std::byte * > > fw::encode (em::view< std::byte * > data, const ServioToHost & msg)
encodes a ServioToHost message to bytes, returns succes bool and subset of data that contains the serialized message
encode() [2/2]
std::tuple< bool, em::view< std::byte * > > fw::encode (em::view< std::byte * > data, const ServioToHostPacket & msg)
error_msg()
ServioToHost fw::error_msg (const char * msg)
References copy_string_to().
get_mode()
Mode fw::get_mode (const control & ctl)
References CURRENT, DISENGAGED, POSITION, POWER, and VELOCITY.
handle_clear_config()
ServioToHost fw::handle_clear_config (const auto & cfg_writer)
References error_msg().
handle_commit_config()
ServioToHost fw::handle_commit_config (const cfg_dispatcher & cfg_disp, const auto & cfg_writer)
References error_msg(), and fw::cfg_dispatcher::map.
handle_get_config()
ServioToHost fw::handle_get_config (const cfg_dispatcher & cfg_disp, const GetConfig & req)
References map_cfg().
handle_get_property()
ServioToHost fw::handle_get_property (const control & ctl, const metrics & met, const converter & conv, const drv::position_interface & pos_drv, const drv::current_interface & curr_drv, const drv::vcc_interface & vcc_drv, const drv::temperature_interface & temp_drv, const drv::hbridge & hb, const GetProperty & msg)
References temperature_converter::convert(), voltage_converter::convert(), current(), error_msg(), get_mode(), fw::drv::temperature_interface::get_temperature(), fw::drv::vcc_interface::get_vcc(), metrics::get_velocity(), position(), converter::temp, and converter::vcc.
handle_message() [1/2]
ServioToHost fw::handle_message (dispatcher & dis, const HostToServio & msg)
References fw::dispatcher::cfg_disp, fw::dispatcher::cfg_writer, fw::dispatcher::conv, fw::dispatcher::ctl, fw::dispatcher::curr_drv, error_msg(), handle_clear_config(), handle_commit_config(), handle_get_config(), handle_get_property(), handle_set_config(), handle_set_mode(), fw::dispatcher::hb, fw::dispatcher::met, fw::dispatcher::now, fw::dispatcher::pos_drv, fw::dispatcher::temp_drv, and fw::dispatcher::vcc_drv.
handle_message() [2/2]
std::tuple< bool, em::view< std::byte * > > fw::handle_message (dispatcher & dis, em::view< const std::byte * > input_data, em::view< std::byte * > output_buffer)
handle_message_packet()
std::tuple< bool, em::view< std::byte * > > fw::handle_message_packet (dispatcher & dis, em::view< const std::byte * > input_data, em::view< std::byte * > output_buffer)
References handle_message().
handle_set_config()
ServioToHost fw::handle_set_config (cfg_dispatcher & cfg_disp, const Config & req)
References error_msg(), and map_cfg().
handle_set_mode()
ServioToHost fw::handle_set_mode (microseconds now, control & ctl, const Mode & msg)
References error_msg().
install_stop_callback()
void fw::install_stop_callback (drv::leds * leds_ptr) inline
References fw::drv::leds::force_red_led(), and STOP_CALLBACK.
map_cfg()
template<typename Cfg , typename UnaryFunction > bool fw::map_cfg (uint32_t key, Cfg & cfg, UnaryFunction && f)
References CURRENT_CONV_OFFSET, CURRENT_CONV_SCALE, CURRENT_LIM_MAX, CURRENT_LIM_MIN, CURRENT_LOOP_D, CURRENT_LOOP_I, CURRENT_LOOP_P, GROUP_ID, ID, MAXIMUM_TEMPERATURE, MINIMUM_VOLTAGE, MODEL, MOVING_DETECTION_STEP, POSITION_CONV_HIGHER_SETPOINT_ANGLE, POSITION_CONV_HIGHER_SETPOINT_VALUE, POSITION_CONV_LOWER_SETPOINT_ANGLE, POSITION_CONV_LOWER_SETPOINT_VALUE, POSITION_LIM_MAX, POSITION_LIM_MIN, POSITION_LOOP_D, POSITION_LOOP_I, POSITION_LOOP_P, STATIC_FRICTION_DECAY, STATIC_FRICTION_SCALE, TEMP_CONV_OFFSET, TEMP_CONV_SCALE, VELOCITY_LIM_MAX, VELOCITY_LIM_MIN, VELOCITY_LOOP_D, VELOCITY_LOOP_I, VELOCITY_LOOP_P, and VOLTAGE_CONV_SCALE.
multistart()
template<typename... Components> void fw::multistart (Components &... comps)
operator<<() [1/2]
void fw::operator<< (const check_bool & , bool val) inline
References stop_exec().
operator<<() [2/2]
void fw::operator<< (hal_check , HAL_StatusTypeDef s) inline
References stop_exec().
position()
float fw::position (const converter & conv, const drv::position_interface & pos_drv) inline
References position_converter::convert(), fw::drv::position_interface::get_position(), and converter::position.
process_message()
template<typename InputType , typename OutputType , typename Handle > std::tuple< bool, em::view< std::byte* > > fw::process_message (em::view< const std::byte * > input_data, em::view< std::byte * > output_buffer, Handle && h)
References decode(), and encode().
stop_exec()
void fw::stop_exec ()
References STOP_CALLBACK.
Variable Documentation
STOP_CALLBACK
em::static_function< void(), 16 > fw::STOP_CALLBACK