servio: plt Namespace Reference
plt Namespace Reference
Classes
struct dma_cfg
struct adc_cfg
struct uart_cfg
struct hb_timer_cfg
struct leds_gpio_cfg
struct leds_timer_cfg
Functions
void cfg_erase (uint32_t start_addr)
bool cfg_write (uint32_t addr, uint64_t val)
void setup_adc_channel (ADC_ChannelConfTypeDef &channel, fw::drv::pinch_cfg cfg)
em::result setup_adc (ADC_HandleTypeDef &adc, DMA_HandleTypeDef &dma, adc_cfg cfg)
em::result setup_clk ()
cfg::off_scale calculate_temp_conversion ()
consteval cfg::map generate_config ()
cfg::map get_default_config ()
em::result setup_gpio (const fw::drv::pin_cfg &cfg)
em::result setup_adc_timer (TIM_HandleTypeDef &tim, TIM_TypeDef *instance)
em::result setup_uart (UART_HandleTypeDef &uart, DMA_HandleTypeDef &tx_dma, uart_cfg cfg)
em::result setup_hbridge_timers (TIM_HandleTypeDef &tim, hb_timer_cfg cfg)
em::result setup_leds_channel (TIM_HandleTypeDef *tim, fw::drv::pinch_cfg cfg)
em::result setup_clock_timer (TIM_HandleTypeDef &tim, TIM_TypeDef *instance)
Class Documentation
plt::dma_cfg
struct plt::dma_cfg
Class Members
DMA_Channel_TypeDef * instance
uint32_t priority
uint32_t request
plt::adc_cfg
struct plt::adc_cfg
Class Members
ADC_TypeDef * adc_instance
uint32_t adc_irq_priority
uint32_t adc_trigger
dma_cfg dma
plt::uart_cfg
struct plt::uart_cfg
Class Members
uint32_t baudrate
IRQn_Type irq
uint32_t irq_priority
pin_cfg rx
pin_cfg tx
dma_cfg tx_dma
USART_TypeDef * uart_instance
plt::hb_timer_cfg
struct plt::hb_timer_cfg
Class Members
IRQn_Type irq
uint32_t irq_priority
pinch_cfg mc1
pinch_cfg mc2
uint16_t period
TIM_TypeDef * timer_instance
plt::leds_gpio_cfg
struct plt::leds_gpio_cfg
Class Members
pin_cfg blue
pin_cfg red
plt::leds_timer_cfg
struct plt::leds_timer_cfg
Class Members
pinch_cfg green
TIM_TypeDef * timer_instance
pinch_cfg yellow
Function Documentation
calculate_temp_conversion()
cfg::off_scale plt::calculate_temp_conversion ()
References cfg::off_scale::offset.
cfg_erase()
void plt::cfg_erase (uint32_t start_addr)
References fw::stop_exec().
cfg_write()
bool plt::cfg_write (uint32_t addr, uint64_t val)
References fw::stop_exec().
generate_config()
consteval cfg::map plt::generate_config ()
References cfg::calculate_current_conversion(), cfg::CURRENT_CONV_OFFSET, cfg::CURRENT_CONV_SCALE, cfg::get_default_config(), cfg::off_scale::offset, and cfg::off_scale::scale.
get_default_config()
cfg::map plt::get_default_config ()
References calculate_temp_conversion(), generate_config(), cfg::off_scale::offset, cfg::off_scale::scale, cfg::TEMP_CONV_OFFSET, and cfg::TEMP_CONV_SCALE.
setup_adc()
em::result plt::setup_adc (ADC_HandleTypeDef & adc, DMA_HandleTypeDef & dma, adc_cfg cfg)
setup_adc_channel()
void plt::setup_adc_channel (ADC_ChannelConfTypeDef & channel, fw::drv::pinch_cfg cfg)
setup_adc_timer()
em::result plt::setup_adc_timer (TIM_HandleTypeDef & tim, TIM_TypeDef * instance)
References fw::stop_exec().
setup_clk()
em::result plt::setup_clk ()
Initializes the peripherals clocks
References fw::stop_exec().
setup_clock_timer()
em::result plt::setup_clock_timer (TIM_HandleTypeDef & tim, TIM_TypeDef * instance)
setup_gpio()
em::result plt::setup_gpio (const fw::drv::pin_cfg & cfg)
setup_hbridge_timers()
em::result plt::setup_hbridge_timers (TIM_HandleTypeDef & tim, hb_timer_cfg cfg)
References fw::stop_exec().
setup_leds_channel()
em::result plt::setup_leds_channel (TIM_HandleTypeDef * tim, fw::drv::pinch_cfg cfg)
setup_uart()
em::result plt::setup_uart (UART_HandleTypeDef & uart, DMA_HandleTypeDef & tx_dma, uart_cfg cfg)
References fw::stop_exec().