servio: servio::ftester Namespace Reference
servio::ftester Namespace Reference
Classes
struct bmp_config
struct config
struct controller_interface
struct joque_test
struct openocd_flash_config
class recorder
struct test_system
Typedefs
template<typename T >
using opt = std::optional< T >
template<typename T >
using sptr = std::shared_ptr< T >
Functions
void flash_commands (CLI::App &app, vari::uvptr< openocd_flash_config, bmp_config > &flash_cmd)
config get_config (int argc, char *argv[])
joque::task make_openocd_flash_task (std::filesystem::path const &firmware, std::filesystem::path const &ocd_cfg, opt< std::filesystem::path > const &log_file, joque::resource const &dev_res)
joque::task make_bmp_flash_task (std::filesystem::path const &firmware, std::filesystem::path const &device, joque::resource const &dev_res)
void flash_firmware_openocd (std::filesystem::path const &firmware, std::filesystem::path const &ocdconf)
void handle_eptr (std::exception_ptr eptr)
bool handle_test_specifics (std::string_view name, test_system &sys, std::filesystem::path out_dir)
Variables
static constexpr em::protocol::channel_type rec_id = 4
Class Documentation
servio::ftester::bmp_config
struct servio::ftester::bmp_config
Class Members
path device
path fw
servio::ftester::config
struct servio::ftester::config
Class Members
uint32_t c_baudrate = 230400
path c_device = "/dev/ttyUSB0"
uint32_t d_baudrate = 230400
path d_device = "/dev/ttyACM0"
string filter
uvptr< openocd_flash_config, bmp_config > flash_cmd
opt< path > input = std::nullopt
opt< path > output_dir = std::nullopt
bool powerless = false
servio::ftester::openocd_flash_config
struct servio::ftester::openocd_flash_config
Class Members
path fw
path openocd_config
Typedef Documentation
opt
template<typename T > using servio::ftester::opt = typedef std::optional< T >
sptr
template<typename T > using servio::ftester::sptr = typedef std::shared_ptr< T >
Function Documentation
flash_commands()
void servio::ftester::flash_commands (CLI::App & app, vari::uvptr< openocd_flash_config, bmp_config > & flash_cmd)
flash_firmware_openocd()
void servio::ftester::flash_firmware_openocd (std::filesystem::path const & firmware, std::filesystem::path const & ocdconf)
get_config()
config servio::ftester::get_config (int argc, char * argv[])
References servio::scmdio::coms_opt(), servio::scmdio::dcoms_opt(), flash_commands(), servio::scmdio::powerless_flag(), and servio::scmdio::verbose_opt().
handle_eptr()
void servio::ftester::handle_eptr (std::exception_ptr eptr)
handle_test_specifics()
bool servio::ftester::handle_test_specifics (std::string_view name, test_system & sys, std::filesystem::path out_dir)
References servio::ftester::test_system::get_records().
make_bmp_flash_task()
joque::task servio::ftester::make_bmp_flash_task (std::filesystem::path const & firmware, std::filesystem::path const & device, joque::resource const & dev_res)
make_openocd_flash_task()
joque::task servio::ftester::make_openocd_flash_task (std::filesystem::path const & firmware, std::filesystem::path const & ocd_cfg, opt< std::filesystem::path > const & log_file, joque::resource const & dev_res)
Variable Documentation
rec_id
constexpr em::protocol::channel_type servio::ftester::rec_id = 4 static constexpr