servio: servio::klmn::tests Namespace Reference
servio::klmn::tests Namespace Reference
Functions
TEST (Kalman, predict)
TEST (Kalman, base)
Function Documentation
TEST() [1/2]
servio::klmn::tests::TEST (Kalman , base)
References servio::klmn::angle(), servio::klmn::angle_mod(), servio::klmn::state_range::offset, servio::base::pi, servio::klmn::simulate(), and servio::klmn::velocity().
TEST() [2/2]
servio::klmn::tests::TEST (Kalman , predict)
References servio::klmn::angle(), servio::klmn::get_control_input_model(), servio::klmn::get_process_noise_covariance(), servio::klmn::get_transition_model(), servio::klmn::predict(), and servio::klmn::velocity().