servio: servio::sntr::tests Namespace Reference
servio::sntr::tests Namespace Reference
Classes
struct central_sentry_fixture
struct sentry_fixture
struct test_clk
Functions
TEST (central_sentry, record)
TEST_F (central_sentry_fixture, empty_inop)
TEST_F (central_sentry_fixture, empty_degr)
TEST_F (central_sentry_fixture, one_deg_insert)
TEST_F (central_sentry_fixture, one_inop_insert)
TEST_F (sentry_fixture, init)
TEST_F (sentry_fixture, insert_inop)
TEST_F (sentry_fixture, insert_degr)
TEST_F (sentry_fixture, insert_wrong_code)
Function Documentation
TEST()
servio::sntr::tests::TEST (central_sentry , record)
References servio::sntr::record::data, servio::sntr::default_record(), servio::sntr::record::ecodes, servio::sntr::record::emsg, servio::sntr::record::src, servio::sntr::record::st, servio::sntr::record::tp, and servio::sntr::UNSET.
TEST_F() [1/8]
servio::sntr::tests::TEST_F (central_sentry_fixture , empty_degr)
TEST_F() [2/8]
servio::sntr::tests::TEST_F (central_sentry_fixture , empty_inop)
TEST_F() [3/8]
servio::sntr::tests::TEST_F (central_sentry_fixture , one_deg_insert)
References servio::sntr::SET, and servio::sntr::UNSET.
TEST_F() [4/8]
servio::sntr::tests::TEST_F (central_sentry_fixture , one_inop_insert)
References servio::sntr::SET, and servio::sntr::UNSET.
TEST_F() [5/8]
servio::sntr::tests::TEST_F (sentry_fixture , init)
References servio::sntr::sentry::set_inoperable().
TEST_F() [6/8]
servio::sntr::tests::TEST_F (sentry_fixture , insert_degr)
References servio::sntr::SET, servio::sntr::sentry::set_degraded(), and servio::sntr::sentry::unset_degraded().
TEST_F() [7/8]
servio::sntr::tests::TEST_F (sentry_fixture , insert_inop)
References servio::sntr::SET, and servio::sntr::sentry::set_inoperable().
TEST_F() [8/8]
servio::sntr::tests::TEST_F (sentry_fixture , insert_wrong_code)
References servio::sntr::eid_bits, servio::sntr::forbidden_eid, servio::sntr::SET, servio::sntr::sentry::set_degraded(), servio::sntr::sentry::set_inoperable(), and servio::sntr::terminated_eid.