servio: servio::str_lib Namespace Reference
servio::str_lib Namespace Reference
Namespaces
namespace bits
Classes
struct _no_res
struct s_to_nr_res
union s_to_nr_res.__unnamed3__
Typedefs
using num = int32_t
using real = float
template<typename T >
using opt = std::optional< T >
Functions
constexpr void u_to_s (char *&p, char *e, std::unsigned_integral auto x) noexcept
constexpr void f_to_s (char *&p, char *e, float x) noexcept
constexpr bool hex_to_n (char const *&p, char const *e, num &x) noexcept
constexpr bool dec_to_n (char const *&p, char const *e, num &x) noexcept
constexpr bool apply_exp (char const *&p, char const *e, float &x) noexcept
constexpr bool s_to_nr (char const *&p, char const *e, s_to_nr_res &x) noexcept
constexpr bool lex_letters (char const *&p, char const *e) noexcept
TEST (iface, numreal)
Variables
constexpr _no_res no_res
Class Documentation
servio::str_lib::_no_res
struct servio::str_lib::_no_res
servio::str_lib::s_to_nr_res
struct servio::str_lib::s_to_nr_res
Class Members
union s_to_nr_res.__unnamed3__ __unnamed__
bool is_num = false
servio::str_lib::s_to_nr_res.__unnamed3__
union servio::str_lib::s_to_nr_res.__unnamed3__
Class Members
num n
real r
Typedef Documentation
num
using servio::str_lib::num = typedef int32_t
opt
template<typename T > using servio::str_lib::opt = typedef std::optional< T >
real
using servio::str_lib::real = typedef float
Function Documentation
apply_exp()
constexpr bool servio::str_lib::apply_exp (char const *& p, char const * e, float & x) constexpr noexcept
References dec_to_n(), servio::str_lib::bits::exp_pow(), and servio::str_lib::bits::try_sign().
dec_to_n()
constexpr bool servio::str_lib::dec_to_n (char const *& p, char const * e, num & x) constexpr noexcept
References servio::str_lib::bits::is_dec().
f_to_s()
constexpr void servio::str_lib::f_to_s (char *& p, char * e, float x) constexpr noexcept
References u_to_s().
hex_to_n()
constexpr bool servio::str_lib::hex_to_n (char const *& p, char const * e, num & x) constexpr noexcept
References servio::str_lib::bits::is_hex().
lex_letters()
constexpr bool servio::str_lib::lex_letters (char const *& p, char const * e) constexpr noexcept
References servio::str_lib::bits::is_id_letter(), and servio::str_lib::bits::is_letter().
s_to_nr()
constexpr bool servio::str_lib::s_to_nr (char const *& p, char const * e, s_to_nr_res & x) constexpr noexcept
References apply_exp(), dec_to_n(), servio::str_lib::bits::has_exp_suffix(), servio::str_lib::bits::hex_prefix(), hex_to_n(), servio::str_lib::bits::is_dec(), servio::str_lib::s_to_nr_res::is_num, and servio::str_lib::bits::try_sign().
TEST()
servio::str_lib::TEST (iface , numreal)
References no_res.
u_to_s()
constexpr void servio::str_lib::u_to_s (char *& p, char * e, std::unsigned_integral auto x) constexpr noexcept
Variable Documentation
no_res
constexpr _no_res servio::str_lib::no_res constexpr