servio: servio::drv Namespace Reference
servio::drv Namespace Reference
Namespaces
bits
tests
Classes
struct detailed_adc_channel
struct adc_channel
struct adc_channel_with_callback
struct adc_pooler
struct adc_pooler_period_cb
struct adc_pooler_vcc
struct adc_pooler_temperature
struct adc_pooler_position
struct adc_pooler_current
struct detailed_cb
struct empty_detailed_cb
struct value_cb
struct empty_value_cb
struct period_cb
struct empty_period_cb
class clock
class cobs_uart
struct pin_cfg
class dts_temp
class flash_storage
class hbridge
struct detailed_cb_iface
struct value_cb_iface
struct period_cb_iface
struct com_res
struct com_iface
struct storage_iface
struct leds_iface
struct clk_iface
struct period_iface
struct pwm_motor_iface
struct pos_iface
struct vcc_iface
struct temp_iface
struct curr_iface
class leds
class quad_encoder
Typedefs
template<typename Callable >
using current_cb = detailed_cb< Callable >
using empty_current_cb = empty_detailed_cb
template<typename Callable >
using position_cb = value_cb< Callable >
using empty_position_cb = empty_value_cb
using current_cb_iface = detailed_cb_iface
using position_cb_iface = value_cb_iface
Enumerations
enum adc_error_codes {
ADC_POOLER_ISTART_ERR = 0x1 ,
ADC_POOLER_ISTOP_ERR = 0x2 ,
ADC_POOLER_DSTART_ERR = 0x3 ,
ADC_POOLER_DSTOP_ERR = 0x4 ,
ADC_POOLER_CFG_ERR = 0x5 ,
ADC_POOLER_NO_SAMPLES_ERR = 0x6 ,
ADC_POOLER_SAMPLES_OVER_ERR = 0x7
}
enum chan_ids {
CURRENT_CHANNEL = 0x1 ,
POSITION_CHANNEL = 0x2 ,
VCC_CHANNEL = 0x3 ,
TEMP_CHANNEL = 0x4
}
enum cobs_error_codes {
COBS_HAL_ERROR_IRQ_ERR = 0x1 ,
COBS_HAL_RX_START_ERR = 0x2
}
Functions
em::result send (com_iface &iface, microseconds timeout, auto &... data)
void wait_for (clk_iface &clk, microseconds ms)
auto retain_callback (period_iface &period)
auto retain_callback (curr_iface &curr_drv)
auto retain_callback (pos_iface &pos_drv)
TEST (COBS, cont)
Variables
chan_ids ADC_FULL_SEQUENCE []
chan_ids ADC_CURR_POS_VCC_SEQUENCE []
chan_ids ADC_CURR_VCC_SEQUENCE []
empty_detailed_cb EMPTY_DETAILED_CALLBACK
empty_value_cb EMPTY_CALLBACK
empty_period_cb EMPTY_PERIOD_CB
Class Documentation
servio::drv::pin_cfg
struct servio::drv::pin_cfg
Class Members
uint8_t alternate
uint8_t mode
uint16_t pin
GPIO_TypeDef * port
uint8_t pull
Typedef Documentation
current_cb
template<typename Callable > using servio::drv::current_cb = typedef detailed_cb< Callable >
current_cb_iface
using servio::drv::current_cb_iface = typedef detailed_cb_iface
empty_current_cb
using servio::drv::empty_current_cb = typedef empty_detailed_cb
empty_position_cb
using servio::drv::empty_position_cb = typedef empty_value_cb
position_cb
template<typename Callable > using servio::drv::position_cb = typedef value_cb< Callable >
position_cb_iface
using servio::drv::position_cb_iface = typedef value_cb_iface
Enumeration Type Documentation
adc_error_codes
enum servio::drv::adc_error_codes
Enumerator
ADC_POOLER_ISTART_ERR
ADC_POOLER_ISTOP_ERR
ADC_POOLER_DSTART_ERR
ADC_POOLER_DSTOP_ERR
ADC_POOLER_CFG_ERR
ADC_POOLER_NO_SAMPLES_ERR
ADC_POOLER_SAMPLES_OVER_ERR
chan_ids
enum servio::drv::chan_ids
Enumerator
CURRENT_CHANNEL
POSITION_CHANNEL
VCC_CHANNEL
TEMP_CHANNEL
cobs_error_codes
enum servio::drv::cobs_error_codes
Enumerator
COBS_HAL_ERROR_IRQ_ERR
COBS_HAL_RX_START_ERR
Function Documentation
retain_callback() [1/3]
auto servio::drv::retain_callback (curr_iface & curr_drv) inline
References servio::drv::curr_iface::get_current_callback().
retain_callback() [2/3]
auto servio::drv::retain_callback (period_iface & period) inline
References servio::drv::period_iface::get_period_callback().
retain_callback() [3/3]
auto servio::drv::retain_callback (pos_iface & pos_drv) inline
References servio::drv::pos_iface::get_position_callback().
send()
em::result servio::drv::send (com_iface & iface, microseconds timeout, auto &... data)
References servio::drv::com_iface::send().
TEST()
servio::drv::TEST (COBS , cont)
References servio::drv::bits::load_message(), servio::drv::bits::on_rx_cplt_irq(), and servio::drv::bits::cobs_rx_container::sizes.
wait_for()
void servio::drv::wait_for (clk_iface & clk, microseconds ms) inline
References servio::drv::clk_iface::get_us().
Variable Documentation
ADC_CURR_POS_VCC_SEQUENCE
chan_ids servio::drv::ADC_CURR_POS_VCC_SEQUENCE[]
Initial value:
= {
    CURRENT_CHANNEL,
    POSITION_CHANNEL,
    CURRENT_CHANNEL,
    VCC_CHANNEL,
}
ADC_CURR_VCC_SEQUENCE
chan_ids servio::drv::ADC_CURR_VCC_SEQUENCE[]
Initial value:
= {
    CURRENT_CHANNEL,
    VCC_CHANNEL,
}
ADC_FULL_SEQUENCE
chan_ids servio::drv::ADC_FULL_SEQUENCE[]
Initial value:
= {
    CURRENT_CHANNEL,
    POSITION_CHANNEL,
    CURRENT_CHANNEL,
    VCC_CHANNEL,
    CURRENT_CHANNEL,
    POSITION_CHANNEL,
    CURRENT_CHANNEL,
    TEMP_CHANNEL,
}
EMPTY_CALLBACK
empty_value_cb servio::drv::EMPTY_CALLBACK inline
EMPTY_DETAILED_CALLBACK
empty_detailed_cb servio::drv::EMPTY_DETAILED_CALLBACK inline
EMPTY_PERIOD_CB
empty_period_cb servio::drv::EMPTY_PERIOD_CB inline