servio: servio::drv::bits Namespace Reference
servio::drv::bits Namespace Reference
Classes
struct char_rx_container
struct cobs_rx_container
struct rx_buffer
Functions
template<char C>
void on_rx_cplt_irq (char_rx_container< C > &rx, std::byte inpt)
void on_rx_cplt_irq (cobs_rx_container &rx, std::byte inpt)
std::tuple< bool, em::view< std::byte * > > load_message (rx_buffer &rx, em::view< std::byte * > data)
em::result uart_start_it (UART_HandleTypeDef *h, std::byte &b)
template<auto START_ERR>
void uart_rx_cplt_irq (UART_HandleTypeDef *h, UART_HandleTypeDef *local, auto &drv, auto &rx_buff, std::byte &rx_byte, sntr::sentry &sentry)
void uart_err_irq (UART_HandleTypeDef *h, UART_HandleTypeDef *local, sntr::sentry &sentry)
Variables
static constexpr uint32_t uart_common_tolerable_hal_errors
Function Documentation
load_message()
std::tuple< bool, em::view< std::byte * > > servio::drv::bits::load_message (rx_buffer & rx, em::view< std::byte * > data)
References servio::drv::bits::rx_buffer::buffer, and servio::drv::bits::rx_buffer::sizes.
on_rx_cplt_irq() [1/2]
template<char C> void servio::drv::bits::on_rx_cplt_irq (char_rx_container< C > & rx, std::byte inpt)
References servio::drv::bits::rx_buffer::buffer, servio::drv::bits::char_rx_container< C >::received_size, and servio::drv::bits::rx_buffer::sizes.
on_rx_cplt_irq() [2/2]
void servio::drv::bits::on_rx_cplt_irq (cobs_rx_container & rx, std::byte inpt) inline
References servio::drv::bits::rx_buffer::buffer, servio::drv::bits::cobs_rx_container::cobs_dec, servio::drv::bits::cobs_rx_container::received_size, and servio::drv::bits::rx_buffer::sizes.
uart_err_irq()
void servio::drv::bits::uart_err_irq (UART_HandleTypeDef * h, UART_HandleTypeDef * local, sntr::sentry & sentry) inline
References servio::sntr::sentry::set_degraded_set(), servio::sntr::sentry::set_inoperable_set(), and uart_common_tolerable_hal_errors.
uart_rx_cplt_irq()
template<auto START_ERR> void servio::drv::bits::uart_rx_cplt_irq (UART_HandleTypeDef * h, UART_HandleTypeDef * local, auto & drv, auto & rx_buff, std::byte & rx_byte, sntr::sentry & sentry) inline
References on_rx_cplt_irq(), and servio::sntr::sentry::set_inoperable().
uart_start_it()
em::result servio::drv::bits::uart_start_it (UART_HandleTypeDef * h, std::byte & b) inline
Variable Documentation
uart_common_tolerable_hal_errors
constexpr uint32_t servio::drv::bits::uart_common_tolerable_hal_errors static constexpr
Initial value:
=
    HAL_UART_ERROR_ORE | HAL_UART_ERROR_DMA | HAL_UART_ERROR_FE | HAL_UART_ERROR_NE