servio: gen Namespace Reference
gen Namespace Reference
Functions
None regenerate_file (str filename, List[Dict[str, Any]] fields, Callable[[TextIO, List[Dict[str, Any]]], None] generator_func)
None generate_key (TextIO fd, List[Dict[str, Any]] fields)
None generate_key_values (TextIO fd, List[Dict[str, Any]] fields)
None generate_ids (TextIO fd, List[Dict[str, Any]] fields)
None generate_str_to_key (TextIO fd, List[Dict[str, Any]] fields)
None generate_to_str (TextIO fd, List[Dict[str, Any]] fields)
None generate_key_to_id (TextIO fd, List[Dict[str, Any]] fields)
None generate_id_to_key (TextIO fd, List[Dict[str, Any]] fields)
None generate_key_trait (TextIO fd, List[Dict[str, Any]] fields)
None generate_map (TextIO fd, List[Dict[str, Any]] fields)
None generate_cfg_doc (TextIO fd, List[Dict[str, Any]] fields)
None generate_cfg (TextIO fd, List[Dict[str, Any]] fields)
None main ()
str apply_prefix (str prefix, str name, str sep="_")
None gen_arg_cmd_struct (TextIO fd, Dict[str, Any] cmd, List[Dict[str, Any]] args, str prefix)
None gen_arg_cmd (TextIO fd, Dict[str, Any] cmd, List[Dict[str, Any]] args, str prefix)
None gen_arg_doc (TextIO fd, Dict[str, Any] cmd, List[Dict[str, Any]] args, str prefix)
None gen_group_cmd_struct (TextIO fd, Dict[str, Any] cmd, str prefix)
None gen_group_cmd (TextIO fd, Dict[str, Any] cmd, str prefix)
None gen_group_doc (TextIO fd, Dict[str, Any] cmd, str prefix)
None traverse_commands (TextIO fd, Dict[str, Any] cmd, str prefix, CmdHandler cmd_handler, GroupHandler group_handler, str separator="_", bool group_first=False)
None traverse_gen (TextIO fd, Dict[str, Any] cmd, str prefix)
None traverse_structs (TextIO fd, Dict[str, Any] cmd, str prefix)
None traverse_doc (TextIO fd, Dict[str, Any] cmd, str prefix)
None gen_type (TextIO fd, Dict[str, Any] tp)
None gen_type_convert (TextIO fd, Dict[str, Any] tp)
None gen_type_doc (TextIO fd, Dict[str, Any] tp)
None regenerate (str filename, Callable[[TextIO], None] cb)
None gen_parse (TextIO fd, Dict[str, Any] root)
None gen_def (TextIO fd, Dict[str, Any] root)
None gen_md (TextIO fd, Dict[str, Any] root)
Variables
CmdHandler = Callable[[TextIO, Dict[str, Any], List[Dict[str, Any]], str], None]
GroupHandler = Callable[[TextIO, Dict[str, Any], str], None]
root = json.load(fd)
Function Documentation
apply_prefix()
str gen.apply_prefix (str prefix, str name, str sep = "_")
gen_arg_cmd()
None gen.gen_arg_cmd (TextIO fd, Dict[str, Any] cmd, List[Dict[str, Any]] args, str prefix)
References apply_prefix().
gen_arg_cmd_struct()
None gen.gen_arg_cmd_struct (TextIO fd, Dict[str, Any] cmd, List[Dict[str, Any]] args, str prefix)
References apply_prefix().
gen_arg_doc()
None gen.gen_arg_doc (TextIO fd, Dict[str, Any] cmd, List[Dict[str, Any]] args, str prefix)
References apply_prefix().
gen_def()
None gen.gen_def (TextIO fd, Dict[str, Any] root)
References gen_type(), and traverse_structs().
gen_group_cmd()
None gen.gen_group_cmd (TextIO fd, Dict[str, Any] cmd, str prefix)
References apply_prefix().
gen_group_cmd_struct()
None gen.gen_group_cmd_struct (TextIO fd, Dict[str, Any] cmd, str prefix)
References apply_prefix().
gen_group_doc()
None gen.gen_group_doc (TextIO fd, Dict[str, Any] cmd, str prefix)
References apply_prefix().
gen_md()
None gen.gen_md (TextIO fd, Dict[str, Any] root)
References gen_type_doc(), and traverse_doc().
gen_parse()
None gen.gen_parse (TextIO fd, Dict[str, Any] root)
References gen_type_convert(), and traverse_gen().
gen_type()
None gen.gen_type (TextIO fd, Dict[str, Any] tp)
gen_type_convert()
None gen.gen_type_convert (TextIO fd, Dict[str, Any] tp)
gen_type_doc()
None gen.gen_type_doc (TextIO fd, Dict[str, Any] tp)
generate_cfg()
None gen.generate_cfg (TextIO fd, List[Dict[str, Any]] fields)
References generate_id_to_key(), generate_ids(), generate_key(), generate_key_to_id(), generate_key_trait(), generate_key_values(), generate_map(), generate_str_to_key(), and generate_to_str().
generate_cfg_doc()
None gen.generate_cfg_doc (TextIO fd, List[Dict[str, Any]] fields)
generate_id_to_key()
None gen.generate_id_to_key (TextIO fd, List[Dict[str, Any]] fields)
generate_ids()
None gen.generate_ids (TextIO fd, List[Dict[str, Any]] fields)
generate_key()
None gen.generate_key (TextIO fd, List[Dict[str, Any]] fields)
generate_key_to_id()
None gen.generate_key_to_id (TextIO fd, List[Dict[str, Any]] fields)
generate_key_trait()
None gen.generate_key_trait (TextIO fd, List[Dict[str, Any]] fields)
generate_key_values()
None gen.generate_key_values (TextIO fd, List[Dict[str, Any]] fields)
generate_map()
None gen.generate_map (TextIO fd, List[Dict[str, Any]] fields)
generate_str_to_key()
None gen.generate_str_to_key (TextIO fd, List[Dict[str, Any]] fields)
generate_to_str()
None gen.generate_to_str (TextIO fd, List[Dict[str, Any]] fields)
main()
None gen.main ()
References main(), and regenerate_file().
regenerate()
None gen.regenerate (str filename, Callable[[TextIO], None] cb)
regenerate_file()
None gen.regenerate_file (str filename, List[Dict[str, Any]] fields, Callable[[TextIO, List[Dict[str, Any]]], None] generator_func)
traverse_commands()
None gen.traverse_commands (TextIO fd, Dict[str, Any] cmd, str prefix, CmdHandler cmd_handler, GroupHandler group_handler, str separator = "_", bool group_first = False)
Generic function to traverse command structure with different handlers.
References apply_prefix(), and traverse_commands().
traverse_doc()
None gen.traverse_doc (TextIO fd, Dict[str, Any] cmd, str prefix)
Generate documentation by traversing commands.
References traverse_commands().
traverse_gen()
None gen.traverse_gen (TextIO fd, Dict[str, Any] cmd, str prefix)
Generate parsing code by traversing commands.
References traverse_commands().
traverse_structs()
None gen.traverse_structs (TextIO fd, Dict[str, Any] cmd, str prefix)
Generate struct definitions by traversing commands.
References traverse_commands().
Variable Documentation
CmdHandler
gen.CmdHandler = Callable[[TextIO, Dict[str, Any], List[Dict[str, Any]], str], None]
GroupHandler
gen.GroupHandler = Callable[[TextIO, Dict[str, Any], str], None]
root
gen.root = json.load(fd)