servio: servio::cfg Namespace Reference
servio::cfg Namespace Reference
Classes
struct cfg_type_trait
struct cfg_type_trait< encoder_mode >
struct cfg_type_trait< uint32_t >
struct context
struct dispatcher
struct handler
struct iface
struct key_trait
struct key_trait< key::current_conv_offset >
struct key_trait< key::current_conv_scale >
struct key_trait< key::encoder_mode >
struct key_trait< key::group_id >
struct key_trait< key::id >
struct key_trait< key::invert_hbridge >
struct key_trait< key::maximum_temperature >
struct key_trait< key::minimum_voltage >
struct key_trait< key::model >
struct key_trait< key::moving_detection_step >
struct key_trait< key::position_high_angle >
struct key_trait< key::position_low_angle >
struct key_trait< key::quad_encoder_range >
struct key_trait< key::temp_conv_offset >
struct key_trait< key::temp_conv_scale >
struct key_trait< key::voltage_conv_scale >
struct map
struct off_scale
struct resolve_governor_res
struct root_handler
Typedefs
using string = em::string_buffer< 32 >
using base_t = vari::typelist< string, float, int32_t, bool >
using value_type = vari::typelist< uint32_t, float, bool, encoder_mode, string >
using value_variant = std::variant< uint32_t, float, bool, encoder_mode, string >
Enumerations
enum class encoder_mode : uint8_t {
analog = 1 ,
quad = 2
}
enum class key : uint32_t {
model = 1 ,
id = 2 ,
group_id = 3 ,
encoder_mode = 4 ,
position_low_angle = 11 ,
position_high_angle = 12 ,
current_conv_scale = 14 ,
current_conv_offset = 15 ,
temp_conv_scale = 16 ,
temp_conv_offset = 17 ,
voltage_conv_scale = 18 ,
invert_hbridge = 19 ,
minimum_voltage = 62 ,
maximum_temperature = 65 ,
moving_detection_step = 66 ,
quad_encoder_range = 80
}
Functions
template<typename T >
opt_str_err load_value (T &tg, vari::vref< base_t const > expr)
template<typename T >
vari::vval< base_t > store_value (T val)
void for_each_key (iface &ifa, auto &&f)
constexpr std::optional< encoder_mode > str_to_encoder_mode (std::string_view str)
constexpr std::string_view encoder_mode_to_str (encoder_mode em)
constexpr std::string_view to_str (key k)
constexpr uint32_t key_to_id (key k)
constexpr key id_to_key (uint32_t id)
vari::vval< vari::vref< iface >, str_err > find_iface (iface *root_handler, gov::governor_manager &gm, std::string_view gov)
opt< resolve_governor_res > resolve_governor (std::string_view field, std::string_view governor)
constexpr off_scale calculate_current_conversion (float v_max, float v_min, float steps, float r_shunt, float gain)
Variables
constexpr std::array< uint32_t, 16 > ids
Class Documentation
servio::cfg::cfg_type_trait
struct servio::cfg::cfg_type_trait
template<typename T>
struct servio::cfg::cfg_type_trait< T >
servio::cfg::context
struct servio::cfg::context
Class Members
map map
servio::cfg::key_trait
struct servio::cfg::key_trait
template<key K>
struct servio::cfg::key_trait< K >
servio::cfg::key_trait< key::current_conv_offset >
struct servio::cfg::key_trait< key::current_conv_offset >
Class Members
typedef float type
servio::cfg::key_trait< key::current_conv_scale >
struct servio::cfg::key_trait< key::current_conv_scale >
Class Members
typedef float type
servio::cfg::key_trait< key::encoder_mode >
struct servio::cfg::key_trait< key::encoder_mode >
Class Members
typedef encoder_mode type
servio::cfg::key_trait< key::group_id >
struct servio::cfg::key_trait< key::group_id >
Class Members
typedef uint32_t type
servio::cfg::key_trait< key::id >
struct servio::cfg::key_trait< key::id >
Class Members
typedef uint32_t type
servio::cfg::key_trait< key::invert_hbridge >
struct servio::cfg::key_trait< key::invert_hbridge >
Class Members
typedef bool type
servio::cfg::key_trait< key::maximum_temperature >
struct servio::cfg::key_trait< key::maximum_temperature >
Class Members
typedef float type
servio::cfg::key_trait< key::minimum_voltage >
struct servio::cfg::key_trait< key::minimum_voltage >
Class Members
typedef float type
servio::cfg::key_trait< key::model >
struct servio::cfg::key_trait< key::model >
Class Members
typedef string type
servio::cfg::key_trait< key::moving_detection_step >
struct servio::cfg::key_trait< key::moving_detection_step >
Class Members
typedef float type
servio::cfg::key_trait< key::position_high_angle >
struct servio::cfg::key_trait< key::position_high_angle >
Class Members
typedef float type
servio::cfg::key_trait< key::position_low_angle >
struct servio::cfg::key_trait< key::position_low_angle >
Class Members
typedef float type
servio::cfg::key_trait< key::quad_encoder_range >
struct servio::cfg::key_trait< key::quad_encoder_range >
Class Members
typedef uint32_t type
servio::cfg::key_trait< key::temp_conv_offset >
struct servio::cfg::key_trait< key::temp_conv_offset >
Class Members
typedef float type
servio::cfg::key_trait< key::temp_conv_scale >
struct servio::cfg::key_trait< key::temp_conv_scale >
Class Members
typedef float type
servio::cfg::key_trait< key::voltage_conv_scale >
struct servio::cfg::key_trait< key::voltage_conv_scale >
Class Members
typedef float type
servio::cfg::off_scale
struct servio::cfg::off_scale
Class Members
float offset
float scale
servio::cfg::resolve_governor_res
struct servio::cfg::resolve_governor_res
Class Members
string_view field
string_view governor
Typedef Documentation
base_t
using servio::cfg::base_t = typedef vari::typelist< string, float, int32_t, bool >
string
using servio::cfg::string = typedef em::string_buffer< 32 >
value_type
using servio::cfg::value_type = typedef vari::typelist< uint32_t, float, bool, encoder_mode, string >
value_variant
using servio::cfg::value_variant = typedef std::variant< uint32_t, float, bool, encoder_mode, string >
Enumeration Type Documentation
encoder_mode
enum class servio::cfg::encoder_mode : uint8_t strong
Enumerator
analog
quad
key
enum class servio::cfg::key : uint32_t strong
Enumerator
model
id
group_id
encoder_mode
position_low_angle
position_high_angle
current_conv_scale
current_conv_offset
temp_conv_scale
temp_conv_offset
voltage_conv_scale
invert_hbridge
minimum_voltage
maximum_temperature
moving_detection_step
quad_encoder_range
Function Documentation
calculate_current_conversion()
constexpr off_scale servio::cfg::calculate_current_conversion (float v_max, float v_min, float steps, float r_shunt, float gain) constexpr
References servio::cfg::off_scale::offset.
encoder_mode_to_str()
constexpr std::string_view servio::cfg::encoder_mode_to_str (encoder_mode em) constexpr
References analog, and quad.
find_iface()
vari::vval< vari::vref< iface >, str_err > servio::cfg::find_iface (iface * root_handler, gov::governor_manager & gm, std::string_view gov) inline
References servio::gov::governor_manager::governors().
for_each_key()
void servio::cfg::for_each_key (iface & ifa, auto && f)
References servio::cfg::iface::on_cmd_list().
id_to_key()
constexpr key servio::cfg::id_to_key (uint32_t id) constexpr
References current_conv_offset, current_conv_scale, encoder_mode, group_id, id, invert_hbridge, maximum_temperature, minimum_voltage, model, moving_detection_step, position_high_angle, position_low_angle, quad_encoder_range, temp_conv_offset, temp_conv_scale, and voltage_conv_scale.
key_to_id()
constexpr uint32_t servio::cfg::key_to_id (key k) constexpr
References current_conv_offset, current_conv_scale, encoder_mode, group_id, id, invert_hbridge, maximum_temperature, minimum_voltage, model, moving_detection_step, position_high_angle, position_low_angle, quad_encoder_range, temp_conv_offset, temp_conv_scale, and voltage_conv_scale.
load_value()
template<typename T > opt_str_err servio::cfg::load_value (T & tg, vari::vref< base_t const > expr)
References load_value(), and servio::parser::load_value().
resolve_governor()
opt< resolve_governor_res > servio::cfg::resolve_governor (std::string_view field, std::string_view governor) inline
References servio::cfg::resolve_governor_res::governor.
store_value()
template<typename T > vari::vval< base_t > servio::cfg::store_value (T val)
str_to_encoder_mode()
constexpr std::optional< encoder_mode > servio::cfg::str_to_encoder_mode (std::string_view str) constexpr
References analog, and quad.
to_str()
constexpr std::string_view servio::cfg::to_str (key k) constexpr
References current_conv_offset, current_conv_scale, encoder_mode, group_id, id, invert_hbridge, maximum_temperature, minimum_voltage, model, moving_detection_step, position_high_angle, position_low_angle, quad_encoder_range, temp_conv_offset, temp_conv_scale, and voltage_conv_scale.
Variable Documentation
ids
constexpr std::array< uint32_t, 16 > servio::cfg::ids constexpr
Initial value:
= {
    1,
    2,
    3,
    4,
    11,
    12,
    14,
    15,
    16,
    17,
    18,
    19,
    62,
    65,
    66,
    80,
}