servio: servio::parser Namespace Reference
servio::parser Namespace Reference
Classes
struct end
struct err
struct id
struct lexer
struct parse_trait
struct parse_trait< A >
struct parse_trait< bool >
struct parse_trait< em::string_buffer< N > >
struct parse_trait< float >
struct parse_trait< uint32_t >
struct parse_trait< unit >
struct parser
struct str
struct unit
Typedefs
template<typename T >
using opt = std::optional< T >
using tok = vari::typelist< id, str, float, int32_t, err >
Functions
vari::vopt< std::string_view > parse_str (char const *&p, char const *e) noexcept
opt< float > _real (parser &p)
opt< bool > _bool (parser &p)
TEST (iface, str)
Class Documentation
servio::parser::end
struct servio::parser::end
servio::parser::err
struct servio::parser::err
servio::parser::id
struct servio::parser::id
Class Members
string_view s
servio::parser::parse_trait
struct servio::parser::parse_trait
template<typename T>
struct servio::parser::parse_trait< T >
servio::parser::str
struct servio::parser::str
Class Members
string_view s
Typedef Documentation
opt
template<typename T > using servio::parser::opt = typedef std::optional< T >
tok
using servio::parser::tok = typedef vari::typelist< id, str, float, int32_t, err >
Function Documentation
_bool()
opt< bool > servio::parser::_bool (parser & p) inline
References servio::parser::parser::expr().
_real()
opt< float > servio::parser::_real (parser & p) inline
References servio::parser::parser::expr().
parse_str()
vari::vopt< std::string_view > servio::parser::parse_str (char const *& p, char const * e) inline noexcept
References servio::str_lib::bits::is_id_letter().
TEST()
servio::parser::TEST (iface , str)
References parse_str().