servio: servio::tests Namespace Reference
servio::tests Namespace Reference
Functions
TEST (CFG, storage)
template<typename T >
std::set< uint32_t > get_enum_ids ()
template<typename T >
std::set< uint32_t > get_iface_ids ()
std::vector< uint32_t > diff (std::set< uint32_t > const &lh, std::set< uint32_t > const &rh)
TEST (CFG, cfg_proto_id_match)
TEST (CFG, encoder_match)
TEST (CFG, cfg_types)
Function Documentation
diff()
std::vector< uint32_t > servio::tests::diff (std::set< uint32_t > const & lh, std::set< uint32_t > const & rh)
get_enum_ids()
template<typename T > std::set< uint32_t > servio::tests::get_enum_ids ()
get_iface_ids()
template<typename T > std::set< uint32_t > servio::tests::get_iface_ids ()
TEST() [1/4]
servio::tests::TEST (CFG , cfg_proto_id_match)
References diff().
TEST() [2/4]
servio::tests::TEST (CFG , cfg_types)
References servio::cfg::get_default_config().
TEST() [3/4]
servio::tests::TEST (CFG , encoder_match)
TEST() [4/4]
servio::tests::TEST (CFG , storage)
References servio::cfg::find_next_page(), servio::cfg::find_oldest_page(), servio::cfg::find_unused_page(), servio::cfg::get_default_config(), servio::cfg::load(), and servio::cfg::store().