servio: servio::brd Namespace Reference
servio::brd Namespace Reference
Classes
struct adc_set
struct dma_cfg
struct adc_cfg
struct uart_cfg
struct hb_timer_cfg
struct leds_timer_cfg
Typedefs
using page = em::view< std::byte * >
An API that has to be implemented by each board variation.
using adc_pooler_type = drv::adc_pooler< adc_set >
Functions
em::view< const page * > get_persistent_pages ()
Pages that shall be used for persistent configuration.
cfg::map get_default_config ()
Returns default configuration for servo for the board.
em::result setup_board ()
Initial setup call for the board.
core::drivers setup_core_drivers (const cfg::map &)
Initialize all core drivers for the servo.
drv::com_iface * setup_debug_comms ()
Initialize debug interface.
adc_pooler_type * adc_pooler_setup (bool enable_pos)
drv::hbridge * hbridge_setup ()
drv::cobs_uart * comms_setup ()
drv::leds * leds_setup ()
drv::pos_iface * quad_encoder_setup (uint32_t period)
em::result start_callback (core::drivers &cdrv)
void install_stop_callback (drv::pwm_motor_iface &motor, drv::leds_iface *leds_ptr)
consteval cnv::off_scale get_curr_coeff ()
em::view< std::byte * > page_at (uint32_t i)
void setup_adc_channel (ADC_ChannelConfTypeDef &channel, uint32_t chann_id, std::optional< drv::pin_cfg > port)
em::result setup_adc (ADC_HandleTypeDef &adc, DMA_HandleTypeDef &dma, adc_cfg cfg)
adc_pooler_type * adc_pooler_setup ()
em::result setup_clk ()
cnv::off_scale calculate_temp_conversion ()
consteval cfg::map generate_config ()
em::view< std::byte * > page (uint32_t i)
void setup_gpio (const drv::pin_cfg &cfg)
em::result setup_adc_timer (TIM_HandleTypeDef &tim, TIM_TypeDef *instance)
em::result setup_uart (UART_HandleTypeDef &uart, DMA_HandleTypeDef &tx_dma, uart_cfg cfg)
em::result setup_hbridge_timers (TIM_HandleTypeDef &tim, hb_timer_cfg cfg)
em::result setup_leds_channel (TIM_HandleTypeDef &tim, uint32_t chann, drv::pin_cfg cfg)
em::result setup_leds_timer (TIM_HandleTypeDef &tim, TIM_TypeDef *instance)
em::result setup_clock_timer (TIM_HandleTypeDef &tim, TIM_TypeDef *instance)
Variables
drv::pin_cfg HBRDIGE_VREF_PIN
TIM_HandleTypeDef TIM2_HANDLE = {}
drv::clock CLOCK { TIM2_HANDLE }
drv::leds LEDS { &TIM2_HANDLE }
std::array< sntr::record, 16 > INOPERABLE_RECORDS
std::array< sntr::record, 128 > DEGRADED_RECORDS
sntr::central_sentry CENTRAL_SENTRY
ADC_HandleTypeDef ADC_HANDLE {}
DMA_HandleTypeDef ADC_DMA_HANDLE {}
TIM_HandleTypeDef TIM6_HANDLE
adc_pooler_type ADC_POOLER { ADC_HANDLE, ADC_DMA_HANDLE, TIM6_HANDLE }
drv::adc_pooler_period_cb< ADC_POOLER > ADC_PERIOD_CB
drv::adc_pooler_vcc< ADC_POOLER > ADC_VCC
drv::adc_pooler_position< ADC_POOLER > ADC_POSITION
drv::adc_pooler_current< ADC_POOLER > ADC_CURRENT
UART_HandleTypeDef UART2_HANDLE {}
DMA_HandleTypeDef UART2_DMA_HANDLE {}
drv::cobs_uart COMMS { "comms", CENTRAL_SENTRY, CLOCK, &UART2_HANDLE, &UART2_DMA_HANDLE }
UART_HandleTypeDef UART1_HANDLE {}
DMA_HandleTypeDef UART1_DMA_HANDLE {}
drv::cobs_uart DEBUG_COMMS { "dcomms", CENTRAL_SENTRY, CLOCK, &UART1_HANDLE, &UART1_DMA_HANDLE }
TIM_HandleTypeDef TIM1_HANDLE {}
drv::hbridge HBRIDGE { &TIM1_HANDLE }
DTS_HandleTypeDef DTS_HANDLE {}
drv::dts_temp DTS_DRV { DTS_HANDLE }
TIM_HandleTypeDef TIM3_HANDLE {}
drv::quad_encoder QUAD { TIM3_HANDLE }
TIM_HandleTypeDef * QUAD_TRIGGER_TIMER = nullptr
std::array< em::view< std::byte * >, 2 > PERSISTENT_BLOCKS { page_at(0), page_at(1) }
TIM_HandleTypeDef ADC_TIM_HANDLE {}
drv::adc_pooler_temperature< ADC_POOLER > ADC_TEMPERATURE
Class Documentation
servio::brd::dma_cfg
struct servio::brd::dma_cfg
Class Members
DMA_Channel_TypeDef * instance
IRQn_Type irq
uint32_t irq_priority
uint32_t priority
uint32_t request
servio::brd::adc_cfg
struct servio::brd::adc_cfg
Class Members
ADC_TypeDef * adc_instance
uint32_t adc_irq_priority
dma_cfg dma
servio::brd::uart_cfg
struct servio::brd::uart_cfg
Class Members
uint32_t baudrate
IRQn_Type irq
uint32_t irq_priority
pin_cfg rx
pin_cfg tx
dma_cfg tx_dma
USART_TypeDef * uart_instance
servio::brd::hb_timer_cfg
struct servio::brd::hb_timer_cfg
Class Members
IRQn_Type irq
uint32_t irq_priority
uint32_t mc1_chan
pin_cfg mc1_pin
uint32_t mc2_chan
pin_cfg mc2_pin
uint16_t period
TIM_TypeDef * timer_instance
servio::brd::leds_timer_cfg
struct servio::brd::leds_timer_cfg
Class Members
pin_cfg green
uint32_t green_chan
TIM_TypeDef * timer_instance
pin_cfg yellow
uint32_t yellow_chan
Typedef Documentation
adc_pooler_type
typedef drv::adc_pooler< adc_set > servio::brd::adc_pooler_type
page
using servio::brd::page = typedef em::view< std::byte* >
An API that has to be implemented by each board variation.
Function Documentation
adc_pooler_setup() [1/2]
adc_pooler_type* servio::brd::adc_pooler_setup ()
References ADC_DMA_HANDLE, servio::drv::ADC_FULL_SEQUENCE, ADC_HANDLE, servio::brd::adc_cfg::adc_instance, ADC_POOLER, ADC_TIM_HANDLE, servio::brd::dma_cfg::instance, servio::drv::adc_pooler< Set >::set_seq(), setup_adc(), setup_adc_channel(), and setup_adc_timer().
adc_pooler_setup() [2/2]
adc_pooler_type* servio::brd::adc_pooler_setup (bool enable_pos)
References servio::drv::ADC_CURR_POS_VCC_SEQUENCE, servio::drv::ADC_CURR_VCC_SEQUENCE, ADC_DMA_HANDLE, ADC_HANDLE, servio::plt::adc_cfg::adc_instance, ADC_POOLER, servio::plt::dma_cfg::irq, servio::drv::adc_pooler< Set >::set_seq(), servio::plt::setup_adc(), servio::plt::setup_adc_channel(), servio::plt::setup_adc_timer(), and TIM6_HANDLE.
calculate_temp_conversion()
cnv::off_scale servio::brd::calculate_temp_conversion ()
References servio::cnv::off_scale::offset.
comms_setup()
drv::cobs_uart * servio::brd::comms_setup ()
References COMMS, servio::plt::dma_cfg::irq, servio::drv::pin_cfg::pin, setup_uart(), UART2_DMA_HANDLE, UART2_HANDLE, and servio::plt::uart_cfg::uart_instance.
generate_config()
consteval cfg::map servio::brd::generate_config ()
References servio::cnv::calc_current_conversion(), servio::cfg::CURRENT_CONV_OFFSET, servio::cfg::CURRENT_CONV_SCALE, servio::cfg::get_default_config(), servio::cnv::off_scale::offset, and servio::cnv::off_scale::scale.
get_curr_coeff()
consteval cnv::off_scale servio::brd::get_curr_coeff ()
References servio::cnv::calc_current_conversion().
get_default_config()
cfg::map servio::brd::get_default_config ()
Returns default configuration for servo for the board.
References servio::cfg::CURRENT_CONV_OFFSET, servio::cfg::CURRENT_CONV_SCALE, get_curr_coeff(), servio::plt::get_default_config(), servio::cnv::off_scale::offset, servio::cnv::off_scale::scale, servio::cfg::TEMP_CONV_OFFSET, and servio::cfg::TEMP_CONV_SCALE.
get_persistent_pages()
em::view< const em::view< std::byte * > * > servio::brd::get_persistent_pages ()
Pages that shall be used for persistent configuration.
References PERSISTENT_BLOCKS.
hbridge_setup()
drv::hbridge * servio::brd::hbridge_setup ()
References HBRIDGE, servio::drv::hbridge::setup(), servio::plt::setup_hbridge_timers(), TIM1_HANDLE, and servio::plt::hb_timer_cfg::timer_instance.
install_stop_callback()
void servio::brd::install_stop_callback (drv::pwm_motor_iface & motor, drv::leds_iface * leds_ptr)
References servio::drv::leds_iface::force_red_led(), servio::drv::pwm_motor_iface::force_stop(), HBRDIGE_VREF_PIN, servio::drv::pin_cfg::pin, servio::drv::pin_cfg::port, and servio::core::STOP_CALLBACK.
leds_setup()
drv::leds * servio::brd::leds_setup ()
References LEDS, servio::drv::pin_cfg::pin, servio::drv::leds::setup(), servio::plt::setup_gpio(), servio::plt::setup_leds_channel(), and TIM2_HANDLE.
page()
em::view< std::byte* > servio::brd::page (uint32_t i)
References _config_start.
page_at()
em::view< std::byte* > servio::brd::page_at (uint32_t i)
References _config_start.
quad_encoder_setup()
drv::pos_iface* servio::brd::quad_encoder_setup (uint32_t period)
References servio::drv::pin_cfg::pin, QUAD, QUAD_TRIGGER_TIMER, servio::plt::setup_encoder_timer(), servio::plt::setup_gpio(), TIM1_HANDLE, and TIM3_HANDLE.
setup_adc()
em::result servio::brd::setup_adc (ADC_HandleTypeDef & adc, DMA_HandleTypeDef & dma, adc_cfg cfg)
References servio::brd::adc_cfg::adc_instance, servio::brd::adc_cfg::adc_irq_priority, servio::brd::adc_cfg::dma, servio::brd::dma_cfg::instance, servio::brd::dma_cfg::irq, servio::brd::dma_cfg::irq_priority, servio::brd::dma_cfg::priority, servio::brd::dma_cfg::request, and servio::fw::stop_exec().
setup_adc_channel()
void servio::brd::setup_adc_channel (ADC_ChannelConfTypeDef & channel, uint32_t chann_id, std::optional< drv::pin_cfg > port)
References setup_gpio().
setup_adc_timer()
em::result servio::brd::setup_adc_timer (TIM_HandleTypeDef & tim, TIM_TypeDef * instance)
References servio::fw::stop_exec().
setup_board()
em::result servio::brd::setup_board ()
Initial setup call for the board.
References servio::plt::setup_clk().
setup_clk()
void servio::brd::setup_clk ()
Configure the main internal regulator output voltage
Initializes the RCC Oscillators according to the specified parameters in the RCC_OscInitTypeDef structure.
Initializes the CPU, AHB and APB buses clocks
Initializes the peripherals clocks
Configures CRS
References servio::fw::stop_exec().
setup_clock_timer()
em::result servio::brd::setup_clock_timer (TIM_HandleTypeDef & tim, TIM_TypeDef * instance)
References servio::fw::stop_exec().
setup_core_drivers()
core::drivers servio::brd::setup_core_drivers (const cfg::map & m)
Initialize all core drivers for the servo.
References ADC_CURRENT, ADC_PERIOD_CB, adc_pooler_setup(), ADC_POSITION, ADC_VCC, CLOCK, servio::core::drivers::clock, comms_setup(), DTS_DRV, DTS_HANDLE, servio::cfg::ENC_MODE_ANALOG, servio::cfg::ENC_MODE_QUAD, servio::cfg::ENCODER_MODE, HBRDIGE_VREF_PIN, hbridge_setup(), install_stop_callback(), leds_setup(), quad_encoder_setup(), servio::plt::setup_clock_timer(), servio::plt::setup_dts(), servio::plt::setup_gpio(), start_callback(), servio::fw::stop_exec(), and TIM2_HANDLE.
setup_debug_comms()
drv::com_iface * servio::brd::setup_debug_comms ()
Initialize debug interface.
References DEBUG_COMMS, servio::plt::dma_cfg::irq, servio::drv::pin_cfg::pin, setup_uart(), UART1_DMA_HANDLE, UART1_HANDLE, and servio::plt::uart_cfg::uart_instance.
setup_gpio()
void servio::brd::setup_gpio (const drv::pin_cfg & cfg)
References servio::drv::pin_cfg::alternate, servio::drv::pin_cfg::mode, servio::drv::pin_cfg::pin, and servio::drv::pin_cfg::port.
setup_hbridge_timers()
em::result servio::brd::setup_hbridge_timers (TIM_HandleTypeDef & tim, hb_timer_cfg cfg)
References servio::brd::hb_timer_cfg::irq, servio::brd::hb_timer_cfg::irq_priority, servio::brd::hb_timer_cfg::mc1_chan, servio::brd::hb_timer_cfg::mc1_pin, servio::brd::hb_timer_cfg::mc2_chan, servio::brd::hb_timer_cfg::mc2_pin, servio::brd::hb_timer_cfg::period, setup_gpio(), servio::fw::stop_exec(), and servio::brd::hb_timer_cfg::timer_instance.
setup_leds_channel()
em::result servio::brd::setup_leds_channel (TIM_HandleTypeDef & tim, uint32_t chann, drv::pin_cfg cfg)
References setup_gpio().
setup_leds_timer()
em::result servio::brd::setup_leds_timer (TIM_HandleTypeDef & tim, TIM_TypeDef * instance)
References servio::fw::stop_exec().
setup_uart()
em::result servio::brd::setup_uart (UART_HandleTypeDef & uart, DMA_HandleTypeDef & tx_dma, uart_cfg cfg)
References servio::drv::pin_cfg::alternate, servio::brd::uart_cfg::baudrate, servio::brd::dma_cfg::instance, servio::brd::dma_cfg::irq, servio::brd::uart_cfg::irq, servio::brd::dma_cfg::irq_priority, servio::brd::uart_cfg::irq_priority, servio::drv::pin_cfg::pin, servio::drv::pin_cfg::port, servio::brd::dma_cfg::priority, servio::brd::dma_cfg::request, servio::brd::uart_cfg::rx, servio::fw::stop_exec(), servio::brd::uart_cfg::tx, servio::brd::uart_cfg::tx_dma, and servio::brd::uart_cfg::uart_instance.
start_callback()
em::result servio::brd::start_callback (core::drivers & cdrv)
References ADC_POOLER, COMMS, servio::core::drivers::comms, HBRDIGE_VREF_PIN, HBRIDGE, LEDS, servio::core::drivers::leds, servio::core::drivers::motor, servio::drv::pin_cfg::pin, servio::drv::pin_cfg::port, servio::core::drivers::position, QUAD, QUAD_TRIGGER_TIMER, servio::drv::adc_pooler< Set >::start(), servio::drv::leds::start(), servio::drv::quad_encoder::start(), servio::drv::cobs_uart::start(), and servio::drv::hbridge::start().
Variable Documentation
ADC_CURRENT
drv::adc_pooler_current< ADC_POOLER > servio::brd::ADC_CURRENT
ADC_DMA_HANDLE
DMA_HandleTypeDef servio::brd::ADC_DMA_HANDLE {}
ADC_HANDLE
ADC_HandleTypeDef servio::brd::ADC_HANDLE {}
ADC_PERIOD_CB
drv::adc_pooler_period_cb< ADC_POOLER > servio::brd::ADC_PERIOD_CB
ADC_POOLER
adc_pooler_type servio::brd::ADC_POOLER { ADC_HANDLE, ADC_DMA_HANDLE, TIM6_HANDLE }
ADC_POSITION
drv::adc_pooler_position< ADC_POOLER > servio::brd::ADC_POSITION
ADC_TEMPERATURE
drv::adc_pooler_temperature< ADC_POOLER > servio::brd::ADC_TEMPERATURE
ADC_TIM_HANDLE
TIM_HandleTypeDef servio::brd::ADC_TIM_HANDLE {}
ADC_VCC
drv::adc_pooler_vcc< ADC_POOLER > servio::brd::ADC_VCC
CENTRAL_SENTRY
sntr::central_sentry servio::brd::CENTRAL_SENTRY
Initial value:
{
    CLOCK,
    INOPERABLE_RECORDS,
    DEGRADED_RECORDS,
    core::STOP_CALLBACK }
CLOCK
drv::clock servio::brd::CLOCK { TIM2_HANDLE }
COMMS
drv::cobs_uart servio::brd::COMMS { "comms", CENTRAL_SENTRY, CLOCK, &UART2_HANDLE, &UART2_DMA_HANDLE }
DEBUG_COMMS
drv::cobs_uart servio::brd::DEBUG_COMMS { "dcomms", CENTRAL_SENTRY, CLOCK, &UART1_HANDLE, &UART1_DMA_HANDLE }
DEGRADED_RECORDS
std::array< sntr::record, 128 > servio::brd::DEGRADED_RECORDS
DTS_DRV
drv::dts_temp servio::brd::DTS_DRV { DTS_HANDLE }
DTS_HANDLE
DTS_HandleTypeDef servio::brd::DTS_HANDLE {}
HBRDIGE_VREF_PIN
drv::pin_cfg servio::brd::HBRDIGE_VREF_PIN
Initial value:
{
    .pin  = GPIO_PIN_4,
    .port = GPIOA,
    .pull = GPIO_PULLDOWN,
}
HBRIDGE
drv::hbridge servio::brd::HBRIDGE { &TIM1_HANDLE }
INOPERABLE_RECORDS
std::array< sntr::record, 16 > servio::brd::INOPERABLE_RECORDS
LEDS
drv::leds servio::brd::LEDS { &TIM2_HANDLE }
PERSISTENT_BLOCKS
std::array< em::view< std::byte * >, 4 > servio::brd::PERSISTENT_BLOCKS { page_at(0), page_at(1) }
QUAD
drv::quad_encoder servio::brd::QUAD { TIM3_HANDLE }
QUAD_TRIGGER_TIMER
TIM_HandleTypeDef* servio::brd::QUAD_TRIGGER_TIMER = nullptr
TIM1_HANDLE
TIM_HandleTypeDef servio::brd::TIM1_HANDLE {}
TIM2_HANDLE
TIM_HandleTypeDef servio::brd::TIM2_HANDLE = {}
TIM3_HANDLE
TIM_HandleTypeDef servio::brd::TIM3_HANDLE {}
TIM6_HANDLE
TIM_HandleTypeDef servio::brd::TIM6_HANDLE
UART1_DMA_HANDLE
DMA_HandleTypeDef servio::brd::UART1_DMA_HANDLE {}
UART1_HANDLE
UART_HandleTypeDef servio::brd::UART1_HANDLE {}
UART2_DMA_HANDLE
DMA_HandleTypeDef servio::brd::UART2_DMA_HANDLE {}
UART2_HANDLE
UART_HandleTypeDef servio::brd::UART2_HANDLE {}