servio: brd Namespace Reference
brd Namespace Reference
Classes
struct adc_set
struct off_scale
struct setpoint
struct dma_cfg
struct pinch_cfg
struct adc_cfg
struct adc_timer_cfg
struct pin_cfg
struct uart_cfg
struct hb_timer_cfg
struct leds_gpio_cfg
struct leds_timer_cfg
struct clock_timer_cfg
Typedefs
using page = em::view< std::byte * >
An API that has to be implemented by each board variation.
Enumerations
enum chan_ids {
CURRENT_CHANNEL ,
POSITION_CHANNEL ,
VCC_CHANNEL ,
TEMP_CHANNEL
}
Functions
em::view< const page * > get_persistent_pages ()
Pages that shall be used for persistent configuration.
cfg::map get_default_config ()
Returns default configuration for servo for the board.
em::result setup_board ()
Initial setup call for the board.
core_drivers setup_core_drivers ()
Initialize all core drivers for the servo.
com_interface * setup_debug_comms ()
Initialize debug interface.
void setup_adc_channel (ADC_ChannelConfTypeDef &channel, pinch_cfg cfg)
em::result setup_adc (ADC_HandleTypeDef &adc, DMA_HandleTypeDef &dma, adc_cfg cfg)
em::result clock_setup (TIM_HandleTypeDef &tim, uint32_t &chan)
em::result adc_pooler_setup (ADC_HandleTypeDef &adc, DMA_HandleTypeDef &dma, TIM_HandleTypeDef &tim, uint32_t &tim_channel)
em::result hbridge_setup (fw::drv::hbridge::handles &h)
em::result comms_setup (fw::drv::cobs_uart::handles &h)
em::result debug_comms_setup (fw::drv::cobs_uart::handles &h)
em::result leds_setup (fw::drv::leds::handles &h)
em::result start_callback (core_drivers &cdrv)
microseconds get_clock_time ()
void setup_clk ()
constexpr off_scale calculate_current_conversion (float v_max, float v_min, float steps, float r_shunt, float gain)
off_scale calculate_temp_conversion ()
consteval cfg::map generate_config ()
em::view< std::byte * > page (uint32_t i)
em::result setup_leds_gpio (fw::drv::leds::handles &h, leds_gpio_cfg cfg)
em::result setup_adc_timer (TIM_HandleTypeDef &tim, uint32_t &tim_channel, adc_timer_cfg cfg)
em::result setup_uart (UART_HandleTypeDef &uart, DMA_HandleTypeDef &tx_dma, uart_cfg cfg)
em::result setup_hbridge_timers (fw::drv::hbridge::handles &, hb_timer_cfg cfg)
em::result setup_leds_timer (fw::drv::leds::handles &, leds_timer_cfg cfg)
em::result setup_clock_timer (TIM_HandleTypeDef &tim, uint32_t &channel, clock_timer_cfg cfg)
Variables
fw::drv::clock CLOCK {}
fw::drv::adc_pooler< adc_set > ADC_POOLER {}
fw::drv::cobs_uart COMMS {}
fw::drv::cobs_uart DEBUG_COMMS {}
fw::drv::hbridge HBRIDGE {}
fw::drv::leds LEDS
PERIOD_CB
VCC
TEMPERATURE
POSITION
CURRENT
auto ADC_SEQUENCE
std::array< em::view< std::byte * >, 4 > PERSISTENT_BLOCKS
Class Documentation
brd::off_scale
struct brd::off_scale
Class Members
float offset
float scale
brd::setpoint
struct brd::setpoint
Class Members
float angle
uint16_t value
brd::dma_cfg
struct brd::dma_cfg
Class Members
DMA_Channel_TypeDef * instance
IRQn_Type irq
uint32_t irq_priority
uint32_t priority
uint32_t request
brd::pinch_cfg
struct brd::pinch_cfg
Class Members
uint8_t alternate
uint32_t channel
uint32_t pin
GPIO_TypeDef * port
brd::adc_cfg
struct brd::adc_cfg
Class Members
ADC_TypeDef * adc_instance
uint32_t adc_irq_priority
dma_cfg dma
brd::adc_timer_cfg
struct brd::adc_timer_cfg
Class Members
uint32_t channel
TIM_TypeDef * timer_instance
brd::pin_cfg
struct brd::pin_cfg
Class Members
uint8_t alternate
uint16_t pin
GPIO_TypeDef * port
brd::uart_cfg
struct brd::uart_cfg
Class Members
uint32_t baudrate
IRQn_Type irq
uint32_t irq_priority
pin_cfg rx
pin_cfg tx
dma_cfg tx_dma
USART_TypeDef * uart_instance
brd::hb_timer_cfg
struct brd::hb_timer_cfg
Class Members
IRQn_Type irq
uint32_t irq_priority
pinch_cfg mc1
pinch_cfg mc2
uint16_t period
TIM_TypeDef * timer_instance
brd::leds_gpio_cfg
struct brd::leds_gpio_cfg
Class Members
pin_cfg blue
pin_cfg red
brd::leds_timer_cfg
struct brd::leds_timer_cfg
Class Members
pinch_cfg green
TIM_TypeDef * timer_instance
pinch_cfg yellow
brd::clock_timer_cfg
struct brd::clock_timer_cfg
Class Members
uint32_t channel
TIM_TypeDef * timer_instance
Typedef Documentation
page
using brd::page = typedef em::view< std::byte* >
An API that has to be implemented by each board variation.
Enumeration Type Documentation
chan_ids
enum brd::chan_ids
Enumerator
CURRENT_CHANNEL
POSITION_CHANNEL
VCC_CHANNEL
TEMP_CHANNEL
Function Documentation
adc_pooler_setup()
em::result brd::adc_pooler_setup (ADC_HandleTypeDef & adc, DMA_HandleTypeDef & dma, TIM_HandleTypeDef & tim, uint32_t & tim_channel)
References brd::adc_cfg::adc_instance, ADC_POOLER, brd::dma_cfg::instance, setup_adc(), setup_adc_channel(), setup_adc_timer(), and brd::adc_timer_cfg::timer_instance.
calculate_current_conversion()
constexpr off_scale brd::calculate_current_conversion (float v_max, float v_min, float steps, float r_shunt, float gain) constexpr
References brd::off_scale::offset.
calculate_temp_conversion()
off_scale brd::calculate_temp_conversion ()
References brd::off_scale::offset.
clock_setup()
em::result brd::clock_setup (TIM_HandleTypeDef & tim, uint32_t & chan)
References setup_clock_timer(), and brd::clock_timer_cfg::timer_instance.
comms_setup()
em::result brd::comms_setup (fw::drv::cobs_uart::handles & h)
References setup_uart(), brd::uart_cfg::tx, fw::drv::cobs_uart::handles::tx_dma, and fw::drv::cobs_uart::handles::uart.
debug_comms_setup()
em::result brd::debug_comms_setup (fw::drv::cobs_uart::handles & h)
References setup_uart(), brd::uart_cfg::tx, fw::drv::cobs_uart::handles::tx_dma, and fw::drv::cobs_uart::handles::uart.
generate_config()
consteval cfg::map brd::generate_config ()
References calculate_current_conversion(), cfg::CURRENT_CONV_OFFSET, cfg::CURRENT_CONV_SCALE, cfg::get_default_config(), brd::off_scale::offset, and brd::off_scale::scale.
get_clock_time()
microseconds brd::get_clock_time ()
References CLOCK, and fw::drv::clock::get_us().
get_default_config()
cfg::map brd::get_default_config ()
Returns default configuration for servo for the board.
References cfg::get_default_config().
get_persistent_pages()
em::view< const em::view< std::byte * > * > brd::get_persistent_pages ()
Pages that shall be used for persistent configuration.
hbridge_setup()
em::result brd::hbridge_setup (fw::drv::hbridge::handles & h)
References brd::pinch_cfg::channel, setup_hbridge_timers(), and brd::hb_timer_cfg::timer_instance.
leds_setup()
em::result brd::leds_setup (fw::drv::leds::handles & h)
References brd::pinch_cfg::channel, brd::pin_cfg::pin, brd::leds_gpio_cfg::red, setup_leds_gpio(), setup_leds_timer(), and brd::leds_timer_cfg::timer_instance.
page()
em::view< std::byte* > brd::page (uint32_t i)
References _config_start.
setup_adc()
em::result brd::setup_adc (ADC_HandleTypeDef & adc, DMA_HandleTypeDef & dma, adc_cfg cfg)
References fw::stop_exec().
setup_adc_channel()
void brd::setup_adc_channel (ADC_ChannelConfTypeDef & channel, pinch_cfg cfg)
setup_adc_timer()
em::result brd::setup_adc_timer (TIM_HandleTypeDef & tim, uint32_t & tim_channel, adc_timer_cfg cfg)
References fw::stop_exec().
setup_board()
em::result brd::setup_board ()
Initial setup call for the board.
setup_clk()
void brd::setup_clk ()
Configure the main internal regulator output voltage
Initializes the RCC Oscillators according to the specified parameters in the RCC_OscInitTypeDef structure.
Initializes the CPU, AHB and APB buses clocks
Initializes the peripherals clocks
Configures CRS
References fw::stop_exec().
setup_clock_timer()
em::result brd::setup_clock_timer (TIM_HandleTypeDef & tim, uint32_t & channel, clock_timer_cfg cfg)
References fw::stop_exec().
setup_core_drivers()
core_drivers brd::setup_core_drivers ()
Initialize all core drivers for the servo.
References core_drivers::start_cb.
setup_debug_comms()
com_interface * brd::setup_debug_comms ()
Initialize debug interface.
References DEBUG_COMMS, debug_comms_setup(), and fw::drv::cobs_uart::setup().
setup_hbridge_timers()
em::result brd::setup_hbridge_timers (fw::drv::hbridge::handles & h, hb_timer_cfg cfg)
References fw::drv::hbridge::handles::mc1_channel, fw::drv::hbridge::handles::mc2_channel, fw::stop_exec(), and fw::drv::hbridge::handles::timer.
setup_leds_gpio()
em::result brd::setup_leds_gpio (fw::drv::leds::handles & h, leds_gpio_cfg cfg)
References fw::drv::leds::handles::blue_peripheral, fw::drv::leds::handles::blue_pin, fw::drv::leds::handles::red_peripheral, and fw::drv::leds::handles::red_pin.
setup_leds_timer()
em::result brd::setup_leds_timer (fw::drv::leds::handles & h, leds_timer_cfg cfg)
References fw::drv::leds::handles::green_channel, fw::stop_exec(), fw::drv::leds::handles::tim, and fw::drv::leds::handles::yellow_channel.
setup_uart()
em::result brd::setup_uart (UART_HandleTypeDef & uart, DMA_HandleTypeDef & tx_dma, uart_cfg cfg)
References fw::stop_exec().
start_callback()
em::result brd::start_callback (core_drivers & cdrv)
References ADC_POOLER, COMMS, core_drivers::comms, HBRIDGE, LEDS, core_drivers::leds, core_drivers::motor, core_drivers::position, fw::drv::cobs_uart::start(), fw::drv::leds::start(), and fw::drv::hbridge::start().
Variable Documentation
ADC_POOLER
fw::drv::adc_pooler< adc_set > brd::ADC_POOLER {}
ADC_SEQUENCE
auto brd::ADC_SEQUENCE
Initial value:
= std::array{
    CURRENT_CHANNEL,
    POSITION_CHANNEL,
    CURRENT_CHANNEL,
    VCC_CHANNEL,
    CURRENT_CHANNEL,
    POSITION_CHANNEL,
    CURRENT_CHANNEL,
    TEMP_CHANNEL,
}
CLOCK
fw::drv::clock brd::CLOCK {}
COMMS
fw::drv::cobs_uart brd::COMMS {}
CURRENT
brd::CURRENT
DEBUG_COMMS
fw::drv::cobs_uart brd::DEBUG_COMMS {}
HBRIDGE
fw::drv::hbridge brd::HBRIDGE {}
LEDS
fw::drv::leds brd::LEDS
PERIOD_CB
brd::PERIOD_CB
PERSISTENT_BLOCKS
std::array< em::view< std::byte* >, 4 > brd::PERSISTENT_BLOCKS
Initial value:
{
    page( 0 ),
    page( 1 ),
    page( 2 ),
    page( 3 ) }
POSITION
brd::POSITION
TEMPERATURE
brd::TEMPERATURE
VCC
brd::VCC