servio: servio::scmdio Namespace Reference
servio::scmdio Namespace Reference
Classes
struct autotune_ctx
struct bflash_ctx
struct cfg_ctx
struct char_cli
struct char_port
struct cobs_cli
struct cobs_port
struct consumer
struct kval_ser
struct kval_ser< vari::typelist< KV, KVs... > >
struct kval_ser< vari::typelist<> >
struct line
struct mode_opts
struct pool_opts
struct port_cli
struct port_iface
struct port_mock
struct preset_def
struct raw_preset_def
struct serial_cli
struct serial_stream
struct servio_exception
struct stm32_bootloader_mock
struct stream_iface
struct val_ser
struct val_ser< avakar::atom< Ts... > >
Typedefs
template<typename T >
using sptr = std::shared_ptr< T >
template<typename T >
using opt = std::optional< T >
Functions
template<typename... Args>
void log_error (auto const &fmt, Args &&... args)
std::filesystem::path const & check_path (std::filesystem::path const &p)
awaitable< void > bflash_info (stream_iface &port, std::ostream &os)
awaitable< void > bflash_download (stream_iface &port, std::ostream &os)
awaitable< void > bflash_flash (stream_iface &port, std::istream &is)
awaitable< void > bflash_clear (stream_iface &port)
std::array< std::byte, 4 > bflash_conv (uint32_t x)
uint32_t bflash_conv (std::span< std::byte const, 4 > data)
CLI::Option * verbose_opt (CLI::App &app)
CLI::Option * coms_opt (CLI::App &app, std::filesystem::path &comms)
CLI::Option * dcoms_opt (CLI::App &app, std::filesystem::path &comms)
CLI::Option * baudrate_opt (CLI::App &app, unsigned &baudrate)
void port_opts (CLI::App &app, port_cli &cli)
awaitable< void > cfg_query_cmd (sptr< port_iface > port, bool json)
awaitable< void > cfg_commit_cmd (sptr< port_iface > port)
awaitable< void > cfg_clear_cmd (sptr< port_iface > port)
awaitable< void > cfg_get_cmd (sptr< port_iface > port, std::string const &name, bool json)
awaitable< void > cfg_set_cmd (sptr< port_iface > port, std::string const &name, std::string value)
awaitable< void > cfg_load_cmd (sptr< port_iface > port, std::filesystem::path const &cfg)
void json_flag (CLI::App *app, bool &flag)
void field_option (CLI::App *app, std::string &field)
void handle_eptr (std::exception_ptr eptr)
void port_callback (CLI::App *app, io_context &io_ctx, auto &ctx_ptr, auto f)
void cfg_def (CLI::App &app, io_context &io_ctx)
awaitable< void > pool_cmd (io_context &, sptr< char_port > port, std::vector< std::string > const &props)
void pool_def (CLI::App &app, io_context &io_ctx)
void mode_def (CLI::App &app, io_context &io_ctx)
void autotune_def (CLI::App &app, io_context &io_ctx)
void bflash_def (CLI::App &app, io_context &io_ctx)
line linear_least_squares (std::span< double > ys)
awaitable< std::vector< double > > pid_collect (float u, auto &&set_f, auto &&get_y_f)
void pid_calculate (std::span< double > buff)
awaitable< void > pid_autotune_current (port_iface &port, float pwr)
void flush_port (boost::asio::serial_port &p)
raw_preset_def load_raw_preset (std::filesystem::path const &folder)
preset_def load_preset (std::filesystem::path const &folder)
awaitable< void > write (port_iface &port, std::string_view payload)
awaitable< std::string > read (port_iface &port)
awaitable< nlohmann::json > exchg (port_iface &port, std::string const &msg)
awaitable< nlohmann::json > get_config_field (port_iface &port, std::string_view name)
awaitable< void > set_config_field (port_iface &port, std::string_view name, nlohmann::json const &value)
awaitable< std::map< std::string, nlohmann::json > > get_full_config (port_iface &port)
awaitable< nlohmann::json > get_property (port_iface &port, std::string_view prop)
awaitable< void > set_mode (port_iface &port, std::string_view mode, nlohmann::json const &arg)
TEST (autotune, lls_symm)
TEST (autotune, lls_off)
TEST (autotune, lls_linear)
TEST (autotune, lls_noise)
TEST (scmdio, info)
TEST (scmdio, reflash)
TEST (iface, base)
Variables
static constexpr std::byte ACK = 0x79_b
static constexpr std::byte NACK = 0x1F_b
static constexpr std::byte INIT = 0x7F_b
static constexpr std::byte GET = 0x00_b
static constexpr std::byte GET_ID = 0x02_b
static constexpr std::byte READ_MEMORY = 0x11_b
static constexpr std::byte WRITE_MEMORY = 0x31_b
static constexpr std::byte EXTENDED_ERASE = 0x44_b
Class Documentation
servio::scmdio::autotune_ctx
struct servio::scmdio::autotune_ctx
Class Members
char_cli port
servio::scmdio::bflash_ctx
struct servio::scmdio::bflash_ctx
Class Members
path file
serial_cli port
servio::scmdio::cfg_ctx
struct servio::scmdio::cfg_ctx
Class Members
string field
bool json = false
path path
char_cli port
string value
servio::scmdio::kval_ser
struct servio::scmdio::kval_ser
template<typename T>
struct servio::scmdio::kval_ser< T >
servio::scmdio::line
struct servio::scmdio::line
Class Members
double off
double scale
servio::scmdio::mode_opts
struct servio::scmdio::mode_opts
Class Members
float angle
float current
char_cli port
float power
float velocity
servio::scmdio::pool_opts
struct servio::scmdio::pool_opts
Class Members
vector< string > data
char_cli port
servio::scmdio::preset_def
struct servio::scmdio::preset_def
Class Members
string board
json config
string name
string platform
servio::scmdio::raw_preset_def
struct servio::scmdio::raw_preset_def
Class Members
json config
json meta
Typedef Documentation
opt
template<typename T > using servio::scmdio::opt = typedef std::optional< T >
sptr
template<typename T > using servio::scmdio::sptr = typedef std::shared_ptr< T >
Function Documentation
autotune_def()
void servio::scmdio::autotune_def (CLI::App & app, io_context & io_ctx)
References pid_autotune_current(), port_callback(), and port_opts().
baudrate_opt()
CLI::Option * servio::scmdio::baudrate_opt (CLI::App & app, unsigned & baudrate)
bflash_clear()
awaitable< void > servio::scmdio::bflash_clear (stream_iface & port)
References bflash_clear().
bflash_conv() [1/2]
uint32_t servio::scmdio::bflash_conv (std::span< std::byte const, 4 > data) inline
bflash_conv() [2/2]
std::array< std::byte, 4 > servio::scmdio::bflash_conv (uint32_t x) inline
bflash_def()
void servio::scmdio::bflash_def (CLI::App & app, io_context & io_ctx)
References bflash_clear(), bflash_download(), bflash_flash(), bflash_info(), port_callback(), and port_opts().
bflash_download()
awaitable< void > servio::scmdio::bflash_download (stream_iface & port, std::ostream & os)
References bflash_download().
bflash_flash()
awaitable< void > servio::scmdio::bflash_flash (stream_iface & port, std::istream & is)
References bflash_flash().
bflash_info()
awaitable< void > servio::scmdio::bflash_info (stream_iface & port, std::ostream & os)
References bflash_info().
cfg_clear_cmd()
awaitable< void > servio::scmdio::cfg_clear_cmd (sptr< port_iface > port)
References exchg().
cfg_commit_cmd()
awaitable< void > servio::scmdio::cfg_commit_cmd (sptr< port_iface > port)
References exchg().
cfg_def()
void servio::scmdio::cfg_def (CLI::App & app, io_context & io_ctx)
References cfg_clear_cmd(), cfg_commit_cmd(), cfg_get_cmd(), cfg_load_cmd(), cfg_query_cmd(), cfg_set_cmd(), field_option(), json_flag(), port_callback(), and port_opts().
cfg_get_cmd()
awaitable< void > servio::scmdio::cfg_get_cmd (sptr< port_iface > port, std::string const & name, bool json)
References get_config_field().
cfg_load_cmd()
awaitable< void > servio::scmdio::cfg_load_cmd (sptr< port_iface > port, std::filesystem::path const & cfg)
References cfg_set_cmd().
cfg_query_cmd()
awaitable< void > servio::scmdio::cfg_query_cmd (sptr< port_iface > port, bool json)
References get_full_config().
cfg_set_cmd()
awaitable< void > servio::scmdio::cfg_set_cmd (sptr< port_iface > port, std::string const & name, std::string value)
References set_config_field().
check_path()
std::filesystem::path const & servio::scmdio::check_path (std::filesystem::path const & p) inline
coms_opt()
CLI::Option * servio::scmdio::coms_opt (CLI::App & app, std::filesystem::path & comms)
dcoms_opt()
CLI::Option * servio::scmdio::dcoms_opt (CLI::App & app, std::filesystem::path & comms)
exchg()
awaitable< nlohmann::json > servio::scmdio::exchg (port_iface & port, std::string const & msg)
References log_error(), read(), and write().
field_option()
void servio::scmdio::field_option (CLI::App * app, std::string & field)
flush_port()
void servio::scmdio::flush_port (boost::asio::serial_port & p) inline
get_config_field()
awaitable< nlohmann::json > servio::scmdio::get_config_field (port_iface & port, std::string_view name)
References exchg(), and log_error().
get_full_config()
awaitable< std::map< std::string, nlohmann::json > > servio::scmdio::get_full_config (port_iface & port)
References get_config_field(), and servio::cfg::keys.
get_property()
awaitable< nlohmann::json > servio::scmdio::get_property (port_iface & port, std::string_view prop)
References exchg().
handle_eptr()
void servio::scmdio::handle_eptr (std::exception_ptr eptr) inline
json_flag()
void servio::scmdio::json_flag (CLI::App * app, bool & flag)
linear_least_squares()
line servio::scmdio::linear_least_squares (std::span< double > ys) inline
load_preset()
preset_def servio::scmdio::load_preset (std::filesystem::path const & folder)
References servio::scmdio::raw_preset_def::config, load_raw_preset(), servio::scmdio::raw_preset_def::meta, and servio::scmdio::preset_def::name.
load_raw_preset()
raw_preset_def servio::scmdio::load_raw_preset (std::filesystem::path const & folder)
References servio::scmdio::raw_preset_def::config, load_raw_preset(), and servio::scmdio::raw_preset_def::meta.
log_error()
template<typename... Args> void servio::scmdio::log_error (auto const & fmt, Args &&... args) inline
mode_def()
void servio::scmdio::mode_def (CLI::App & app, io_context & io_ctx)
References port_callback(), port_opts(), and set_mode().
pid_autotune_current()
awaitable< void > servio::scmdio::pid_autotune_current (port_iface & port, float pwr)
References get_property(), pid_collect(), and set_mode().
pid_calculate()
void servio::scmdio::pid_calculate (std::span< double > buff) inline
References linear_least_squares(), servio::scmdio::line::off, and servio::scmdio::line::scale.
pid_collect()
awaitable< std::vector< double > > servio::scmdio::pid_collect (float u, auto && set_f, auto && get_y_f)
pool_cmd()
awaitable< void > servio::scmdio::pool_cmd (io_context & , sptr< char_port > port, std::vector< std::string > const & props)
References get_property().
pool_def()
void servio::scmdio::pool_def (CLI::App & app, io_context & io_ctx)
References pool_cmd(), port_callback(), and port_opts().
port_callback()
void servio::scmdio::port_callback (CLI::App * app, io_context & io_ctx, auto & ctx_ptr, auto f)
References handle_eptr().
port_opts()
void servio::scmdio::port_opts (CLI::App & app, port_cli & cli)
References servio::scmdio::port_cli::baudrate, baudrate_opt(), coms_opt(), and servio::scmdio::port_cli::device.
read()
awaitable< std::string > servio::scmdio::read (port_iface & port)
References servio::scmdio::port_iface::read_msg().
set_config_field()
awaitable< void > servio::scmdio::set_config_field (port_iface & port, std::string_view name, nlohmann::json const & value)
References exchg().
set_mode()
awaitable< void > servio::scmdio::set_mode (port_iface & port, std::string_view mode, nlohmann::json const & arg)
References exchg().
TEST() [1/7]
servio::scmdio::TEST (autotune , lls_linear)
References linear_least_squares(), servio::scmdio::line::off, and servio::scmdio::line::scale.
TEST() [2/7]
servio::scmdio::TEST (autotune , lls_noise)
References linear_least_squares(), servio::scmdio::line::off, and servio::scmdio::line::scale.
TEST() [3/7]
servio::scmdio::TEST (autotune , lls_off)
References linear_least_squares(), servio::scmdio::line::off, and servio::scmdio::line::scale.
TEST() [4/7]
servio::scmdio::TEST (autotune , lls_symm)
References linear_least_squares(), servio::scmdio::line::off, and servio::scmdio::line::scale.
TEST() [5/7]
servio::scmdio::TEST (iface , base)
References servio::cfg::encoder_mode, get_config_field(), get_full_config(), get_property(), servio::cfg::group_id, handle_eptr(), servio::cfg::id, servio::cfg::invert_hbridge, servio::cfg::keys, servio::cfg::model, servio::scmdio::port_mock::attrs::motor, servio::ctl::config::position_limits, servio::iface::property_values, servio::cfg::quad_encoder_range, set_config_field(), and set_mode().
TEST() [6/7]
servio::scmdio::TEST (scmdio , info)
References bflash_info(), and handle_eptr().
TEST() [7/7]
servio::scmdio::TEST (scmdio , reflash)
verbose_opt()
CLI::Option * servio::scmdio::verbose_opt (CLI::App & app)
write()
awaitable< void > servio::scmdio::write (port_iface & port, std::string_view payload)
References servio::scmdio::port_iface::write_msg().
Variable Documentation
ACK
constexpr std::byte servio::scmdio::ACK = 0x79_b static constexpr
EXTENDED_ERASE
constexpr std::byte servio::scmdio::EXTENDED_ERASE = 0x44_b static constexpr
GET
constexpr std::byte servio::scmdio::GET = 0x00_b static constexpr
GET_ID
constexpr std::byte servio::scmdio::GET_ID = 0x02_b static constexpr
INIT
constexpr std::byte servio::scmdio::INIT = 0x7F_b static constexpr
NACK
constexpr std::byte servio::scmdio::NACK = 0x1F_b static constexpr
READ_MEMORY
constexpr std::byte servio::scmdio::READ_MEMORY = 0x11_b static constexpr
WRITE_MEMORY
constexpr std::byte servio::scmdio::WRITE_MEMORY = 0x31_b static constexpr