servio: servio::core::tests Namespace Reference
servio::core::tests Namespace Reference
Functions
TEST (core, dispatcher)
Function Documentation
TEST()
servio::core::tests::TEST (core , dispatcher)
References servio::drv::mock::stor::clear_cnt, servio::DISENGAGED, servio::cfg::encoder_mode_to_str(), servio::core::handle_message(), servio::core::dispatcher::motor, servio::ctl::config::position_limits, servio::drv::mock::stor::store_cnt, servio::cfg::str_to_key(), servio::SUCCESS, servio::drv::mock::pos::x, servio::drv::mock::curr::x, servio::drv::mock::vcc::x, and servio::drv::mock::temp::x.