servio: servio::iface Namespace Reference
servio::iface Namespace Reference
Namespaces
namespace literals
Classes
struct cfg_clear_stmt
struct cfg_commit_stmt
struct cfg_get_stmt
struct cfg_set_stmt
struct field
struct field< IDX, Key, void >
struct field_traits
struct field_traits< vari::typelist< Field... > >
struct field_tuple
struct field_tuple< vari::typelist< Ts... > >
struct group
struct info_stmt
struct invalid_stmt
struct key_filter
struct key_filter< K, vari::typelist< F, Fs... > >
struct kval
struct kval< Key, void >
struct mode_stmt
struct prop_stmt
struct resp
Typedefs
template<typename T >
using opt = std::optional< T >
template<typename T >
using field_tuple_t = typename field_tuple< T >::type
using mode = vari::typelist< field< 1, "disengaged"_a, void >, field< 2, "power"_a, float >, field< 3, "current"_a, float >, field< 4, "velocity"_a, float >, field< 5, "position"_a, float > >
using mode_traits = field_traits< mode >
using mode_types = typename mode_traits::types
using mode_vals = typename mode_traits::vals
using mode_key = typename mode_traits::keys
using property = vari::typelist< field< 1, "mode"_a, mode_key >, field< 2, "current"_a, float >, field< 3, "vcc"_a, float >, field< 4, "temp"_a, float >, field< 5, "position"_a, float >, field< 6, "velocity"_a, float > >
using prop_traits = field_traits< property >
using prop_types = prop_traits::types
using prop_vals = prop_traits::vals
using prop_key = prop_traits::keys
using encoder_mode = vari::typelist< field< 1, "analog"_a, void >, field< 2, "quad"_a, void > >
using ec_mode_key = typename field_traits< encoder_mode >::keys
using cfg = vari::typelist< field< 1, "model"_a, std::string_view >, field< 2, "id"_a, uint32_t >, field< 3, "group_id"_a, uint32_t >, field< 4, "encoder_mode"_a, ec_mode_key >, field< 11, "position_lower_angle"_a, float >, field< 12, "position_higher_angle"_a, float >, field< 14, "current_conv_scale"_a, float >, field< 15, "current_conv_offset"_a, float >, field< 16, "temp_conv_scale"_a, float >, field< 17, "temp_conv_offset"_a, float >, field< 18, "voltage_conv_scale"_a, float >, field< 19, "invert_hbridge"_a, bool >, field< 30, "current_loop_p"_a, float >, field< 31, "current_loop_i"_a, float >, field< 32, "current_loop_d"_a, float >, field< 33, "current_lim_min"_a, float >, field< 34, "current_lim_max"_a, float >, field< 40, "velocity_loop_p"_a, float >, field< 41, "velocity_loop_i"_a, float >, field< 42, "velocity_loop_d"_a, float >, field< 43, "velocity_lim_min"_a, float >, field< 44, "velocity_lim_max"_a, float >, field< 45, "velocity_to_current_lim_scale"_a, float >, field< 50, "position_loop_p"_a, float >, field< 51, "position_loop_i"_a, float >, field< 52, "position_loop_d"_a, float >, field< 53, "position_lim_min"_a, float >, field< 54, "position_lim_max"_a, float >, field< 55, "position_to_velocity_lim_scale"_a, float >, field< 60, "static_friction_scale"_a, float >, field< 61, "static_friction_decay"_a, float >, field< 62, "moving_detection_step"_a, float >, field< 65, "minimum_voltage"_a, float >, field< 66, "maximum_temperature"_a, float >, field< 80, "quad_encoder_range"_a, uint32_t > >
using cfg_traits = field_traits< cfg >
using cfg_types = typename cfg_traits::types
using cfg_vals = typename cfg_traits::vals
using cfg_key = typename cfg_traits::keys
using stmt = vari::typelist< mode_stmt, prop_stmt, cfg_set_stmt, cfg_get_stmt, cfg_commit_stmt, cfg_clear_stmt, info_stmt >
using num = int32_t
using real = float
Functions
template<auto Key, typename T >
constexpr kval< Key, T > operator| (T val, kval< Key, void >) noexcept
vari::vval< stmt, invalid_stmt > parse (std::string_view inpt)
template<auto A>
auto kv (auto x)
template<auto A>
auto kv ()
TEST (iface, valid_parse)
TEST (iface, invalid_parse)
TEST (iface, numreal)
TEST (iface, str)
constexpr bool _is_letter (char c) noexcept
constexpr bool _is_dec (char c) noexcept
constexpr bool _is_hex (char c) noexcept
constexpr bool _is_ws (char c) noexcept
constexpr bool _is_id_letter (char c) noexcept
vari::vopt< num > hex_numeric (char const *&p, char const *e)
vari::vopt< num > dec_digits (char const *&p, char const *e)
vari::vopt< num > dec_numeric (char const *&p, char const *e)
constexpr bool hex_prefix (char const *p, char const *e)
vari::vopt< num, real > numreal (char const *&p, char const *e)
constexpr bool lex_id (char const *&p, char const *e) noexcept
vari::vopt< std::string_view > parse_str (char const *&p, char const *e) noexcept
Class Documentation
servio::iface::field_traits
struct servio::iface::field_traits
template<typename Cfg>
struct servio::iface::field_traits< Cfg >
servio::iface::field_tuple
struct servio::iface::field_tuple
template<typename T>
struct servio::iface::field_tuple< T >
servio::iface::field_tuple< vari::typelist< Ts... > >
struct servio::iface::field_tuple< vari::typelist< Ts... > >
template<typename... Ts>
struct servio::iface::field_tuple< vari::typelist< Ts... > >
Class Members
typedef tuple< Ts... > type
servio::iface::group
struct servio::iface::group
template<avakar::s Desc, typename... Ts>
struct servio::iface::group< Desc, Ts >
Class Members
typedef typelist< Ts... > value_type
servio::iface::key_filter
struct servio::iface::key_filter
template<auto K, typename T>
struct servio::iface::key_filter< K, T >
servio::iface::resp
struct servio::iface::resp
Class Members
string_buffer< 64 > res
Typedef Documentation
cfg
using servio::iface::cfg = typedef vari::typelist< field< 1, "model"_a, std::string_view >, field< 2, "id"_a, uint32_t >, field< 3, "group_id"_a, uint32_t >, field< 4, "encoder_mode"_a, ec_mode_key >, field< 11, "position_lower_angle"_a, float >, field< 12, "position_higher_angle"_a, float >, field< 14, "current_conv_scale"_a, float >, field< 15, "current_conv_offset"_a, float >, field< 16, "temp_conv_scale"_a, float >, field< 17, "temp_conv_offset"_a, float >, field< 18, "voltage_conv_scale"_a, float >, field< 19, "invert_hbridge"_a, bool >, field< 30, "current_loop_p"_a, float >, field< 31, "current_loop_i"_a, float >, field< 32, "current_loop_d"_a, float >, field< 33, "current_lim_min"_a, float >, field< 34, "current_lim_max"_a, float >, field< 40, "velocity_loop_p"_a, float >, field< 41, "velocity_loop_i"_a, float >, field< 42, "velocity_loop_d"_a, float >, field< 43, "velocity_lim_min"_a, float >, field< 44, "velocity_lim_max"_a, float >, field< 45, "velocity_to_current_lim_scale"_a, float >, field< 50, "position_loop_p"_a, float >, field< 51, "position_loop_i"_a, float >, field< 52, "position_loop_d"_a, float >, field< 53, "position_lim_min"_a, float >, field< 54, "position_lim_max"_a, float >, field< 55, "position_to_velocity_lim_scale"_a, float >, field< 60, "static_friction_scale"_a, float >, field< 61, "static_friction_decay"_a, float >, field< 62, "moving_detection_step"_a, float >, field< 65, "minimum_voltage"_a, float >, field< 66, "maximum_temperature"_a, float >, field< 80, "quad_encoder_range"_a, uint32_t > >
cfg_key
using servio::iface::cfg_key = typedef typename cfg_traits::keys
cfg_traits
using servio::iface::cfg_traits = typedef field_traits< cfg >
cfg_types
using servio::iface::cfg_types = typedef typename cfg_traits::types
cfg_vals
using servio::iface::cfg_vals = typedef typename cfg_traits::vals
ec_mode_key
using servio::iface::ec_mode_key = typedef typename field_traits< encoder_mode >::keys
encoder_mode
using servio::iface::encoder_mode = typedef vari::typelist< field< 1, "analog"_a, void >, field< 2, "quad"_a, void > >
field_tuple_t
template<typename T > using servio::iface::field_tuple_t = typedef typename field_tuple< T >::type
mode
using servio::iface::mode = typedef vari::typelist< field< 1, "disengaged"_a, void >, field< 2, "power"_a, float >, field< 3, "current"_a, float >, field< 4, "velocity"_a, float >, field< 5, "position"_a, float > >
mode_key
using servio::iface::mode_key = typedef typename mode_traits::keys
mode_traits
using servio::iface::mode_traits = typedef field_traits< mode >
mode_types
using servio::iface::mode_types = typedef typename mode_traits::types
mode_vals
using servio::iface::mode_vals = typedef typename mode_traits::vals
num
using servio::iface::num = typedef int32_t
opt
template<typename T > using servio::iface::opt = typedef std::optional< T >
prop_key
using servio::iface::prop_key = typedef prop_traits::keys
prop_traits
using servio::iface::prop_traits = typedef field_traits< property >
prop_types
using servio::iface::prop_types = typedef prop_traits::types
prop_vals
using servio::iface::prop_vals = typedef prop_traits::vals
property
using servio::iface::property = typedef vari::typelist< field< 1, "mode"_a, mode_key >, field< 2, "current"_a, float >, field< 3, "vcc"_a, float >, field< 4, "temp"_a, float >, field< 5, "position"_a, float >, field< 6, "velocity"_a, float > >
real
using servio::iface::real = typedef float
stmt
using servio::iface::stmt = typedef vari::typelist< mode_stmt, prop_stmt, cfg_set_stmt, cfg_get_stmt, cfg_commit_stmt, cfg_clear_stmt, info_stmt >
Function Documentation
_is_dec()
constexpr bool servio::iface::_is_dec (char c) constexpr noexcept
_is_hex()
constexpr bool servio::iface::_is_hex (char c) constexpr noexcept
References _is_dec().
_is_id_letter()
constexpr bool servio::iface::_is_id_letter (char c) constexpr noexcept
References _is_dec(), and _is_letter().
_is_letter()
constexpr bool servio::iface::_is_letter (char c) constexpr noexcept
_is_ws()
constexpr bool servio::iface::_is_ws (char c) constexpr noexcept
dec_digits()
vari::vopt< num > servio::iface::dec_digits (char const *& p, char const * e) inline
References _is_dec(), and SERVIO_NUM_ASSERT.
dec_numeric()
vari::vopt< num > servio::iface::dec_numeric (char const *& p, char const * e) inline
References _is_dec(), dec_digits(), and SERVIO_NUM_ASSERT.
hex_numeric()
vari::vopt< num > servio::iface::hex_numeric (char const *& p, char const * e) inline
References _is_hex(), and SERVIO_NUM_ASSERT.
hex_prefix()
constexpr bool servio::iface::hex_prefix (char const * p, char const * e) constexpr
References SERVIO_NUM_ASSERT.
kv() [1/2]
template<auto A> auto servio::iface::kv ()
kv() [2/2]
template<auto A> auto servio::iface::kv (auto x)
References servio::iface::kval< Key, T >::value.
lex_id()
constexpr bool servio::iface::lex_id (char const *& p, char const * e) constexpr noexcept
References _is_id_letter(), and _is_letter().
numreal()
vari::vopt< num, real > servio::iface::numreal (char const *& p, char const * e) inline
References _is_dec(), dec_numeric(), hex_numeric(), hex_prefix(), and SERVIO_NUM_ASSERT.
operator|()
template<auto Key, typename T > constexpr kval< Key, T > servio::iface::operator| (T val, kval< Key, void >) constexpr noexcept
parse()
vari::vval< stmt, invalid_stmt > servio::iface::parse (std::string_view inpt)
parse_str()
vari::vopt< std::string_view > servio::iface::parse_str (char const *& p, char const * e) inline noexcept
References _is_id_letter().
TEST() [1/4]
servio::iface::TEST (iface , invalid_parse)
References parse().
TEST() [2/4]
servio::iface::TEST (iface , numreal)
References numreal().
TEST() [3/4]
servio::iface::TEST (iface , str)
References parse_str().
TEST() [4/4]
servio::iface::TEST (iface , valid_parse)
References servio::iface::cfg_get_stmt::k, kv(), parse(), and servio::iface::cfg_set_stmt::val.