servio: boards/prototype2/board.cpp File Reference
board.cpp File Reference
#include "brd.hpp"
#include "core_drivers.hpp"
#include "emlabcpp/result.h"
#include "fw/drv/adc_pooler.hpp"
#include "fw/drv/clock.hpp"
#include "fw/drv/cobs_uart.hpp"
#include "fw/util.hpp"
#include "setup.hpp"
Classes
struct brd::adc_set
Namespaces
brd
Enumerations
enum brd::chan_ids {
brd::CURRENT_CHANNEL ,
brd::POSITION_CHANNEL ,
brd::VCC_CHANNEL ,
brd::TEMP_CHANNEL ,
brd::CURRENT_CHANNEL ,
brd::POSITION_CHANNEL ,
brd::VCC_CHANNEL ,
brd::TEMP_CHANNEL
}
Functions
void TIM1_UP_TIM16_IRQHandler ()
void USART2_IRQHandler (void)
void DMA1_Channel4_IRQHandler (void)
void USART1_IRQHandler (void)
void DMA1_Channel5_IRQHandler (void)
void DMA1_Channel1_IRQHandler ()
void ADC1_2_IRQHandler ()
void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef *h)
void HAL_UART_TxCpltCallback (UART_HandleTypeDef *h)
void HAL_UART_RxCpltCallback (UART_HandleTypeDef *h)
void HAL_ADC_ConvCpltCallback (ADC_HandleTypeDef *h)
void HAL_ADC_ErrorCallback (ADC_HandleTypeDef *h)
em::result brd::setup_board ()
Initial setup call for the board.
em::result brd::clock_setup (TIM_HandleTypeDef &tim, uint32_t &chan)
em::result brd::adc_pooler_setup (ADC_HandleTypeDef &adc, DMA_HandleTypeDef &dma, TIM_HandleTypeDef &tim, uint32_t &tim_channel)
em::result brd::hbridge_setup (fw::drv::hbridge::handles &h)
em::result brd::comms_setup (fw::drv::cobs_uart::handles &h)
em::result brd::debug_comms_setup (fw::drv::cobs_uart::handles &h)
com_interface * brd::setup_debug_comms ()
Initialize debug interface.
em::result brd::leds_setup (fw::drv::leds::handles &h)
em::result brd::start_callback (core_drivers &cdrv)
microseconds brd::get_clock_time ()
core_drivers brd::setup_core_drivers ()
Initialize all core drivers for the servo.
Variables
brd::PERIOD_CB
brd::VCC
brd::TEMPERATURE
brd::POSITION
brd::CURRENT
auto brd::ADC_SEQUENCE
Function Documentation
ADC1_2_IRQHandler()
void ADC1_2_IRQHandler ()
References brd::ADC_POOLER.
DMA1_Channel1_IRQHandler()
void DMA1_Channel1_IRQHandler ()
References brd::ADC_POOLER.
DMA1_Channel4_IRQHandler()
void DMA1_Channel4_IRQHandler (void)
References brd::COMMS, and fw::drv::cobs_uart::tx_dma_irq().
DMA1_Channel5_IRQHandler()
void DMA1_Channel5_IRQHandler (void)
References brd::DEBUG_COMMS, and fw::drv::cobs_uart::tx_dma_irq().
HAL_ADC_ConvCpltCallback()
void HAL_ADC_ConvCpltCallback (ADC_HandleTypeDef * h)
References brd::ADC_POOLER.
HAL_ADC_ErrorCallback()
void HAL_ADC_ErrorCallback (ADC_HandleTypeDef * h)
References brd::ADC_POOLER.
HAL_TIM_PeriodElapsedCallback()
void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef * h)
References brd::HBRIDGE, and fw::drv::hbridge::timer_period_irq().
HAL_UART_RxCpltCallback()
void HAL_UART_RxCpltCallback (UART_HandleTypeDef * h)
References brd::COMMS, brd::DEBUG_COMMS, and fw::drv::cobs_uart::rx_cplt_irq().
HAL_UART_TxCpltCallback()
void HAL_UART_TxCpltCallback (UART_HandleTypeDef * h)
References brd::COMMS, brd::DEBUG_COMMS, and fw::drv::cobs_uart::tx_cplt_irq().
TIM1_UP_TIM16_IRQHandler()
void TIM1_UP_TIM16_IRQHandler ()
References brd::HBRIDGE, and fw::drv::hbridge::timer_irq().
USART1_IRQHandler()
void USART1_IRQHandler (void)
References brd::DEBUG_COMMS, and fw::drv::cobs_uart::uart_irq().
USART2_IRQHandler()
void USART2_IRQHandler (void)
References brd::COMMS, and fw::drv::cobs_uart::uart_irq().