servio: src/scmdio/main.cpp File Reference
main.cpp File Reference
#include "io.pb.h"
#include "scmdio/cli.hpp"
#include "scmdio/config_cmds.hpp"
#include "scmdio/serial.hpp"
#include <emlabcpp/algorithm.h>
#include <filesystem>
Classes
struct servio::scmdio::cfg_opts
struct servio::scmdio::mode_opts
Namespaces
servio
servio::scmdio
Functions
void servio::scmdio::json_flag (CLI::App *app, bool &flag)
void servio::scmdio::field_option (CLI::App *app, std::string &field)
void servio::scmdio::cfg_def (CLI::App &app, boost::asio::io_context &context, std::unique_ptr< cobs_port > &port_ptr)
boost::asio::awaitable< void > servio::scmdio::pool_cmd (boost::asio::io_context &, cobs_port &port, std::vector< const google::protobuf::FieldDescriptor * > fields)
boost::asio::awaitable< void > servio::scmdio::pool_cmd (boost::asio::io_context &context, cobs_port &port, std::vector< std::string > properties)
void servio::scmdio::pool_def (CLI::App &app, boost::asio::io_context &context, std::unique_ptr< cobs_port > &port_ptr)
void servio::scmdio::mode_def (CLI::App &app, boost::asio::io_context &context, std::unique_ptr< cobs_port > &port_ptr)
int main (int argc, char *argv[])
Class Documentation
servio::scmdio::cfg_opts
struct servio::scmdio::cfg_opts
Class Members
string field
bool json
string value
servio::scmdio::mode_opts
struct servio::scmdio::mode_opts
Class Members
float angle
float current
float velocity
Function Documentation
main()
int main (int argc, char * argv[])
References servio::scmdio::cfg_def(), servio::scmdio::common_cli::context, servio::scmdio::mode_def(), servio::scmdio::pool_def(), servio::scmdio::common_cli::port_ptr, and servio::scmdio::common_cli::setup().