servio: cfg_dispatcher Struct Reference
cfg_dispatcher Struct Reference
#include <cfg_dispatcher.hpp>
Public Member Functions
template<cfg::key Key, typename T >
void set (const T &item)
void full_apply ()
void apply (const cfg::key &key)
Public Attributes
cfg::map & map
core & c
Member Function Documentation
apply()
void cfg_dispatcher::apply (const cfg::key & key)
References c, core::conv, core::ctl, CURRENT, cfg::CURRENT_CONV_OFFSET, cfg::CURRENT_CONV_SCALE, cfg::CURRENT_LIM_MAX, cfg::CURRENT_LIM_MIN, cfg::CURRENT_LOOP_D, cfg::CURRENT_LOOP_I, cfg::CURRENT_LOOP_P, cfg::GROUP_ID, cfg::ID, map, cfg::MAXIMUM_TEMPERATURE, core::met, cfg::MINIMUM_VOLTAGE, cfg::MODEL, core::mon, cfg::MOVING_DETECTION_STEP, POSITION, cfg::POSITION_CONV_HIGHER_SETPOINT_ANGLE, cfg::POSITION_CONV_HIGHER_SETPOINT_VALUE, cfg::POSITION_CONV_LOWER_SETPOINT_ANGLE, cfg::POSITION_CONV_LOWER_SETPOINT_VALUE, cfg::POSITION_LIM_MAX, cfg::POSITION_LIM_MIN, cfg::POSITION_LOOP_D, cfg::POSITION_LOOP_I, cfg::POSITION_LOOP_P, converter::set_current_cfg(), control::set_limits(), monitor::set_maximum_temperature(), monitor::set_minimum_voltage(), metrics::set_moving_step(), control::set_pid(), converter::set_position_cfg(), metrics::set_position_range(), control::set_static_friction(), converter::set_temp_cfg(), converter::set_vcc_cfg(), cfg::STATIC_FRICTION_DECAY, cfg::STATIC_FRICTION_SCALE, cfg::TEMP_CONV_OFFSET, cfg::TEMP_CONV_SCALE, VELOCITY, cfg::VELOCITY_LIM_MAX, cfg::VELOCITY_LIM_MIN, cfg::VELOCITY_LOOP_D, cfg::VELOCITY_LOOP_I, cfg::VELOCITY_LOOP_P, and cfg::VOLTAGE_CONV_SCALE.
full_apply()
void cfg_dispatcher::full_apply ()
References apply().
set()
template<cfg::key Key, typename T > void cfg_dispatcher::set (const T & item) inline
References apply(), and map.
Member Data Documentation
c
core& cfg_dispatcher::c
map
cfg::map& cfg_dispatcher::map
The documentation for this struct was generated from the following files:
src/cfg_dispatcher.hpp
src/cfg_dispatcher.cpp