servio: servio::ftest::bench::profile Struct Reference
servio::ftest::bench::profile Struct Reference
#include <benchmarks.hpp>
Public Member Functions
t::coroutine< void > run (auto &mem, uctx &ctx)
Public Attributes
drv::clk_iface & clk
drv::curr_iface & curr
core::core & cor
std::string_view name = "current_profile"
Member Function Documentation
run()
t::coroutine< void > servio::ftest::bench::profile::run (auto & mem, uctx & ctx) inline
References clk, cor, servio::ftest::bench::prof_record::count, servio::core::core::ctl, curr, servio::ftest::uctx::expect(), servio::drv::curr_iface::get_current_callback(), servio::drv::clk_iface::get_us(), servio::ftest::bench::prof_record::max, servio::ftest::bench::prof_record::min, servio::drv::adc_detailed_cb< Callable >::on_value_irq(), servio::ftest::bench::PROF_BUFFER, servio::ftest::uctx::record, servio::drv::retain_callback(), servio::drv::curr_iface::set_current_callback(), servio::ftest::setup_poweroff(), servio::ftest::store_metric(), servio::ftest::bench::prof_record::sum, and servio::ctl::control::switch_to_power_control().
Member Data Documentation
clk
drv::clk_iface& servio::ftest::bench::profile::clk
cor
core::core& servio::ftest::bench::profile::cor
curr
drv::curr_iface& servio::ftest::bench::profile::curr
name
std::string_view servio::ftest::bench::profile::name = "current_profile"
The documentation for this struct was generated from the following file:
src/ftest/bench/benchmarks.hpp