servio: fw::persistent_config_writer Struct Reference
fw::persistent_config_writer Struct Reference
#include <store_persistent_config.hpp>
Public Member Functions
bool operator() (const cfg::map *cfg)
Public Attributes
cfg::payload & last_payload
em::view< const cfg::page * > pages
current_interface & current_iface
Member Function Documentation
operator()()
bool fw::persistent_config_writer::operator() (const cfg::map * cfg)
References driver_interface::clear_status(), current_iface, DEGRADED, cfg::find_next_page(), driver_interface::get_status(), cfg::payload::git_ver, cfg::payload::id, last_payload, pages, and fw::store_persistent_config().
Member Data Documentation
current_iface
current_interface& fw::persistent_config_writer::current_iface
last_payload
cfg::payload& fw::persistent_config_writer::last_payload
pages
em::view< const cfg::page* > fw::persistent_config_writer::pages
The documentation for this struct was generated from the following files:
src/fw/store_persistent_config.hpp
src/fw/store_persistent_config.cpp