servio: servio::drv::tests::period_iface_test Struct Reference
servio::drv::tests::period_iface_test Struct Reference
#include <interface_tests.hpp>
Public Member Functions
t::coroutine< void > run (auto &mem, ftest::uctx &ctx)
Public Attributes
clk_iface & clk
period_iface & iface
std::string_view name = "period_iface"
Member Function Documentation
run()
t::coroutine< void > servio::drv::tests::period_iface_test::run (auto & mem, ftest::uctx & ctx) inline
References servio::ftest::uctx::coll, servio::ftest::uctx::expect(), servio::drv::period_iface::get_period_callback(), servio::drv::retain_callback(), servio::drv::period_iface::set_period_callback(), servio::drv::period_iface::start(), servio::drv::period_iface::stop(), servio::ftest::store_metric(), and servio::drv::wait_for().
Member Data Documentation
clk
clk_iface& servio::drv::tests::period_iface_test::clk
iface
period_iface& servio::drv::tests::period_iface_test::iface
name
std::string_view servio::drv::tests::period_iface_test::name = "period_iface"
The documentation for this struct was generated from the following file:
src/drv/tests/interface_tests.hpp