servio: servio::mtr::posvel_kalman Struct Reference
servio::mtr::posvel_kalman Struct Reference
#include <posvel_kalman.hpp>
Public Member Functions
posvel_kalman (float position, limits< float > position_range)
void set_position_range (limits< float > position_range)
float get_position () const
float get_velocity () const
void update (sec_time sdiff, float position)
Public Attributes
float angle {}
kalman::state_range st_range = { .offset = 0.F, .size = 0.F }
kalman::state x {}
kalman::state_covariance P {}
float offset = 0.F
Static Public Attributes
static constexpr float observation_deviation = 0.000005F
static constexpr float process_deviation = 0.005F
static constexpr kalman::observation_model h = kalman::get_observation_model()
static constexpr kalman::observation_noise_covariance r
Constructor & Destructor Documentation
posvel_kalman()
servio::mtr::posvel_kalman::posvel_kalman (float position, limits< float > position_range) inline
References servio::kalman::angle(), servio::kalman::angle_mod(), servio::cnv::position(), set_position_range(), st_range, and x.
Member Function Documentation
get_position()
float servio::mtr::posvel_kalman::get_position () const inline
References angle.
get_velocity()
float servio::mtr::posvel_kalman::get_velocity () const inline
References servio::kalman::velocity(), and x.
set_position_range()
void servio::mtr::posvel_kalman::set_position_range (limits< float > position_range) inline
References servio::kalman::state_range::offset, servio::kalman::state_range::size, and st_range.
update()
void servio::mtr::posvel_kalman::update (sec_time sdiff, float position) inline
References servio::kalman::angle(), angle, servio::kalman::angle_mod(), servio::kalman::get_control_input_model(), servio::kalman::get_process_noise_covariance(), servio::kalman::get_transition_model(), h, servio::kalman::modify_angle(), offset, P, servio::pi, servio::cnv::position(), servio::kalman::predict(), process_deviation, r, servio::kalman::requires_offset(), st_range, servio::kalman::update(), and x.
Member Data Documentation
angle
float servio::mtr::posvel_kalman::angle {}
h
constexpr kalman::observation_model servio::mtr::posvel_kalman::h = kalman::get_observation_model() static constexpr
observation_deviation
constexpr float servio::mtr::posvel_kalman::observation_deviation = 0.000005F static constexpr
offset
float servio::mtr::posvel_kalman::offset = 0.F
P
kalman::state_covariance servio::mtr::posvel_kalman::P {}
process_deviation
constexpr float servio::mtr::posvel_kalman::process_deviation = 0.005F static constexpr
r
constexpr kalman::observation_noise_covariance servio::mtr::posvel_kalman::r static constexpr
Initial value:
=
            kalman::get_observation_noise_covariance( observation_deviation )
st_range
kalman::state_range servio::mtr::posvel_kalman::st_range = { .offset = 0.F, .size = 0.F }
x
kalman::state servio::mtr::posvel_kalman::x {}
The documentation for this struct was generated from the following file:
src/mtr/posvel_kalman.hpp