servio: core Struct Reference
core Struct Reference
#include <core.hpp>
Public Member Functions
core (microseconds now, const vcc_interface &vcc_drv, const temperature_interface &temp_drv, clk_interface &clk)
void tick (leds_interface &leds, microseconds now)
Public Attributes
control ctl
converter conv
metrics met
indication ind
monitor mon
Constructor & Destructor Documentation
core()
core::core (microseconds now, const vcc_interface & vcc_drv, const temperature_interface & temp_drv, clk_interface & clk) inline
References pi.
Member Function Documentation
tick()
void core::tick (leds_interface & leds, microseconds now) inline
References indication::get_state(), ind, mon, indication::tick(), monitor::tick(), and leds_interface::update().
Member Data Documentation
conv
converter core::conv
ctl
control core::ctl
ind
indication core::ind
met
metrics core::met
mon
monitor core::mon
The documentation for this struct was generated from the following file:
src/core.hpp