servio: servio::gov::gov_fixture Struct Reference
servio::gov::gov_fixture Struct Reference
#include <gov_fixture.hpp>
Public Member Functions
gov_fixture ()
void tick (handle &gov, microseconds now)
Public Attributes
sim::simple_motor motor
Constructor & Destructor Documentation
gov_fixture()
servio::gov::gov_fixture::gov_fixture () inline
References motor, and servio::sim::simple_motor::static_friction_force.
Member Function Documentation
tick()
void servio::gov::gov_fixture::tick (handle & gov, microseconds now) inline
References servio::sim::simple_motor::apply_power(), servio::sim::simple_motor::current, servio::gov::handle::current_irq(), servio::gov::handle::metrics_irq(), motor, servio::sim::simple_motor::position(), and servio::sim::simple_motor::velocity.
Member Data Documentation
motor
sim::simple_motor servio::gov::gov_fixture::motor
The documentation for this struct was generated from the following file:
src/gov/tests/gov_fixture.hpp