servio: servio::ftest::tests::meas_vel_test Struct Reference
servio::ftest::tests::meas_vel_test Struct Reference
#include <meas_test.hpp>
Public Member Functions
t::coroutine< void > run (auto &, collector &coll)
Public Attributes
t::parameters & params
drv::clk_interface & clk
drv::current_interface & curr
drv::pwm_motor_interface & motor
core::core & cor
std::string_view name = "measure_vel"
Member Function Documentation
run()
t::coroutine< void > servio::ftest::tests::meas_vel_test::run (auto & , collector & coll) inline
References cor, servio::core::core::ctl, curr, servio::mtr::metrics::get_velocity(), servio::ftest::is_powerless(), servio::core::core::met, motor, params, servio::drv::retain_callback(), servio::drv::current_interface::set_current_callback(), servio::drv::pwm_motor_interface::set_power(), and servio::ftest::setup_poweroff().
Member Data Documentation
clk
drv::clk_interface& servio::ftest::tests::meas_vel_test::clk
cor
core::core& servio::ftest::tests::meas_vel_test::cor
curr
drv::current_interface& servio::ftest::tests::meas_vel_test::curr
motor
drv::pwm_motor_interface& servio::ftest::tests::meas_vel_test::motor
name
std::string_view servio::ftest::tests::meas_vel_test::name = "measure_vel"
params
t::parameters& servio::ftest::tests::meas_vel_test::params
The documentation for this struct was generated from the following file:
src/ftest/intg/meas_test.hpp