servio: servio::drv::detailed_adc_channel< ID, N > Struct Template Reference
servio::drv::detailed_adc_channel< ID, N > Struct Template Reference
#include <adc_pooler.hpp>
Public Member Functions
void period_start (ADC_HandleTypeDef &h)
void period_stop (ADC_HandleTypeDef &h)
void conv_cplt (ADC_HandleTypeDef &)
Public Attributes
sntr::sentry sentry_
uint16_t buffer [N]
std::size_t used
uint32_t last_value
ADC_ChannelConfTypeDef chconf = {}
base::adc_detailed_cb_interface * callback = &EMPTY_ADC_DETAILED_CALLBACK
Static Public Attributes
static constexpr auto id = ID
Member Function Documentation
conv_cplt()
template<auto ID, std::size_t N> void servio::drv::detailed_adc_channel< ID, N >::conv_cplt (ADC_HandleTypeDef &) inline
period_start()
template<auto ID, std::size_t N> void servio::drv::detailed_adc_channel< ID, N >::period_start (ADC_HandleTypeDef & h) inline
References servio::drv::ADC_POOLER_CFG_ERR, servio::drv::ADC_POOLER_DSTART_ERR, servio::drv::detailed_adc_channel< ID, N >::buffer, servio::drv::detailed_adc_channel< ID, N >::chconf, servio::cfg::ID, servio::drv::detailed_adc_channel< ID, N >::sentry_, and servio::sntr::sentry::set_inoperable().
period_stop()
template<auto ID, std::size_t N> void servio::drv::detailed_adc_channel< ID, N >::period_stop (ADC_HandleTypeDef & h) inline
References servio::drv::ADC_POOLER_DSTOP_ERR, servio::drv::ADC_POOLER_NO_SAMPLES_ERR, servio::drv::ADC_POOLER_SAMPLES_OVER_ERR, servio::drv::detailed_adc_channel< ID, N >::buffer, servio::drv::detailed_adc_channel< ID, N >::callback, servio::cfg::ID, servio::drv::detailed_adc_channel< ID, N >::last_value, servio::base::adc_detailed_cb_interface::on_value_irq(), servio::drv::detailed_adc_channel< ID, N >::sentry_, servio::sntr::sentry::set_degraded(), servio::sntr::sentry::set_inoperable(), and servio::drv::detailed_adc_channel< ID, N >::used.
Member Data Documentation
buffer
template<auto ID, std::size_t N> uint16_t servio::drv::detailed_adc_channel< ID, N >::buffer[N]
callback
template<auto ID, std::size_t N> base::adc_detailed_cb_interface* servio::drv::detailed_adc_channel< ID, N >::callback = &EMPTY_ADC_DETAILED_CALLBACK
chconf
template<auto ID, std::size_t N> ADC_ChannelConfTypeDef servio::drv::detailed_adc_channel< ID, N >::chconf = {}
id
template<auto ID, std::size_t N> constexpr auto servio::drv::detailed_adc_channel< ID, N >::id = ID static constexpr
last_value
template<auto ID, std::size_t N> uint32_t servio::drv::detailed_adc_channel< ID, N >::last_value
sentry_
template<auto ID, std::size_t N> sntr::sentry servio::drv::detailed_adc_channel< ID, N >::sentry_
used
template<auto ID, std::size_t N> std::size_t servio::drv::detailed_adc_channel< ID, N >::used
The documentation for this struct was generated from the following file:
src/drv/adc_pooler.hpp