servio: servio::drv::tests::comms_echo_test Struct Reference
servio::drv::tests::comms_echo_test Struct Reference
#include <interface_tests.hpp>
Public Member Functions
t::coroutine< void > run (auto &mem, ftest::uctx &ctx)
Public Attributes
clk_iface & clk
com_iface & comms
std::string_view name = "comms_echo"
Member Function Documentation
run()
t::coroutine< void > servio::drv::tests::comms_echo_test::run (auto & mem, ftest::uctx & ctx) inline
References clk, comms, servio::ftest::uctx::expect(), servio::drv::com_iface::recv(), servio::drv::send(), servio::ftest::store_data(), and servio::drv::wait_for().
Member Data Documentation
clk
clk_iface& servio::drv::tests::comms_echo_test::clk
comms
com_iface& servio::drv::tests::comms_echo_test::comms
name
std::string_view servio::drv::tests::comms_echo_test::name = "comms_echo"
The documentation for this struct was generated from the following file:
src/drv/tests/interface_tests.hpp