servio: fw::cfg_dispatcher Struct Reference
fw::cfg_dispatcher Struct Reference
#include <cfg_dispatcher.hpp>
Public Member Functions
void operator() (const cfg_keyval &kv)
cfg_value_message get (const cfg_key &key)
void set (const cfg_key &key, const cfg_value_message &msg)
void full_apply ()
void apply (const cfg_key &key)
Public Attributes
cfg_map & map
core & c
Member Function Documentation
apply()
void fw::cfg_dispatcher::apply (const cfg_key & key)
References c, CONTROL_CURRENT_LIM_MAX, CONTROL_CURRENT_LIM_MIN, CONTROL_CURRENT_LOOP_D, CONTROL_CURRENT_LOOP_I, CONTROL_CURRENT_LOOP_P, CONTROL_POSITION_LIM_MAX, CONTROL_POSITION_LIM_MIN, CONTROL_POSITION_LOOP_D, CONTROL_POSITION_LOOP_I, CONTROL_POSITION_LOOP_P, CONTROL_VELOCITY_LIM_MAX, CONTROL_VELOCITY_LIM_MIN, CONTROL_VELOCITY_LOOP_D, CONTROL_VELOCITY_LOOP_I, CONTROL_VELOCITY_LOOP_P, fw::core::conv, fw::core::ctl, CURRENT, CURRENT_CONV_OFFSET, CURRENT_CONV_SCALE, map, MAXIMUM_TEMPERATURE, fw::core::met, MINIMUM_VOLTAGE, fw::core::mon, POSITION, POSITION_CONV_HIGHER_SETPOINT_ANGLE, POSITION_CONV_HIGHER_SETPOINT_VALUE, POSITION_CONV_LOWER_SETPOINT_ANGLE, POSITION_CONV_LOWER_SETPOINT_VALUE, REVERSED, converter::set_current_cfg(), control::set_limits(), fw::monitor::set_maximum_temperature(), fw::monitor::set_minimum_voltage(), control::set_pid(), converter::set_position_cfg(), metrics::set_position_range(), converter::set_temp_cfg(), converter::set_vcc_cfg(), TEMP_CONV_OFFSET, TEMP_CONV_SCALE, VELOCITY, and VOLTAGE_CONV_SCALE.
full_apply()
void fw::cfg_dispatcher::full_apply ()
References apply(), and map.
get()
cfg_value_message fw::cfg_dispatcher::get (const cfg_key & key)
References map.
operator()()
void fw::cfg_dispatcher::operator() (const cfg_keyval & kv) inline
References cfg_keyval::key, cfg_keyval::msg, and set().
set()
void fw::cfg_dispatcher::set (const cfg_key & key, const cfg_value_message & msg)
References apply(), and map.
Member Data Documentation
c
core& fw::cfg_dispatcher::c
map
cfg_map& fw::cfg_dispatcher::map
The documentation for this struct was generated from the following files:
src/fw/cfg_dispatcher.hpp
src/fw/cfg_dispatcher.cpp