servio: servio::parser::parser Struct Reference
servio::parser::parser Struct Reference
#include <parser.hpp>
Public Member Functions
parser (std::string_view sv)
std::size_t loc ()
bool ended ()
vari::vopt< string, float, int32_t, id_t, op_t, bool > next ()
vari::vopt< expr_t > expr ()
opt< op_t > op ()
opt< std::string_view > id ()
Public Attributes
lexer l
Constructor & Destructor Documentation
parser()
servio::parser::parser::parser (std::string_view sv) inline
Member Function Documentation
ended()
bool servio::parser::parser::ended () inline
References servio::parser::lexer::clear_ws(), and l.
expr()
vari::vopt< expr_t > servio::parser::parser::expr () inline
References l, and servio::parser::lexer::next().
id()
opt< std::string_view > servio::parser::parser::id () inline
References l, servio::parser::lexer::next(), and servio::parser::id_t::s.
loc()
std::size_t servio::parser::parser::loc () inline
References servio::parser::lexer::b, l, and servio::parser::lexer::p.
next()
vari::vopt< string, float, int32_t, id_t, op_t, bool > servio::parser::parser::next () inline
References l, servio::parser::lexer::next(), and op().
op()
opt< op_t > servio::parser::parser::op () inline
References l, servio::parser::lexer::next(), and op().
Member Data Documentation
l
lexer servio::parser::parser::l
The documentation for this struct was generated from the following file:
src/lib/parser.hpp