servio: fw::dispatcher Struct Reference
fw::dispatcher Struct Reference
#include <dispatcher.hpp>
Public Member Functions
void handle_message (const switch_to_power_command &cmd)
void handle_message (const switch_to_current_command &cmd)
void handle_message (const switch_to_velocity_command &cmd)
void handle_message (const switch_to_position_command &cmd)
void handle_message (const get_current_command &)
void handle_message (const get_vcc_command &)
void handle_message (const get_temp_command &)
void handle_message (const get_position_command &)
void handle_message (const set_config &req)
void handle_message (const get_config_request &req)
Public Attributes
comms & comm
hbridge & hb
acquisition & acquistion
control & ctl
cfg_dispatcher & cfg_disp
converter & conv
std::chrono::microseconds now
Member Function Documentation
handle_message() [1/10]
void fw::dispatcher::handle_message (const get_config_request & req) inline
References cfg_disp, comm, fw::cfg_dispatcher::get(), get_config_request::key, get_config_response::msg, and fw::comms::send().
handle_message() [2/10]
void fw::dispatcher::handle_message (const get_current_command &) inline
References acquistion, comm, conv, converter::convert_current(), fw::acquisition::get_current(), fw::hbridge::get_direction(), hb, and fw::comms::send().
handle_message() [3/10]
void fw::dispatcher::handle_message (const get_position_command &) inline
References acquistion, comm, conv, converter::convert_position(), fw::acquisition::get_position(), and fw::comms::send().
handle_message() [4/10]
void fw::dispatcher::handle_message (const get_temp_command &) inline
References acquistion, comm, conv, converter::convert_temp(), fw::acquisition::get_temp(), and fw::comms::send().
handle_message() [5/10]
void fw::dispatcher::handle_message (const get_vcc_command &) inline
References acquistion, comm, conv, converter::convert_vcc(), fw::acquisition::get_vcc(), and fw::comms::send().
handle_message() [6/10]
void fw::dispatcher::handle_message (const set_config & req) inline
References cfg_disp, set_config::key, set_config::msg, and fw::cfg_dispatcher::set().
handle_message() [7/10]
void fw::dispatcher::handle_message (const switch_to_current_command & cmd) inline
References now, and message_with_float< ID, ProtocolType >::value.
handle_message() [8/10]
void fw::dispatcher::handle_message (const switch_to_position_command & cmd) inline
References now, and message_with_float< ID, ProtocolType >::value.
handle_message() [9/10]
void fw::dispatcher::handle_message (const switch_to_power_command & cmd) inline
References getter< ID, T >::value.
handle_message() [10/10]
void fw::dispatcher::handle_message (const switch_to_velocity_command & cmd) inline
References now, and message_with_float< ID, ProtocolType >::value.
Member Data Documentation
acquistion
acquisition& fw::dispatcher::acquistion
cfg_disp
cfg_dispatcher& fw::dispatcher::cfg_disp
comm
comms& fw::dispatcher::comm
conv
converter& fw::dispatcher::conv
ctl
control& fw::dispatcher::ctl
hb
hbridge& fw::dispatcher::hb
now
std::chrono::microseconds fw::dispatcher::now
The documentation for this struct was generated from the following file:
src/fw/dispatcher.hpp