servio: cfg::dispatcher Struct Reference
cfg::dispatcher Struct Reference
#include <dispatcher.hpp>
Public Member Functions
template<key Key, typename T >
void set (const T &item)
void full_apply ()
void apply (const key &key)
Public Attributes
map & m
core & c
Member Function Documentation
apply()
void cfg::dispatcher::apply (const key & key)
References cfg::apply(), c, core::conv, core::ctl, cfg::CURRENT_CONV_OFFSET, cfg::CURRENT_CONV_SCALE, cfg::GROUP_ID, cfg::ID, m, cfg::MAXIMUM_TEMPERATURE, core::met, cfg::MINIMUM_VOLTAGE, cfg::MODEL, core::mon, cfg::MOVING_DETECTION_STEP, cfg::POSITION_CONV_HIGHER_SETPOINT_ANGLE, cfg::POSITION_CONV_HIGHER_SETPOINT_VALUE, cfg::POSITION_CONV_LOWER_SETPOINT_ANGLE, cfg::POSITION_CONV_LOWER_SETPOINT_VALUE, converter::set_current_cfg(), monitor::set_maximum_temperature(), monitor::set_minimum_voltage(), metrics::set_moving_step(), converter::set_position_cfg(), metrics::set_position_range(), converter::set_temp_cfg(), converter::set_vcc_cfg(), cfg::TEMP_CONV_OFFSET, cfg::TEMP_CONV_SCALE, and cfg::VOLTAGE_CONV_SCALE.
full_apply()
void cfg::dispatcher::full_apply ()
References apply().
set()
template<key Key, typename T > void cfg::dispatcher::set (const T & item) inline
References apply(), and m.
Member Data Documentation
c
core& cfg::dispatcher::c
m
map& cfg::dispatcher::m
The documentation for this struct was generated from the following files:
src/cfg/dispatcher.hpp
src/cfg/dispatcher.cpp