servio: servio::sim::simple_motor Struct Reference
servio::sim::simple_motor Struct Reference
#include <motor.hpp>
Public Member Functions
simple_motor ()=default
simple_motor (float pos)
void reset_time (microseconds now)
void apply_power (microseconds now, pwr p)
float position () const
Static Public Member Functions
static float resistance (float vel)
static float power_to_current (float p)
Public Attributes
float power = 0
float current = 0.F
float velocity = 0.F
angle_vec pos_vec = { 1.F, 0.f }
float last_t = 0.
float static_friction_vel = 0.02f
float static_friction_force = 0.7f
Constructor & Destructor Documentation
simple_motor() [1/2]
servio::sim::simple_motor::simple_motor () default
simple_motor() [2/2]
servio::sim::simple_motor::simple_motor (float pos) inline
References pos_vec, and servio::sim::rotate_vec().
Member Function Documentation
apply_power()
void servio::sim::simple_motor::apply_power (microseconds now, pwr p) inline
References current, last_t, pos_vec, power, power_to_current(), resistance(), servio::sim::rotate_vec(), static_friction_force, static_friction_vel, and velocity.
position()
float servio::sim::simple_motor::position () const inline
References pos_vec.
power_to_current()
static float servio::sim::simple_motor::power_to_current (float p) inline static
References servio::p_low, and servio::p_max.
reset_time()
void servio::sim::simple_motor::reset_time (microseconds now) inline
References last_t.
resistance()
static float servio::sim::simple_motor::resistance (float vel) inline static
Member Data Documentation
current
float servio::sim::simple_motor::current = 0.F
last_t
float servio::sim::simple_motor::last_t = 0.
pos_vec
angle_vec servio::sim::simple_motor::pos_vec = { 1.F, 0.f }
power
float servio::sim::simple_motor::power = 0
static_friction_force
float servio::sim::simple_motor::static_friction_force = 0.7f
static_friction_vel
float servio::sim::simple_motor::static_friction_vel = 0.02f
velocity
float servio::sim::simple_motor::velocity = 0.F
The documentation for this struct was generated from the following file:
src/sim/motor.hpp