servio: servio::parser::lexer Struct Reference
servio::parser::lexer Struct Reference
#include <parser.hpp>
Public Member Functions
lexer (std::string_view sv)
bool clear_ws ()
vari::vval< tok, end > next ()
Public Attributes
char const * b
char const * p
char const * e
Constructor & Destructor Documentation
lexer()
servio::parser::lexer::lexer (std::string_view sv) inline
Member Function Documentation
clear_ws()
bool servio::parser::lexer::clear_ws () inline
References e, servio::str_lib::bits::is_ws(), and p.
next()
vari::vval< tok, end > servio::parser::lexer::next () inline
References clear_ws(), e, servio::str_lib::s_to_nr_res::is_num, servio::str_lib::lex_letters(), p, servio::parser::parse_op(), servio::parser::parse_str(), servio::parser::id_t::s, and servio::str_lib::s_to_nr().
Member Data Documentation
b
char const* servio::parser::lexer::b
e
char const* servio::parser::lexer::e
p
char const* servio::parser::lexer::p
The documentation for this struct was generated from the following file:
src/lib/parser.hpp