servio: servio::ftest::tests::loop_frequency Struct Reference
servio::ftest::tests::loop_frequency Struct Reference
#include <benchmarks.hpp>
Public Member Functions
t::coroutine< void > run (auto &mem, uctx &ctx)
t::coroutine< float > store_as_freq (em::pmr::memory_resource &mem, uctx &coll, const std::string_view sv, std::size_t counter, base::microseconds time_window)
Public Attributes
drv::clk_iface & clk
drv::period_iface & period
drv::pos_iface & pos
drv::curr_iface & curr
std::string_view name = "loop_frequency"
Member Function Documentation
run()
t::coroutine< void > servio::ftest::tests::loop_frequency::run (auto & mem, uctx & ctx) inline
References clk, servio::ftest::uctx::coll, curr, servio::drv::period_iface::get_period_callback(), servio::drv::period_cb_iface::on_period_irq(), period, pos, servio::drv::retain_callback(), servio::drv::curr_iface::set_current_callback(), servio::drv::period_iface::set_period_callback(), servio::drv::pos_iface::set_position_callback(), store_as_freq(), servio::ftest::store_metric(), and servio::drv::wait_for().
store_as_freq()
t::coroutine< float > servio::ftest::tests::loop_frequency::store_as_freq (em::pmr::memory_resource & mem, uctx & coll, const std::string_view sv, std::size_t counter, base::microseconds time_window) inline
References servio::ftest::store_metric().
Member Data Documentation
clk
drv::clk_iface& servio::ftest::tests::loop_frequency::clk
curr
drv::curr_iface& servio::ftest::tests::loop_frequency::curr
name
std::string_view servio::ftest::tests::loop_frequency::name = "loop_frequency"
period
drv::period_iface& servio::ftest::tests::loop_frequency::period
pos
drv::pos_iface& servio::ftest::tests::loop_frequency::pos
The documentation for this struct was generated from the following file:
src/ftest/bench/benchmarks.hpp