servio: servio::drv::tests::storage_iface_test Struct Reference
servio::drv::tests::storage_iface_test Struct Reference
#include <interface_tests.hpp>
Public Member Functions
t::coroutine< void > run (auto &, ftest::uctx &ctx)
Public Attributes
cfg::map & cfg
storage_iface & iface
std::string_view name = "storage_iface"
Member Function Documentation
run()
t::coroutine< void > servio::drv::tests::storage_iface_test::run (auto & , ftest::uctx & ctx) inline
References cfg, servio::drv::storage_iface::clear_cfg(), servio::ftest::uctx::expect(), iface, servio::drv::storage_iface::load_cfg(), servio::drv::storage_iface::store_cfg(), and servio::SUCCESS.
Member Data Documentation
cfg
cfg::map& servio::drv::tests::storage_iface_test::cfg
iface
storage_iface& servio::drv::tests::storage_iface_test::iface
name
std::string_view servio::drv::tests::storage_iface_test::name = "storage_iface"
The documentation for this struct was generated from the following file:
src/drv/tests/interface_tests.hpp