servio: servio::drv::tests::position_test Struct Reference
servio::drv::tests::position_test Struct Reference
Public Member Functions
em::testing::test_coroutine run (auto &, em::testing::record &rec)
Public Attributes
base::position_interface & iface
base::clk_interface & clk
em::testing::collector & coll
std::string_view name = "pos_test"
Member Function Documentation
run()
em::testing::test_coroutine servio::drv::tests::position_test::run (auto & , em::testing::record & rec) inline
References servio::base::position_interface::get_position_callback(), servio::drv::retain_callback(), servio::base::position_interface::set_position_callback(), and servio::base::wait_for().
Member Data Documentation
clk
base::clk_interface& servio::drv::tests::position_test::clk
coll
em::testing::collector& servio::drv::tests::position_test::coll
iface
base::position_interface& servio::drv::tests::position_test::iface
name
std::string_view servio::drv::tests::position_test::name = "pos_test"
The documentation for this struct was generated from the following file:
src/drv/tests/setup_fwtest.cpp