servio: fw::standard_callbacks Struct Reference
fw::standard_callbacks Struct Reference
#include <core.hpp>
Public Member Functions
standard_callbacks (hbridge &hb, acquisition &acqui, clock &clk, control &ctl, metrics &met, const converter &conv)
Public Attributes
acquisition_period_callback period_cb
current_callback current_cb
position_callback pos_cb
Constructor & Destructor Documentation
standard_callbacks()
fw::standard_callbacks::standard_callbacks (hbridge & hb, acquisition & acqui, clock & clk, control & ctl, metrics & met, const converter & conv) inline
References pos_cb, fw::acquisition::set_current_callback(), fw::hbridge::set_period_callback(), and fw::acquisition::set_position_callback().
Member Data Documentation
current_cb
current_callback fw::standard_callbacks::current_cb
period_cb
acquisition_period_callback fw::standard_callbacks::period_cb
pos_cb
position_callback fw::standard_callbacks::pos_cb
The documentation for this struct was generated from the following file:
src/fw/core.hpp