servio: servio::gov::vel::_velocity_gov Struct Reference
servio::gov::vel::_velocity_gov Struct Reference final
#include <velocity.hpp>
Public Types
using pid_t = em::pid< typename microseconds::rep >
using pid_per = microseconds::period
Public Member Functions
_velocity_gov ()
std::string_view name () const override
servio::cfg::iface * get_cfg () override
void apply_cfg (cfg::key k)
engage_res engage (em::pmr::memory_resource &) override
status disengage (handle &) override
status on_cmd (iface::cmd_parser cmd, servio::iface::root_ser out) override
pwr current_irq (microseconds now, float current) override
void metrics_irq (microseconds now, float, float velocity, bool is_moving) override
Public Member Functions inherited from servio::gov::governor
virtual ~governor ()=default
Public Member Functions inherited from servio::gov::handle
virtual ~handle ()=default
Public Attributes
cfg::map cfg
servio::cfg::handler< cfg::map > cfg_handler
linear_transition_regulator current_scale_regl
limits< float > derived_curr_lims
float goal_vel = 0.0F
float goal_curr = 0.0F
pid_t curr_pid
pid_t vel_pid
Static Public Attributes
static constexpr auto pid_r = float{ pid_per::den } / float{ pid_per::num }
Member Typedef Documentation
pid_per
using servio::gov::vel::_velocity_gov::pid_per = microseconds::period
pid_t
using servio::gov::vel::_velocity_gov::pid_t = em::pid< typename microseconds::rep >
Constructor & Destructor Documentation
_velocity_gov()
servio::gov::vel::_velocity_gov::_velocity_gov () inline
Member Function Documentation
apply_cfg()
void servio::gov::vel::_velocity_gov::apply_cfg (cfg::key k) inline
References cfg, servio::gov::vel::cfg::curr_lim_max, servio::gov::vel::cfg::map::curr_lim_max, servio::gov::vel::cfg::curr_lim_min, servio::gov::vel::cfg::map::curr_lim_min, servio::gov::vel::cfg::curr_loop_d, servio::gov::vel::cfg::map::curr_loop_d, servio::gov::vel::cfg::curr_loop_i, servio::gov::vel::cfg::map::curr_loop_i, servio::gov::vel::cfg::curr_loop_p, servio::gov::vel::cfg::map::curr_loop_p, curr_pid, current_scale_regl, pid_r, servio::linear_transition_regulator::set_config(), servio::gov::vel::cfg::static_friction_decay, servio::gov::vel::cfg::map::static_friction_decay, servio::gov::vel::cfg::static_friction_scale, servio::gov::vel::cfg::map::static_friction_scale, servio::gov::vel::cfg::vel_lim_max, servio::gov::vel::cfg::vel_lim_min, servio::gov::vel::cfg::vel_loop_d, servio::gov::vel::cfg::map::vel_loop_d, servio::gov::vel::cfg::vel_loop_i, servio::gov::vel::cfg::map::vel_loop_i, servio::gov::vel::cfg::vel_loop_p, servio::gov::vel::cfg::map::vel_loop_p, vel_pid, and servio::gov::vel::cfg::vel_to_curr_lim_scale.
current_irq()
pwr servio::gov::vel::_velocity_gov::current_irq (microseconds now, float current) inline override virtual
Implements servio::gov::handle.
References curr_pid, derived_curr_lims, and goal_curr.
disengage()
status servio::gov::vel::_velocity_gov::disengage (handle &) inline override virtual
Implements servio::gov::governor.
References goal_vel, and servio::SUCCESS.
engage()
engage_res servio::gov::vel::_velocity_gov::engage (em::pmr::memory_resource &) inline override virtual
Implements servio::gov::governor.
References goal_vel, and servio::SUCCESS.
get_cfg()
servio::cfg::iface * servio::gov::vel::_velocity_gov::get_cfg () inline override virtual
Implements servio::gov::governor.
References cfg_handler.
metrics_irq()
void servio::gov::vel::_velocity_gov::metrics_irq (microseconds now, float , float velocity, bool is_moving) inline override virtual
Implements servio::gov::handle.
References cfg, current_scale_regl, derived_curr_lims, goal_curr, goal_vel, servio::linear_transition_regulator::state, servio::linear_transition_regulator::update(), servio::gov::vel::cfg::map::vel_lim_max, servio::gov::vel::cfg::map::vel_lim_min, vel_pid, and servio::gov::vel::cfg::map::vel_to_curr_lim_scale.
name()
std::string_view servio::gov::vel::_velocity_gov::name () const inline override virtual
Implements servio::gov::governor.
on_cmd()
status servio::gov::vel::_velocity_gov::on_cmd (iface::cmd_parser cmd, servio::iface::root_ser out) inline override virtual
Implements servio::gov::governor.
References servio::ERROR, servio::gov::vel::iface::set_stmt::goal, goal_vel, servio::gov::vel::iface::parse_vel(), servio::iface::SUCCESS, and servio::SUCCESS.
Member Data Documentation
cfg
cfg::map servio::gov::vel::_velocity_gov::cfg
cfg_handler
servio::cfg::handler< cfg::map > servio::gov::vel::_velocity_gov::cfg_handler
Initial value:
{
            cfg,
            em::member_function< &_velocity_gov::apply_cfg >{ *this } }
curr_pid
pid_t servio::gov::vel::_velocity_gov::curr_pid
current_scale_regl
linear_transition_regulator servio::gov::vel::_velocity_gov::current_scale_regl
derived_curr_lims
limits< float > servio::gov::vel::_velocity_gov::derived_curr_lims
goal_curr
float servio::gov::vel::_velocity_gov::goal_curr = 0.0F
goal_vel
float servio::gov::vel::_velocity_gov::goal_vel = 0.0F
pid_r
constexpr auto servio::gov::vel::_velocity_gov::pid_r = float{ pid_per::den } / float{ pid_per::num } static constexpr
vel_pid
pid_t servio::gov::vel::_velocity_gov::vel_pid
The documentation for this struct was generated from the following file:
src/gov/velocity/velocity.hpp