servio: servio::ftest::tests::profile Struct Reference
servio::ftest::tests::profile Struct Reference
#include <benchmarks.hpp>
Public Member Functions
t::coroutine< void > run (auto &mem, uctx &ctx)
Public Attributes
drv::clk_iface & clk
drv::curr_iface & curr
std::string_view name = "current_profile"
Member Function Documentation
run()
t::coroutine< void > servio::ftest::tests::profile::run (auto & mem, uctx & ctx) inline
References clk, servio::ftest::tests::prof_record::count, curr, servio::ftest::uctx::expect(), servio::drv::clk_iface::get_us(), servio::ftest::tests::prof_record::max, servio::ftest::tests::prof_record::min, servio::ftest::tests::PROF_BUFFER, servio::ftest::uctx::record, servio::drv::retain_callback(), servio::drv::curr_iface::set_current_callback(), servio::ftest::store_metric(), and servio::ftest::tests::prof_record::sum.
Member Data Documentation
clk
drv::clk_iface& servio::ftest::tests::profile::clk
curr
drv::curr_iface& servio::ftest::tests::profile::curr
name
std::string_view servio::ftest::tests::profile::name = "current_profile"
The documentation for this struct was generated from the following file:
src/ftest/bench/benchmarks.hpp