servio: servio::standard_callbacks Struct Reference
servio::standard_callbacks Struct Reference
#include <standard_callbacks.hpp>
Public Member Functions
standard_callbacks (pwm_motor_interface &motor, clk_interface &clk, ctl::control &ctl, mtr::metrics &met, const cnv::converter &conv)
void set_callbacks (period_interface &period, period_cb_interface &period_cb, position_interface &pos_drv, current_interface &curr_drv)
Public Attributes
current_callback current_cb
position_callback pos_cb
Constructor & Destructor Documentation
standard_callbacks()
servio::standard_callbacks::standard_callbacks (pwm_motor_interface & motor, clk_interface & clk, ctl::control & ctl, mtr::metrics & met, const cnv::converter & conv) inline
Member Function Documentation
set_callbacks()
void servio::standard_callbacks::set_callbacks (period_interface & period, period_cb_interface & period_cb, position_interface & pos_drv, current_interface & curr_drv) inline
References current_cb, pos_cb, servio::current_interface::set_current_callback(), servio::period_interface::set_period_callback(), and servio::position_interface::set_position_callback().
Member Data Documentation
current_cb
current_callback servio::standard_callbacks::current_cb
pos_cb
position_callback servio::standard_callbacks::pos_cb
The documentation for this struct was generated from the following file:
src/standard_callbacks.hpp