servio: servio::core::core Struct Reference
servio::core::core Struct Reference
#include <core.hpp>
Public Member Functions
core (microseconds now, drv::vcc_iface const &vcc_drv, drv::temp_iface const &temp_drv)
void tick (drv::leds_iface &leds, microseconds now)
Public Attributes
em::pmr::stack_resource< 1024 > gov_mem
gov::governor_manager gov_
cnv::converter conv
mtr::metrics met
mon::indication ind
mon::monitor mon
Constructor & Destructor Documentation
core()
servio::core::core::core (microseconds now, drv::vcc_iface const & vcc_drv, drv::temp_iface const & temp_drv) inline
References servio::pi.
Member Function Documentation
tick()
void servio::core::core::tick (drv::leds_iface & leds, microseconds now) inline
References servio::gov::governor_manager::active(), servio::mon::indication::get_state(), gov_, ind, mon, servio::mon::indication::tick(), servio::mon::monitor::tick(), and servio::drv::leds_iface::update().
Member Data Documentation
conv
cnv::converter servio::core::core::conv
gov_
gov::governor_manager servio::core::core::gov_
gov_mem
em::pmr::stack_resource< 1024 > servio::core::core::gov_mem
ind
mon::indication servio::core::core::ind
met
mtr::metrics servio::core::core::met
mon
mon::monitor servio::core::core::mon
The documentation for this struct was generated from the following file:
src/core/core.hpp