servio: servio::drv::tests::pwm_motor_test Struct Reference
servio::drv::tests::pwm_motor_test Struct Reference
#include <interface_tests.hpp>
Public Member Functions
auto test (ftest::uctx &ctx, pwr p, int16_t expected, std::source_location src=std::source_location::current())
t::coroutine< void > run (auto &, ftest::uctx &ctx)
Public Attributes
period_iface & period
pwm_motor_iface & iface
std::string_view name = "pwm_motor"
Member Function Documentation
run()
t::coroutine< void > servio::drv::tests::pwm_motor_test::run (auto & , ftest::uctx & ctx) inline
References servio::ftest::uctx::expect(), servio::drv::tests::hold(), iface, servio::drv::motor_info_iface::is_stopped(), period, and test().
test()
auto servio::drv::tests::pwm_motor_test::test (ftest::uctx & ctx, pwr p, int16_t expected, std::source_location src = std::source_location::current()) inline
References servio::ftest::uctx::coll, servio::ftest::uctx::expect(), servio::drv::motor_info_iface::get_direction(), iface, and servio::drv::pwm_motor_iface::set_power().
Member Data Documentation
iface
pwm_motor_iface& servio::drv::tests::pwm_motor_test::iface
name
std::string_view servio::drv::tests::pwm_motor_test::name = "pwm_motor"
period
period_iface& servio::drv::tests::pwm_motor_test::period
The documentation for this struct was generated from the following file:
src/drv/tests/interface_tests.hpp