servio: servio::ftester::test_system Struct Reference
servio::ftester::test_system Struct Reference
#include <system.hpp>
Public Member Functions
test_system (std::filesystem::path const &d_dev, uint32_t d_baudrate, std::filesystem::path const &c_dev, uint32_t c_baudrate, nlohmann::json const &input_json)
std::string suite_name () const
std::string suite_date () const
auto const & get_tests () const
bool wait_for_init ()
bool is_initializing () const
em::testing::data_tree const & get_collected () const
auto const & get_records () const
void tick ()
std::variant< em::testing::test_result, em::testing::error_variant > run_test (em::testing::test_id tid)
Constructor & Destructor Documentation
test_system()
servio::ftester::test_system::test_system (std::filesystem::path const & d_dev, uint32_t d_baudrate, std::filesystem::path const & c_dev, uint32_t c_baudrate, nlohmann::json const & input_json) inline
Member Function Documentation
get_collected()
em::testing::data_tree const & servio::ftester::test_system::get_collected () const inline
get_records()
auto const & servio::ftester::test_system::get_records () const inline
References servio::ftester::recorder::get_buffer().
get_tests()
auto const & servio::ftester::test_system::get_tests () const inline
is_initializing()
bool servio::ftester::test_system::is_initializing () const inline
run_test()
std::variant< em::testing::test_result, em::testing::error_variant > servio::ftester::test_system::run_test (em::testing::test_id tid) inline
References servio::ftester::controller_interface::res, and tick().
suite_date()
std::string servio::ftester::test_system::suite_date () const inline
suite_name()
std::string servio::ftester::test_system::suite_name () const inline
tick()
void servio::ftester::test_system::tick () inline
wait_for_init()
bool servio::ftester::test_system::wait_for_init () inline
References is_initializing(), and tick().
The documentation for this struct was generated from the following file:
src/ftester/system.hpp