servio: servio::ftest::tests::current_ctl_test Struct Reference
servio::ftest::tests::current_ctl_test Struct Reference
#include <ctl_test.hpp>
Public Member Functions
t::coroutine< void > run (auto &, collector &coll)
Public Attributes
t::parameters & params
drv::clk_iface & clk
drv::current_interface & curr
drv::pwm_motor_interface & motor
core::core & cor
std::string_view name = "ctl_test"
Member Function Documentation
run()
t::coroutine< void > servio::ftest::tests::current_ctl_test::run (auto & , collector & coll) inline
References clk, servio::core::core::conv, cor, servio::core::core::ctl, curr, servio::cnv::current(), servio::drv::clk_iface::get_us(), servio::ftest::is_powerless(), motor, params, servio::ftest::setup_poweroff(), servio::ctl::control::switch_to_current_control(), and servio::drv::wait_for().
Member Data Documentation
clk
drv::clk_iface& servio::ftest::tests::current_ctl_test::clk
cor
core::core& servio::ftest::tests::current_ctl_test::cor
curr
drv::current_interface& servio::ftest::tests::current_ctl_test::curr
motor
drv::pwm_motor_interface& servio::ftest::tests::current_ctl_test::motor
name
std::string_view servio::ftest::tests::current_ctl_test::name = "ctl_test"
params
t::parameters& servio::ftest::tests::current_ctl_test::params
The documentation for this struct was generated from the following file:
src/ftest/intg/ctl_test.hpp