servio: servio::drv::tests::cobs_uart_err_test Struct Reference
servio::drv::tests::cobs_uart_err_test Struct Reference
#include <impl_tests.hpp>
Public Member Functions
t::coroutine< void > run (auto &, ftest::uctx &ctx)
Public Attributes
clk_iface & clk
std::string_view name = "cobs_uart_err"
Member Function Documentation
run()
t::coroutine< void > servio::drv::tests::cobs_uart_err_test::run (auto & , ftest::uctx & ctx) inline
References servio::sntr::test_central_sentry::buffer, clk, servio::ftest::uctx::coll, servio::sntr::test_central_sentry::DEGR, servio::drv::cobs_uart::err_irq(), servio::ftest::uctx::expect(), servio::sntr::test_central_sentry::INOP, servio::sntr::test_central_sentry::is_inoperable(), and servio::drv::cobs_uart::tolerable_hal_errors.
Member Data Documentation
clk
clk_iface& servio::drv::tests::cobs_uart_err_test::clk
name
std::string_view servio::drv::tests::cobs_uart_err_test::name = "cobs_uart_err"
The documentation for this struct was generated from the following file:
src/drv/tests/impl_tests.hpp