servio: servio::drv::char_uart< Delims > Struct Template Reference
servio::drv::char_uart< Delims > Struct Template Reference final
#include <char_uart.hpp>
Public Member Functions
char_uart (char const *id, sntr::central_sentry_iface &central, clk_iface &clk, UART_HandleTypeDef *uart, DMA_HandleTypeDef *tx_dma)
char_uart (char_uart const &)=delete
char_uart (char_uart &&)=delete
char_uart & operator= (char_uart const &)=delete
char_uart & operator= (char_uart &&)=delete
void rx_cplt_irq (UART_HandleTypeDef *huart)
void tx_cplt_irq (UART_HandleTypeDef *huart)
void err_irq (UART_HandleTypeDef *huart)
com_res recv (std::span< std::byte > data) override
status start () override
status send (send_data_t data, microseconds timeout) override
Static Public Attributes
static constexpr char delims [] = { Delims... }
Constructor & Destructor Documentation
char_uart() [1/3]
template<char... Delims> servio::drv::char_uart< Delims >::char_uart (char const * id, sntr::central_sentry_iface & central, clk_iface & clk, UART_HandleTypeDef * uart, DMA_HandleTypeDef * tx_dma) inline
char_uart() [2/3]
template<char... Delims> servio::drv::char_uart< Delims >::char_uart (char_uart< Delims > const &) delete
char_uart() [3/3]
template<char... Delims> servio::drv::char_uart< Delims >::char_uart (char_uart< Delims > &&) delete
Member Function Documentation
err_irq()
template<char... Delims> void servio::drv::char_uart< Delims >::err_irq (UART_HandleTypeDef * huart) inline
References servio::drv::bits::uart_err_irq().
operator=() [1/2]
template<char... Delims> char_uart & servio::drv::char_uart< Delims >::operator= (char_uart< Delims > &&) delete
operator=() [2/2]
template<char... Delims> char_uart & servio::drv::char_uart< Delims >::operator= (char_uart< Delims > const &) delete
recv()
template<char... Delims> com_res servio::drv::char_uart< Delims >::recv (std::span< std::byte > data) inline override virtual
Implements servio::drv::com_iface.
References servio::drv::bits::load_message().
rx_cplt_irq()
template<char... Delims> void servio::drv::char_uart< Delims >::rx_cplt_irq (UART_HandleTypeDef * huart) inline
send()
template<char... Delims> status servio::drv::char_uart< Delims >::send (send_data_t data, microseconds timeout) inline override virtual
Implements servio::drv::com_iface.
References servio::drv::char_uart< Delims >::delims, servio::ERROR, servio::drv::spin_with_timeout(), and servio::SUCCESS.
start()
template<char... Delims> status servio::drv::char_uart< Delims >::start () inline override virtual
Implements servio::drv::com_iface.
References servio::drv::bits::uart_start_it().
tx_cplt_irq()
template<char... Delims> void servio::drv::char_uart< Delims >::tx_cplt_irq (UART_HandleTypeDef * huart) inline
Member Data Documentation
delims
template<char... Delims> constexpr char servio::drv::char_uart< Delims >::delims[] = { Delims... } static constexpr
The documentation for this struct was generated from the following file:
src/drv/char_uart.hpp