servio: servio::drv::tests::current_iface_test Struct Reference
servio::drv::tests::current_iface_test Struct Reference
#include <interface_tests.hpp>
Public Member Functions
t::coroutine< void > run (auto &mem, collector &coll)
Public Attributes
current_interface & iface
clk_interface & clk
std::string_view name = "curr_test"
Member Function Documentation
run()
t::coroutine< void > servio::drv::tests::current_iface_test::run (auto & mem, collector & coll) inline
References servio::drv::current_interface::get_current_callback(), servio::drv::retain_callback(), servio::drv::current_interface::set_current_callback(), servio::drv::tests::store_metric(), and servio::drv::wait_for().
Member Data Documentation
clk
clk_interface& servio::drv::tests::current_iface_test::clk
iface
current_interface& servio::drv::tests::current_iface_test::iface
name
std::string_view servio::drv::tests::current_iface_test::name = "curr_test"
The documentation for this struct was generated from the following file:
src/drv/tests/interface_tests.hpp