servio: servio::ftest::bench::usage Struct Reference
servio::ftest::bench::usage Struct Reference
#include <benchmarks.hpp>
Public Member Functions
t::coroutine< void > run (auto &mem, uctx &ctx)
std::size_t count_iterations (microseconds time_window)
Public Attributes
drv::period_iface & period
drv::clk_iface & clk
std::string_view name = "usage"
Member Function Documentation
count_iterations()
std::size_t servio::ftest::bench::usage::count_iterations (microseconds time_window) inline
References clk, and servio::drv::clk_iface::get_us().
run()
t::coroutine< void > servio::ftest::bench::usage::run (auto & mem, uctx & ctx) inline
References servio::ftest::uctx::coll, count_iterations(), period, servio::drv::period_iface::start(), servio::drv::period_iface::stop(), and servio::ftest::store_metric().
Member Data Documentation
clk
drv::clk_iface& servio::ftest::bench::usage::clk
name
std::string_view servio::ftest::bench::usage::name = "usage"
period
drv::period_iface& servio::ftest::bench::usage::period
The documentation for this struct was generated from the following file:
src/ftest/bench/benchmarks.hpp