servio: servio::drv::cobs_uart Struct Reference
servio::drv::cobs_uart Struct Reference final
#include <cobs_uart.hpp>
Public Member Functions
cobs_uart (char const *id, sntr::central_sentry_iface &central, clk_iface &clk, UART_HandleTypeDef *uart, DMA_HandleTypeDef *tx_dma)
cobs_uart (cobs_uart const &)=delete
cobs_uart (cobs_uart &&)=delete
cobs_uart & operator= (cobs_uart const &)=delete
cobs_uart & operator= (cobs_uart &&)=delete
void rx_cplt_irq (UART_HandleTypeDef *huart)
void tx_cplt_irq (UART_HandleTypeDef *huart)
void err_irq (UART_HandleTypeDef *huart)
com_res recv (std::span< std::byte > data) override
status start () override
status send (send_data_t data, microseconds timeout) override
Constructor & Destructor Documentation
cobs_uart() [1/3]
servio::drv::cobs_uart::cobs_uart (char const * id, sntr::central_sentry_iface & central, clk_iface & clk, UART_HandleTypeDef * uart, DMA_HandleTypeDef * tx_dma) inline
cobs_uart() [2/3]
servio::drv::cobs_uart::cobs_uart (cobs_uart const &) delete
cobs_uart() [3/3]
servio::drv::cobs_uart::cobs_uart (cobs_uart &&) delete
Member Function Documentation
err_irq()
void servio::drv::cobs_uart::err_irq (UART_HandleTypeDef * huart) inline
References servio::drv::bits::uart_err_irq().
operator=() [1/2]
cobs_uart & servio::drv::cobs_uart::operator= (cobs_uart &&) delete
operator=() [2/2]
cobs_uart & servio::drv::cobs_uart::operator= (cobs_uart const &) delete
recv()
com_res servio::drv::cobs_uart::recv (std::span< std::byte > data) inline override virtual
Implements servio::drv::com_iface.
References servio::drv::bits::load_message().
rx_cplt_irq()
void servio::drv::cobs_uart::rx_cplt_irq (UART_HandleTypeDef * huart) inline
send()
status servio::drv::cobs_uart::send (send_data_t data, microseconds timeout) override virtual
Implements servio::drv::com_iface.
References servio::ERROR, servio::drv::spin_with_timeout(), and servio::SUCCESS.
start()
status servio::drv::cobs_uart::start () inline override virtual
Implements servio::drv::com_iface.
References servio::drv::bits::uart_start_it().
tx_cplt_irq()
void servio::drv::cobs_uart::tx_cplt_irq (UART_HandleTypeDef * huart) inline
The documentation for this struct was generated from the following files:
src/drv/cobs_uart.hpp
src/drv/cobs_uart.cpp