servio: servio::drv::tests::vcc_test Struct Reference
servio::drv::tests::vcc_test Struct Reference
#include <interface_tests.hpp>
Public Member Functions
t::coroutine< void > run (auto &mem, ftest::uctx &ctx)
Public Attributes
vcc_iface & iface
std::string_view name = "vcc_test"
Member Function Documentation
run()
t::coroutine< void > servio::drv::tests::vcc_test::run (auto & mem, ftest::uctx & ctx) inline
References servio::ftest::uctx::expect(), servio::drv::vcc_iface::get_vcc(), and servio::ftest::store_metric().
Member Data Documentation
iface
vcc_iface& servio::drv::tests::vcc_test::iface
name
std::string_view servio::drv::tests::vcc_test::name = "vcc_test"
The documentation for this struct was generated from the following file:
src/drv/tests/interface_tests.hpp