servio: servio::gov::pos::_position_gov Struct Reference
servio::gov::pos::_position_gov Struct Reference final
#include <position.hpp>
Public Types
using pid = em::pid< typename microseconds::rep >
using pid_per = microseconds::period
Public Member Functions
_position_gov ()
std::string_view name () const override
servio::cfg::iface * get_cfg () override
void apply_cfg (cfg::key k)
engage_res engage (em::pmr::memory_resource &) override
status disengage (handle &) override
status on_cmd (iface::cmd_parser cmd, servio::iface::root_ser out) override
pwr current_irq (microseconds now, float current) override
void metrics_irq (microseconds now, float position, float, bool is_moving) override
Public Member Functions inherited from servio::gov::governor
virtual ~governor ()=default
Public Member Functions inherited from servio::gov::handle
virtual ~handle ()=default
Public Attributes
cfg::map cfg
servio::cfg::handler< cfg::map > cfg_handler
linear_transition_regulator current_scale_regl
limits< float > derived_curr_lims
float goal_curr = 0.0F
pid curr_pid
float goal_pos = 0.0F
pid pos_pid
Static Public Attributes
static constexpr auto pid_r = float{ pid_per::den } / float{ pid_per::num }
Member Typedef Documentation
pid
using servio::gov::pos::_position_gov::pid = em::pid< typename microseconds::rep >
pid_per
using servio::gov::pos::_position_gov::pid_per = microseconds::period
Constructor & Destructor Documentation
_position_gov()
servio::gov::pos::_position_gov::_position_gov () inline
Member Function Documentation
apply_cfg()
void servio::gov::pos::_position_gov::apply_cfg (cfg::key k) inline
References cfg, servio::gov::pos::cfg::curr_lim_max, servio::gov::pos::cfg::map::curr_lim_max, servio::gov::pos::cfg::curr_lim_min, servio::gov::pos::cfg::map::curr_lim_min, servio::gov::pos::cfg::curr_loop_d, servio::gov::pos::cfg::map::curr_loop_d, servio::gov::pos::cfg::curr_loop_i, servio::gov::pos::cfg::map::curr_loop_i, servio::gov::pos::cfg::curr_loop_p, servio::gov::pos::cfg::map::curr_loop_p, curr_pid, current_scale_regl, pid_r, servio::gov::pos::cfg::pos_lim_max, servio::gov::pos::cfg::pos_lim_min, servio::gov::pos::cfg::pos_loop_d, servio::gov::pos::cfg::map::pos_loop_d, servio::gov::pos::cfg::pos_loop_i, servio::gov::pos::cfg::map::pos_loop_i, servio::gov::pos::cfg::pos_loop_p, servio::gov::pos::cfg::map::pos_loop_p, pos_pid, servio::gov::pos::cfg::pos_to_curr_lim_scale, servio::linear_transition_regulator::set_config(), servio::gov::pos::cfg::static_friction_decay, servio::gov::pos::cfg::map::static_friction_decay, servio::gov::pos::cfg::static_friction_scale, and servio::gov::pos::cfg::map::static_friction_scale.
current_irq()
pwr servio::gov::pos::_position_gov::current_irq (microseconds now, float current) inline override virtual
Implements servio::gov::handle.
References curr_pid, derived_curr_lims, and goal_curr.
disengage()
status servio::gov::pos::_position_gov::disengage (handle &) inline override virtual
Implements servio::gov::governor.
References servio::SUCCESS.
engage()
engage_res servio::gov::pos::_position_gov::engage (em::pmr::memory_resource &) inline override virtual
Implements servio::gov::governor.
References goal_pos, and servio::SUCCESS.
get_cfg()
servio::cfg::iface * servio::gov::pos::_position_gov::get_cfg () inline override virtual
Implements servio::gov::governor.
References cfg_handler.
metrics_irq()
void servio::gov::pos::_position_gov::metrics_irq (microseconds now, float position, float , bool is_moving) inline override virtual
Implements servio::gov::handle.
References cfg, current_scale_regl, derived_curr_lims, goal_curr, goal_pos, servio::gov::pos::cfg::map::pos_lim_max, servio::gov::pos::cfg::map::pos_lim_min, pos_pid, servio::gov::pos::cfg::map::pos_to_curr_lim_scale, servio::linear_transition_regulator::state, and servio::linear_transition_regulator::update().
name()
std::string_view servio::gov::pos::_position_gov::name () const inline override virtual
Implements servio::gov::governor.
on_cmd()
status servio::gov::pos::_position_gov::on_cmd (iface::cmd_parser cmd, servio::iface::root_ser out) inline override virtual
Implements servio::gov::governor.
References servio::ERROR, servio::gov::pos::iface::set_stmt::goal, goal_pos, servio::gov::pos::iface::parse_pos(), servio::iface::SUCCESS, and servio::SUCCESS.
Member Data Documentation
cfg
cfg::map servio::gov::pos::_position_gov::cfg
cfg_handler
servio::cfg::handler< cfg::map > servio::gov::pos::_position_gov::cfg_handler
Initial value:
{
            cfg,
            em::member_function< &_position_gov::apply_cfg >{ *this } }
curr_pid
pid servio::gov::pos::_position_gov::curr_pid
current_scale_regl
linear_transition_regulator servio::gov::pos::_position_gov::current_scale_regl
derived_curr_lims
limits< float > servio::gov::pos::_position_gov::derived_curr_lims
goal_curr
float servio::gov::pos::_position_gov::goal_curr = 0.0F
goal_pos
float servio::gov::pos::_position_gov::goal_pos = 0.0F
pid_r
constexpr auto servio::gov::pos::_position_gov::pid_r = float{ pid_per::den } / float{ pid_per::num } static constexpr
pos_pid
pid servio::gov::pos::_position_gov::pos_pid
The documentation for this struct was generated from the following file:
src/gov/position/position.hpp