servio: fw::current_callback Struct Reference
fw::current_callback Struct Reference
#include <callbacks.hpp>
Public Member Functions
void operator() (uint32_t current, std::span< uint16_t >)
Public Attributes
hbridge & hb
control & ctl
const converter & conv
Member Function Documentation
operator()()
void fw::current_callback::operator() (uint32_t current, std::span< uint16_t >) inline
References conv, converter::convert_current(), fw::hbridge::get_direction(), hb, fw::hbridge::set_power(), and fw::ticks_ms().
Member Data Documentation
conv
const converter& fw::current_callback::conv
ctl
control& fw::current_callback::ctl
hb
hbridge& fw::current_callback::hb
The documentation for this struct was generated from the following file:
src/fw/callbacks.hpp