servio: servio::ftest::intg::meas_vel_test Struct Reference
servio::ftest::intg::meas_vel_test Struct Reference
#include <meas_test.hpp>
Public Member Functions
t::coroutine< void > run (auto &, uctx &ctx)
Public Attributes
t::parameters & params
drv::clk_iface & clk
drv::curr_iface & curr
drv::pwm_motor_iface & motor
core::core & cor
std::string_view name = "measure_vel"
Member Function Documentation
run()
t::coroutine< void > servio::ftest::intg::meas_vel_test::run (auto & , uctx & ctx) inline
References servio::ftest::uctx::coll, cor, servio::core::core::ctl, curr, servio::mtr::metrics::get_velocity(), servio::ftest::is_powerless(), servio::core::core::met, motor, servio::p_max, servio::p_zero, params, servio::drv::retain_callback(), servio::drv::curr_iface::set_current_callback(), servio::drv::pwm_motor_iface::set_power(), and servio::ftest::setup_poweroff().
Member Data Documentation
clk
drv::clk_iface& servio::ftest::intg::meas_vel_test::clk
cor
core::core& servio::ftest::intg::meas_vel_test::cor
curr
drv::curr_iface& servio::ftest::intg::meas_vel_test::curr
motor
drv::pwm_motor_iface& servio::ftest::intg::meas_vel_test::motor
name
std::string_view servio::ftest::intg::meas_vel_test::name = "measure_vel"
params
t::parameters& servio::ftest::intg::meas_vel_test::params
The documentation for this struct was generated from the following file:
src/ftest/intg/meas_test.hpp