servio: servio::gov::governor_manager Struct Reference
servio::gov::governor_manager Struct Reference
#include <governor_manager.hpp>
Public Member Functions
bool add_gov (governor &gov)
status disengage ()
status activate (std::string_view name, em::pmr::memory_resource &buffer)
status deactivate ()
pwr current_irq (microseconds now, float current)
void metrics_irq (microseconds now, float position, float velocity, bool is_moving)
governor * active () const
std::span< vari::vref< governor > const > governors () const
Static Public Attributes
static constexpr std::size_t n = 8
Member Function Documentation
activate()
status servio::gov::governor_manager::activate (std::string_view name, em::pmr::memory_resource & buffer) inline
References disengage(), servio::gov::governor::engage(), and servio::SUCCESS.
active()
governor * servio::gov::governor_manager::active () const inline
add_gov()
bool servio::gov::governor_manager::add_gov (governor & gov) inline
current_irq()
pwr servio::gov::governor_manager::current_irq (microseconds now, float current) inline
References servio::gov::handle::current_irq().
deactivate()
status servio::gov::governor_manager::deactivate () inline
References servio::gov::governor::disengage(), and servio::SUCCESS.
disengage()
status servio::gov::governor_manager::disengage () inline
References servio::gov::governor::disengage().
governors()
std::span< vari::vref< governor > const > servio::gov::governor_manager::governors () const inline
metrics_irq()
void servio::gov::governor_manager::metrics_irq (microseconds now, float position, float velocity, bool is_moving) inline
References servio::gov::handle::metrics_irq().
Member Data Documentation
n
constexpr std::size_t servio::gov::governor_manager::n = 8 static constexpr
The documentation for this struct was generated from the following file:
src/gov/governor_manager.hpp