servio: servio::cfg::dispatcher Struct Reference
servio::cfg::dispatcher Struct Reference
#include <dispatcher.hpp>
Public Member Functions
template<key Key, typename T >
void set (T const &item)
template<key Key>
auto const & get () const
void full_apply ()
void apply (key k)
Public Attributes
map & m
ctl::control & ctl
cnv::converter & conv
mtr::metrics & met
mon::monitor & mon
drv::pwm_motor_iface & motor
drv::get_pos_iface & pos
Member Function Documentation
apply()
void servio::cfg::dispatcher::apply (key k)
References servio::cfg::apply(), conv, ctl, servio::cfg::current_conv_offset, servio::cfg::map::current_conv_offset, servio::cfg::current_conv_scale, servio::cfg::map::current_conv_scale, servio::cfg::encoder_mode, servio::drv::get_pos_iface::get_position_range(), servio::cfg::group_id, servio::cfg::id, servio::cfg::invert_hbridge, servio::cfg::map::invert_hbridge, m, servio::cfg::maximum_temperature, servio::cfg::map::maximum_temperature, met, servio::cfg::minimum_voltage, servio::cfg::map::minimum_voltage, servio::cfg::model, mon, motor, servio::cfg::moving_detection_step, servio::cfg::map::moving_detection_step, pos, servio::cfg::position_high_angle, servio::cfg::map::position_high_angle, servio::cfg::position_low_angle, servio::cfg::map::position_low_angle, servio::cfg::quad_encoder_range, servio::cnv::converter::set_current_cfg(), servio::drv::pwm_motor_iface::set_invert(), servio::mon::monitor::set_maximum_temperature(), servio::mon::monitor::set_minimum_voltage(), servio::mtr::metrics::set_moving_step(), servio::cnv::converter::set_position_cfg(), servio::mtr::metrics::set_position_range(), servio::cnv::converter::set_temp_cfg(), servio::cnv::converter::set_vcc_cfg(), servio::cfg::temp_conv_offset, servio::cfg::map::temp_conv_offset, servio::cfg::temp_conv_scale, servio::cfg::map::temp_conv_scale, servio::cfg::voltage_conv_scale, and servio::cfg::map::voltage_conv_scale.
full_apply()
void servio::cfg::dispatcher::full_apply ()
References apply(), and servio::cfg::keys.
get()
template<key Key> auto const & servio::cfg::dispatcher::get () const inline
References m, and servio::cfg::map::ref_by_key().
set()
template<key Key, typename T > void servio::cfg::dispatcher::set (T const & item) inline
References apply(), m, and servio::cfg::map::ref_by_key().
Member Data Documentation
conv
cnv::converter& servio::cfg::dispatcher::conv
ctl
ctl::control& servio::cfg::dispatcher::ctl
m
map& servio::cfg::dispatcher::m
met
mtr::metrics& servio::cfg::dispatcher::met
mon
mon::monitor& servio::cfg::dispatcher::mon
motor
drv::pwm_motor_iface& servio::cfg::dispatcher::motor
pos
drv::get_pos_iface& servio::cfg::dispatcher::pos
The documentation for this struct was generated from the following files:
src/cfg/dispatcher.hpp
src/cfg/dispatcher.cpp