servio: servio::ftest::tests::sign_test Struct Reference
servio::ftest::tests::sign_test Struct Reference
#include <ctl_test.hpp>
Public Member Functions
t::coroutine< void > run (auto &, collector &coll)
Public Attributes
t::parameters & params
drv::clk_interface & clk
drv::current_interface & curr
drv::position_interface & pos
drv::pwm_motor_interface & motor
core::core & cor
std::string_view name = "sign_test"
Member Function Documentation
run()
t::coroutine< void > servio::ftest::tests::sign_test::run (auto & , collector & coll) inline
References clk, servio::core::core::conv, cor, servio::core::core::ctl, curr, servio::cnv::current(), servio::mtr::metrics::get_position(), servio::drv::clk_interface::get_us(), servio::mtr::metrics::get_velocity(), servio::ftest::is_powerless(), servio::core::core::met, motor, params, pos, servio::ftest::rewind(), servio::drv::pwm_motor_interface::set_power(), servio::ftest::setup_poweroff(), and servio::ctl::control::switch_to_current_control().
Member Data Documentation
clk
drv::clk_interface& servio::ftest::tests::sign_test::clk
cor
core::core& servio::ftest::tests::sign_test::cor
curr
drv::current_interface& servio::ftest::tests::sign_test::curr
motor
drv::pwm_motor_interface& servio::ftest::tests::sign_test::motor
name
std::string_view servio::ftest::tests::sign_test::name = "sign_test"
params
t::parameters& servio::ftest::tests::sign_test::params
pos
drv::position_interface& servio::ftest::tests::sign_test::pos
The documentation for this struct was generated from the following file:
src/ftest/intg/ctl_test.hpp