servio: servio::ftest::intg::meas_cur_test Struct Reference
servio::ftest::intg::meas_cur_test Struct Reference
#include <meas_test.hpp>
Public Member Functions
t::coroutine< void > run (auto &, uctx &ctx)
Public Attributes
t::parameters & params
drv::clk_iface & clk
drv::curr_iface & curr
drv::pwm_motor_iface & motor
core::core & cor
std::string_view name = "measure_current"
Member Function Documentation
run()
t::coroutine< void > servio::ftest::intg::meas_cur_test::run (auto & , uctx & ctx) inline
References clk, servio::ftest::uctx::coll, servio::core::core::conv, cor, servio::core::core::ctl, curr, servio::cnv::current(), servio::drv::clk_iface::get_us(), servio::ftest::is_powerless(), motor, servio::p_max, params, servio::drv::retain_callback(), servio::drv::curr_iface::set_current_callback(), servio::drv::pwm_motor_iface::set_power(), servio::ftest::setup_poweroff(), and servio::drv::wait_for().
Member Data Documentation
clk
drv::clk_iface& servio::ftest::intg::meas_cur_test::clk
cor
core::core& servio::ftest::intg::meas_cur_test::cor
curr
drv::curr_iface& servio::ftest::intg::meas_cur_test::curr
motor
drv::pwm_motor_iface& servio::ftest::intg::meas_cur_test::motor
name
std::string_view servio::ftest::intg::meas_cur_test::name = "measure_current"
params
t::parameters& servio::ftest::intg::meas_cur_test::params
The documentation for this struct was generated from the following file:
src/ftest/intg/meas_test.hpp