servio: servio::drv::tests::curr_iface_test Struct Reference
servio::drv::tests::curr_iface_test Struct Reference
#include <interface_tests.hpp>
Public Member Functions
t::coroutine< void > run (auto &mem, ftest::uctx &ctx)
Public Attributes
curr_iface & iface
clk_iface & clk
std::string_view name = "curr_test"
Member Function Documentation
run()
t::coroutine< void > servio::drv::tests::curr_iface_test::run (auto & mem, ftest::uctx & ctx) inline
References clk, servio::ftest::uctx::expect(), servio::drv::curr_iface::get_current_callback(), iface, servio::drv::retain_callback(), servio::drv::curr_iface::set_current_callback(), and servio::drv::wait_for().
Member Data Documentation
clk
clk_iface& servio::drv::tests::curr_iface_test::clk
iface
curr_iface& servio::drv::tests::curr_iface_test::iface
name
std::string_view servio::drv::tests::curr_iface_test::name = "curr_test"
The documentation for this struct was generated from the following file:
src/drv/tests/interface_tests.hpp