servio: servio::scmdio::stm32_bootloader_mock Struct Reference
servio::scmdio::stm32_bootloader_mock Struct Reference
Public Types
using cons = consumer< std::byte >
Public Member Functions
auto get_data ()
auto get_id_data ()
void reply_data (auto &&data)
cons state_machine ()
awaitable< void > write (std::span< std::byte const > msg) override
uint32_t conv_addr (std::span< std::byte, 4 > data)
awaitable< bool > read (std::span< std::byte > msg) override
Public Member Functions inherited from servio::scmdio::stream_iface
awaitable< void > write (std::byte b)
awaitable< opt< std::byte > > read ()
virtual ~stream_iface ()=default
Static Public Member Functions
static std::vector< std::byte > setup_mem (std::size_t k)
Public Attributes
std::vector< std::byte > memory = setup_mem(24)
std::size_t mem_offset = 0x0800'0000
std::deque< std::byte > buffer
cons c = state_machine()
Member Typedef Documentation
cons
using servio::scmdio::stm32_bootloader_mock::cons = consumer< std::byte >
Member Function Documentation
conv_addr()
uint32_t servio::scmdio::stm32_bootloader_mock::conv_addr (std::span< std::byte, 4 > data) inline
References servio::scmdio::bflash_conv(), and mem_offset.
get_data()
auto servio::scmdio::stm32_bootloader_mock::get_data () inline
get_id_data()
auto servio::scmdio::stm32_bootloader_mock::get_id_data () inline
read()
awaitable< bool > servio::scmdio::stm32_bootloader_mock::read (std::span< std::byte > msg) inline override virtual
Implements servio::scmdio::stream_iface.
References buffer.
reply_data()
void servio::scmdio::stm32_bootloader_mock::reply_data (auto && data) inline
References servio::scmdio::ACK, and buffer.
setup_mem()
static std::vector< std::byte > servio::scmdio::stm32_bootloader_mock::setup_mem (std::size_t k) inline static
state_machine()
cons servio::scmdio::stm32_bootloader_mock::state_machine () inline
References servio::scmdio::ACK, buffer, conv_addr(), servio::scmdio::GET, get_data(), servio::scmdio::GET_ID, get_id_data(), servio::scmdio::INIT, servio::scmdio::log_error(), memory, servio::scmdio::NACK, servio::scmdio::READ_MEMORY, reply_data(), and servio::scmdio::WRITE_MEMORY.
write()
awaitable< void > servio::scmdio::stm32_bootloader_mock::write (std::span< std::byte const > msg) inline override virtual
Implements servio::scmdio::stream_iface.
References c, and servio::scmdio::consumer< T >::eat().
Member Data Documentation
buffer
std::deque< std::byte > servio::scmdio::stm32_bootloader_mock::buffer
c
cons servio::scmdio::stm32_bootloader_mock::c = state_machine()
mem_offset
std::size_t servio::scmdio::stm32_bootloader_mock::mem_offset = 0x0800'0000
memory
std::vector< std::byte > servio::scmdio::stm32_bootloader_mock::memory = setup_mem(24)
The documentation for this struct was generated from the following file:
src/scmdio/tests/bflash_utest.cpp