servio: servio::core Struct Reference
servio::core Struct Reference
#include <core.hpp>
Public Member Functions
core (base::microseconds now, const base::vcc_interface &vcc_drv, const base::temperature_interface &temp_drv, base::clk_interface &clk)
void tick (base::leds_interface &leds, base::microseconds now)
Public Attributes
ctl::control ctl
cnv::converter conv
mtr::metrics met
mon::indication ind
mon::monitor mon
Constructor & Destructor Documentation
core()
servio::core::core (base::microseconds now, const base::vcc_interface & vcc_drv, const base::temperature_interface & temp_drv, base::clk_interface & clk) inline
References servio::base::pi.
Member Function Documentation
tick()
void servio::core::tick (base::leds_interface & leds, base::microseconds now) inline
References servio::mon::indication::get_state(), ind, mon, servio::mon::indication::tick(), servio::mon::monitor::tick(), and servio::base::leds_interface::update().
Member Data Documentation
conv
cnv::converter servio::core::conv
ctl
ctl::control servio::core::ctl
ind
mon::indication servio::core::ind
met
mtr::metrics servio::core::met
mon
mon::monitor servio::core::mon
The documentation for this struct was generated from the following file:
src/core.hpp