servio: servio::ftester::joque_test Struct Reference
servio::ftester::joque_test Struct Reference
Public Member Functions
joque::run_result operator() (const joque::task &)
Public Attributes
std::string name
em::testing::test_id tid
test_system & sys
std::optional< std::filesystem::path > output_dir
Member Function Documentation
operator()()
joque::run_result servio::ftester::joque_test::operator() (const joque::task &) inline
References servio::ftester::test_system::get_collected(), servio::ftester::test_system::get_records(), servio::ftester::handle_test_specifics(), name, output_dir, servio::ftester::test_system::run_test(), sys, and tid.
Member Data Documentation
name
std::string servio::ftester::joque_test::name
output_dir
std::optional< std::filesystem::path > servio::ftester::joque_test::output_dir
sys
test_system& servio::ftester::joque_test::sys
tid
em::testing::test_id servio::ftester::joque_test::tid
The documentation for this struct was generated from the following file:
src/ftester/main.cpp