servio: fw::position_callback Struct Reference
fw::position_callback Struct Reference
#include <callbacks.hpp>
Public Member Functions
void operator() (float position)
Public Attributes
control & ctl
metrics & met
Member Function Documentation
operator()()
void fw::position_callback::operator() (float position) inline
References metrics::get_position(), metrics::get_velocity(), met, and metrics::position_irq().
Member Data Documentation
ctl
control& fw::position_callback::ctl
met
metrics& fw::position_callback::met
The documentation for this struct was generated from the following file:
src/fw/callbacks.hpp