servio: fw::core Struct Reference
fw::core Struct Reference
#include <core.hpp>
Public Member Functions
core (microseconds now, const drv::vcc_interface &vcc_drv, const drv::temperature_interface &temp_drv, drv::clock &clk)
void tick (drv::leds &leds, microseconds now)
Public Attributes
control ctl
converter conv
metrics met
indication ind
monitor mon
Constructor & Destructor Documentation
core()
fw::core::core (microseconds now, const drv::vcc_interface & vcc_drv, const drv::temperature_interface & temp_drv, drv::clock & clk) inline
References pi.
Member Function Documentation
tick()
void fw::core::tick (drv::leds & leds, microseconds now) inline
References indication::get_state(), ind, mon, fw::monitor::tick(), indication::tick(), and fw::drv::leds::update().
Member Data Documentation
conv
converter fw::core::conv
ctl
control fw::core::ctl
ind
indication fw::core::ind
met
metrics fw::core::met
mon
monitor fw::core::mon
The documentation for this struct was generated from the following file:
src/fw/core.hpp