servio: servio::ftest::intg::sign_test Struct Reference
servio::ftest::intg::sign_test Struct Reference
#include <ctl_test.hpp>
Public Member Functions
t::coroutine< void > run (auto &, uctx &ctx)
Public Attributes
t::parameters & params
drv::clk_iface & clk
drv::curr_iface & curr
drv::pos_iface & pos
drv::pwm_motor_iface & motor
core::core & cor
std::string_view name = "sign_test"
Member Function Documentation
run()
t::coroutine< void > servio::ftest::intg::sign_test::run (auto & , uctx & ctx) inline
References clk, servio::ftest::uctx::coll, servio::core::core::conv, cor, servio::core::core::ctl, curr, servio::cnv::current(), servio::ftest::uctx::expect(), servio::mtr::metrics::get_position(), servio::drv::clk_iface::get_us(), servio::mtr::metrics::get_velocity(), servio::ftest::is_powerless(), servio::core::core::met, motor, servio::p_low, servio::p_zero, params, pos, servio::ftest::rewind(), servio::ftest::setup_poweroff(), servio::ctl::control::switch_to_power_control(), and servio::drv::wait_for().
Member Data Documentation
clk
drv::clk_iface& servio::ftest::intg::sign_test::clk
cor
core::core& servio::ftest::intg::sign_test::cor
curr
drv::curr_iface& servio::ftest::intg::sign_test::curr
motor
drv::pwm_motor_iface& servio::ftest::intg::sign_test::motor
name
std::string_view servio::ftest::intg::sign_test::name = "sign_test"
params
t::parameters& servio::ftest::intg::sign_test::params
pos
drv::pos_iface& servio::ftest::intg::sign_test::pos
The documentation for this struct was generated from the following file:
src/ftest/intg/ctl_test.hpp