servio: servio::scmdio::cobs_port Struct Reference
servio::scmdio::cobs_port Struct Reference
#include <port.hpp>
Public Member Functions
cobs_port (io_context &context, std::filesystem::path const &p, uint32_t baudrate)
awaitable< void > write_msg (std::span< std::byte const > msg) override
awaitable< std::span< std::byte > > read_msg (std::span< std::byte > buffer) override
Public Member Functions inherited from servio::scmdio::port_iface
virtual ~port_iface ()=default
Public Attributes
boost::asio::serial_port port
std::vector< std::byte > read_buffer
Constructor & Destructor Documentation
cobs_port()
servio::scmdio::cobs_port::cobs_port (io_context & context, std::filesystem::path const & p, uint32_t baudrate) inline
References servio::scmdio::flush_port(), and port.
Member Function Documentation
read_msg()
awaitable< std::span< std::byte > > servio::scmdio::cobs_port::read_msg (std::span< std::byte > buffer) override virtual
Implements servio::scmdio::port_iface.
References servio::scmdio::log_error(), port, and read_buffer.
write_msg()
awaitable< void > servio::scmdio::cobs_port::write_msg (std::span< std::byte const > msg) override virtual
Implements servio::scmdio::port_iface.
References servio::scmdio::log_error(), and port.
Member Data Documentation
port
boost::asio::serial_port servio::scmdio::cobs_port::port
read_buffer
std::vector< std::byte > servio::scmdio::cobs_port::read_buffer
The documentation for this struct was generated from the following files:
src/scmdio/port.hpp
src/scmdio/port.cpp