servio: servio::ftest::testing_system Struct Reference
servio::ftest::testing_system Struct Reference
#include <testing_system.hpp>
Public Member Functions
auto send_cb ()
testing_system (drv::com_iface &debug_comms, std::string_view name)
em::result send_ (uint16_t channel, const auto &data)
void tick ()
Public Attributes
drv::com_iface & debug_comms
em::testing::reactor reactor
em::testing::collector collector
em::testing::parameters parameters
em::static_function< em::result(std::span< const std::byte >), 32 > ctx_cb
uctx ctx
Constructor & Destructor Documentation
testing_system()
servio::ftest::testing_system::testing_system (drv::com_iface & debug_comms, std::string_view name) inline
References servio::ftester::rec_id, and send_().
Member Function Documentation
send_()
em::result servio::ftest::testing_system::send_ (uint16_t channel, const auto & data) inline
References debug_comms, and servio::drv::send().
send_cb()
auto servio::ftest::testing_system::send_cb () inline
References send_().
tick()
void servio::ftest::testing_system::tick () inline
References collector, debug_comms, parameters, reactor, and servio::drv::com_iface::recv().
Member Data Documentation
collector
em::testing::collector servio::ftest::testing_system::collector
ctx
uctx servio::ftest::testing_system::ctx
ctx_cb
em::static_function< em::result(std::span< const std::byte >), 32 > servio::ftest::testing_system::ctx_cb
debug_comms
drv::com_iface& servio::ftest::testing_system::debug_comms
parameters
em::testing::parameters servio::ftest::testing_system::parameters
reactor
em::testing::reactor servio::ftest::testing_system::reactor
The documentation for this struct was generated from the following file:
src/ftest/testing_system.hpp