servio: mtr::posvel_kalman Struct Reference
mtr::posvel_kalman Struct Reference
#include <posvel_kalman.hpp>
Public Member Functions
posvel_kalman (float position, limits< float > position_range)
void set_position_range (limits< float > position_range)
float get_position () const
float get_velocity () const
void update (sec_time sdiff, float position)
Public Attributes
float angle {}
kalman::state_range st_range = { .offset = 0.f, .size = 0.f }
kalman::state x {}
kalman::state_covariance P {}
float offset = 0.f
Static Public Attributes
static constexpr float observation_deviation_ = 0.000005f
static constexpr float process_deviation_ = 0.005f
static constexpr kalman::observation_model H = kalman::get_observation_model()
static constexpr kalman::observation_noise_covariance R
Constructor & Destructor Documentation
posvel_kalman()
mtr::posvel_kalman::posvel_kalman (float position, limits< float > position_range) inline
References kalman::angle(), kalman::angle_mod(), fw::position(), set_position_range(), st_range, and x.
Member Function Documentation
get_position()
float mtr::posvel_kalman::get_position () const inline
References angle.
get_velocity()
float mtr::posvel_kalman::get_velocity () const inline
References kalman::velocity(), and x.
set_position_range()
void mtr::posvel_kalman::set_position_range (limits< float > position_range) inline
References kalman::state_range::offset, kalman::state_range::size, and st_range.
update()
void mtr::posvel_kalman::update (sec_time sdiff, float position) inline
References kalman::angle(), angle, kalman::angle_mod(), kalman::get_control_input_model(), kalman::get_process_noise_covariance(), kalman::get_transition_model(), H, kalman::modify_angle(), offset, P, pi, fw::position(), kalman::predict(), process_deviation_, R, kalman::requires_offset(), st_range, kalman::update(), and x.
Member Data Documentation
angle
float mtr::posvel_kalman::angle {}
H
constexpr kalman::observation_model mtr::posvel_kalman::H = kalman::get_observation_model() static constexpr
observation_deviation_
constexpr float mtr::posvel_kalman::observation_deviation_ = 0.000005f static constexpr
offset
float mtr::posvel_kalman::offset = 0.f
P
kalman::state_covariance mtr::posvel_kalman::P {}
process_deviation_
constexpr float mtr::posvel_kalman::process_deviation_ = 0.005f static constexpr
R
constexpr kalman::observation_noise_covariance mtr::posvel_kalman::R static constexpr
Initial value:
=
            kalman::get_observation_noise_covariance( observation_deviation_ )
st_range
kalman::state_range mtr::posvel_kalman::st_range = { .offset = 0.f, .size = 0.f }
x
kalman::state mtr::posvel_kalman::x {}
The documentation for this struct was generated from the following file:
src/mtr/posvel_kalman.hpp