servio: servio::fw::persistent_config_writer Struct Reference
servio::fw::persistent_config_writer Struct Reference
#include <store_persistent_config.hpp>
Public Member Functions
bool operator() (const cfg::map *cfg)
Public Attributes
cfg::payload & last_payload
em::view< const cfg::page * > pages
base::current_interface & current_iface
Member Function Documentation
operator()()
bool servio::fw::persistent_config_writer::operator() (const cfg::map * cfg)
References servio::base::driver_interface::clear_status(), current_iface, servio::base::DEGRADED, servio::cfg::find_next_page(), servio::base::driver_interface::get_status(), servio::cfg::payload::git_ver, servio::cfg::payload::id, last_payload, pages, and servio::fw::store_persistent_config().
Member Data Documentation
current_iface
base::current_interface& servio::fw::persistent_config_writer::current_iface
last_payload
cfg::payload& servio::fw::persistent_config_writer::last_payload
pages
em::view< const cfg::page* > servio::fw::persistent_config_writer::pages
The documentation for this struct was generated from the following files:
src/fw/store_persistent_config.hpp
src/fw/store_persistent_config.cpp