servio: servio::json::jval_ser Struct Reference
servio::json::jval_ser Struct Reference
#include <json_ser.hpp>
Public Member Functions
jval_ser (em::view< std::byte * > buff) noexcept
jval_ser (em::view< char * > buff) noexcept
jval_ser & operator() (std::string_view sv) &noexcept
jval_ser & operator() (char const *st) &noexcept
jval_ser & operator() (unsigned int x) &noexcept
jval_ser & operator() (long unsigned int x) &noexcept
jval_ser & operator() (bool x) &noexcept
jval_ser & operator() (float x) &noexcept
operator em::view< std::byte * > () &&noexcept
void add (char c) noexcept
Constructor & Destructor Documentation
jval_ser() [1/2]
servio::json::jval_ser::jval_ser (em::view< std::byte * > buff) inline noexcept
jval_ser() [2/2]
servio::json::jval_ser::jval_ser (em::view< char * > buff) inline noexcept
Member Function Documentation
add()
void servio::json::jval_ser::add (char c) inline noexcept
operator em::view< std::byte * >()
servio::json::jval_ser::operator em::view< std::byte * > () && inline noexcept
operator()() [1/6]
jval_ser & servio::json::jval_ser::operator() (bool x) & inline noexcept
operator()() [2/6]
jval_ser & servio::json::jval_ser::operator() (char const * st) & inline noexcept
References add().
operator()() [3/6]
jval_ser & servio::json::jval_ser::operator() (float x) & inline noexcept
References servio::str_lib::f_to_s().
operator()() [4/6]
jval_ser & servio::json::jval_ser::operator() (long unsigned int x) & inline noexcept
References servio::str_lib::u_to_s().
operator()() [5/6]
jval_ser & servio::json::jval_ser::operator() (std::string_view sv) & inline noexcept
operator()() [6/6]
jval_ser & servio::json::jval_ser::operator() (unsigned int x) & inline noexcept
References servio::str_lib::u_to_s().
The documentation for this struct was generated from the following file:
src/lib/json_ser.hpp