var searchData=
[
  ['s_5fto_5fnr_5fres_0',['s_to_nr_res',['../namespaceservio_1_1str__lib.html#structservio_1_1str__lib_1_1s__to__nr__res',1,'servio::str_lib']]],
  ['s_5fto_5fnr_5fres_2e_5f_5funnamed1_5f_5f_1',['s_to_nr_res.__unnamed1__',['../namespaceservio_1_1str__lib.html#unionservio_1_1str__lib_1_1s__to__nr__res_8____unnamed1____',1,'servio::str_lib']]],
  ['sentry_2',['sentry',['../classservio_1_1sntr_1_1sentry.html',1,'servio::sntr']]],
  ['serial_5fcli_3',['serial_cli',['../structservio_1_1scmdio_1_1serial__cli.html',1,'servio::scmdio']]],
  ['serial_5fstream_4',['serial_stream',['../structservio_1_1scmdio_1_1serial__stream.html',1,'servio::scmdio']]],
  ['servio_5fexception_5',['servio_exception',['../structservio_1_1scmdio_1_1servio__exception.html',1,'servio::scmdio']]],
  ['set_5fstmt_6',['set_stmt',['../structservio_1_1gov_1_1curr_1_1iface_1_1set__stmt.html',1,'servio::gov::curr::iface::set_stmt'],['../structservio_1_1gov_1_1pos_1_1iface_1_1set__stmt.html',1,'servio::gov::pos::iface::set_stmt'],['../structservio_1_1gov_1_1pow_1_1iface_1_1set__stmt.html',1,'servio::gov::pow::iface::set_stmt'],['../structservio_1_1gov_1_1vel_1_1iface_1_1set__stmt.html',1,'servio::gov::vel::iface::set_stmt']]],
  ['sign_5ftest_7',['sign_test',['../structservio_1_1ftest_1_1intg_1_1sign__test.html',1,'servio::ftest::intg']]],
  ['silent_5fpeer_8',['silent_peer',['../structsilent__peer.html',1,'']]],
  ['simple_5fmotor_9',['simple_motor',['../structservio_1_1sim_1_1simple__motor.html',1,'servio::sim']]],
  ['standard_5fcallbacks_10',['standard_callbacks',['../structservio_1_1core_1_1standard__callbacks.html',1,'servio::core']]],
  ['state_5frange_11',['state_range',['../namespaceservio_1_1klmn.html#structservio_1_1klmn_1_1state__range',1,'servio::klmn']]],
  ['static_5fdetector_12',['static_detector',['../structservio_1_1mtr_1_1static__detector.html',1,'servio::mtr']]],
  ['status_5ferror_5fcategory_13',['status_error_category',['../structservio_1_1status__error__category.html',1,'servio']]],
  ['stmt_14',['stmt',['../structservio_1_1gov_1_1curr_1_1iface_1_1stmt.html',1,'servio::gov::curr::iface::stmt'],['../structservio_1_1gov_1_1pos_1_1iface_1_1stmt.html',1,'servio::gov::pos::iface::stmt'],['../structservio_1_1gov_1_1pow_1_1iface_1_1stmt.html',1,'servio::gov::pow::iface::stmt'],['../structservio_1_1gov_1_1vel_1_1iface_1_1stmt.html',1,'servio::gov::vel::iface::stmt'],['../structservio_1_1iface_1_1stmt.html',1,'servio::iface::stmt']]],
  ['stor_15',['stor',['../structservio_1_1drv_1_1mock_1_1stor.html',1,'servio::drv::mock']]],
  ['storage_5fiface_16',['storage_iface',['../structservio_1_1drv_1_1storage__iface.html',1,'servio::drv']]],
  ['storage_5fiface_5ftest_17',['storage_iface_test',['../structservio_1_1drv_1_1tests_1_1storage__iface__test.html',1,'servio::drv::tests']]],
  ['str_5ferr_18',['str_err',['../namespaceservio.html#structservio_1_1str__err',1,'servio']]],
  ['stream_5fiface_19',['stream_iface',['../structservio_1_1scmdio_1_1stream__iface.html',1,'servio::scmdio']]],
  ['sub_5freceiver_20',['sub_receiver',['../structservio_1_1ftest_1_1__rewind__sender_1_1__op_1_1sub__receiver.html',1,'servio::ftest::_rewind_sender::_op']]]
];
