---
name: build

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/emsro/build-env:latest
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.github_token }}

        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive

            - run: git config --global --add safe.directory /__w/servio/servio

            - run: make configure

            - run: make build

            - run: make test


            - uses: actions/upload-artifact@v4
              with:
                  name: proto3_fw.elf
                  path: build/h5/src/brd/proto3/proto3_fw.elf
