---
name: doxygen

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Install graphviz
              run: sudo apt install graphviz plantuml -y

            - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
