name: publish

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-22.04	
        steps:
            - name: Install graphviz
              run: sudo apt install graphviz

            - uses: JamesIves/github-pages-deploy-action@3.7.1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
