name: tests

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/emsro/build-env:latest
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.github_token }}

        defaults:
            run:
                shell:
                    bash
        steps:
            - uses: actions/checkout@v3

            - name: Test
              run: make test

            - name: Test under address sanitizer
              run: make test SANITIZER=address

            - name: Test under undefined sanitizer
              run: make test SANITIZER=undefined
