set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(STM32_TARGET_TRIPLET arm-none-eabi)

find_program(
  CMAKE_C_COMPILER
  NAMES ${STM32_TARGET_TRIPLET}-gcc
  HINTS ${TOOLCHAIN_BIN_PATH})
find_program(
  CMAKE_CXX_COMPILER
  NAMES ${STM32_TARGET_TRIPLET}-g++
  HINTS ${TOOLCHAIN_BIN_PATH})
find_program(
  CMAKE_ASM_COMPILER
  NAMES ${STM32_TARGET_TRIPLET}-gcc
  HINTS ${TOOLCHAIN_BIN_PATH})
find_program(
  CMAKE_OBJCOPY
  NAMES ${STM32_TARGET_TRIPLET}-objcopy
  HINTS ${TOOLCHAIN_BIN_PATH})
find_program(
  CMAKE_OBJDUMP
  NAMES ${STM32_TARGET_TRIPLET}-objdump
  HINTS ${TOOLCHAIN_BIN_PATH})
find_program(
  CMAKE_SIZE
  NAMES ${STM32_TARGET_TRIPLET}-size
  HINTS ${TOOLCHAIN_BIN_PATH})
find_program(
  CMAKE_DEBUGGER
  NAMES ${STM32_TARGET_TRIPLET}-gdb
  HINTS ${TOOLCHAIN_BIN_PATH})
find_program(
  CMAKE_CPPFILT
  NAMES ${STM32_TARGET_TRIPLET}-c++filt
  HINTS ${TOOLCHAIN_BIN_PATH})

set(CMAKE_EXECUTABLE_SUFFIX_C .elf)
set(CMAKE_EXECUTABLE_SUFFIX_CXX .elf)
set(CMAKE_EXECUTABLE_SUFFIX_ASM .elf)

# This should be safe to set for a bare-metal cross-compiler
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
